### ISSUE TITLE
Problem of installing ovis on CentOS 7

### ISSUE THREAD

**Issue by Mzcg** [ovis-hpc/ovis#10]
Hello ovis development team,

I am working on a project with Los Almos lab that need to install the LDMS to collect some data. I follow these instructions to install: https://www.opengridcomputing.com/wordpress/index.php/ovis-3-3-user-guide/
However, I installed all the dependencies, and follow the Quick build guide. However, after I have done the command "../configure --prefix=/home/foo/opt/ovis --enable-baler --enable-sos --enable-swig" and start doing "make", there are a few errors coming up: (the following is the screenshot)
![image](https://user-images.githubusercontent.com/41025380/42475248-b1730948-838f-11e8-8ccb-1d07e59b46ab.png)

I am not sure how to fix the undefined reference to sos_iter_pos_set or sos_iter_pos_get. I am not sure if this is version issue or not. I also checked the keyword using grep, it gave me the following result:
![image](https://user-images.githubusercontent.com/41025380/42475362-09c8338e-8390-11e8-8880-33eda55099fd.png)

Does anyone know anything about this issue? I would really appreciate for y'all helps!

Bests,
Mzcg

**Comment by baallan** [comment]
Please use the latest ldms public release on github/ovis-hpc/ovis.
You will find build instructions/recipes in github/baallan/distribution (see file rhel7/firerpms).
