### ISSUE TITLE
ldms_auth_munge doesn't check whether Munge daemon is running or not.

### ISSUE THREAD

**Issue by nichamon** [ovis-hpc/ovis#1001]
I started an LDMSD with -a munge.
```
ldmsd -x sock:10001 -a munge ...
ldmsd -x rdma:10001 -a munge ...
```
LDMSD started successfully. However, I could not ldms_ls to it, and no error messages in the LDMSD's log. With the gdb session, I found that `munge_encode` returned an error because Munge daemon wasn't running. 

Two things that we may want to address.
-  Should `ldms_auth_munge` check whether it can connect to the Munge daemon in `__auth_munge_new()`, where it creates the auth munge?
-  Should `ldms_auth_munge` logs error messages?

**Comment by nichamon** [comment]
@tom95858 @narategithub What do you think?

**Comment by tom95858** [comment]
I think there is a munge test digest we could attempt to encode/decode in the init logic. This would allow us to test at init time if the daemon was running and/or the socket was accessible.

I would like to add a logging library and move the log functions out of ldmsd. This would allow transports, authentication plugins, stores, etc... to all log messages in the same way.

**Comment by baallan** [comment]
re munge fails, we certainly need it logged.

Re logging library, it would be great if now is the time to pick up that discussion again:
https://github.com/ovis-hpc/ovis-wiki/wiki/Proposal-5

**Comment by nichamon** [comment]
> I think there is a munge test digest we could attempt to encode/decode in the init logic. This would allow us to test at init time if the daemon was running and/or the socket was accessible.

I'll add the logic to test during the init state. I'll post the patch when I'm done.

> I would like to add a logging library and move the log functions out of ldmsd. This would allow transports, authentication plugins, stores, etc... to all log messages in the same way.

I totally agree with you.
