### ISSUE TITLE
Abandoned man pages?

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#101]
The following man pages are in the source tree, but neither in the dist nor installed:

```
ldms/man/Plugin_papi.man
ldms/man/Plugin_perfevent.man
ldms/man/Plugin_procdiskstats.man
ldms/man/Plugin_rapl.man
ldms/man/Plugin_sampler_atasmart.man
ldms/man/Plugin_store_function_csv.man
```

In the case of Plugin_papi.man, there is also a Plugin_papi_sampler.man that _is_ installed.  Maybe Plugin_papi.man is an old version that should be deleted?

The others look like they still have matching plugins, so they probably just need to be added.

It does raise a question: should we unconditionally install the man page for a plugin that was not built?  We always should include it in the dist, but should it be installed if its matching plugin was not built and installed?

**Comment by morrone** [comment]
Also in the man directory, "make_exits_mans.sh" should either be added to EXTRA_DIST or cleaned up.  Nothing seems to employ the "ldmsd_exists.man" make target, which is the only thing that would use make_exits_mans.sh.

**Comment by ovis-hpc** [comment]
@morrone I think the samplers that go with those man pages haven't been moved to their own directories yet. Once they do, then the man pages will be moved.

**Comment by morrone** [comment]
@ovis-hpc, it is not clear to me that the state of subdirectories is relevant here.  There are other man pages for plugins that do not have their own subdirectories that _do_ have their man pages included from ldms/man/Makefile.am. Likewise, there are plugins that have their own subdirectories but also still have man pages in ldms/man/Makefile.am.

The issue here is that these pages are just in limbo, neither included in the dist nor installed.

The Plugin_papi.man on is the only one that doesn't seem to have a plugin that goes with it at all.

**Comment by oceandlr** [comment]
@morrone OK. I assumed without looking that those were ones that had not yet been moved and that they would be caught up at that time. It would be worth taking a look at the samplers, not only for this issue, but also to update some of the pre-array ones to array structures if desired if that is acceptable within v4 (they may be already in planned v5?) @narategithub  @baallan @tom95858
