### ISSUE TITLE
strgp_add "regex" option undocumented

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#1132]
It appears that strgp_add's "regex" option is undocumented. At least it seems to be missing from ldmsctl.man.

**Comment by tom95858** [comment]
@nichamon could you please add this documentation to the appropriate .man and usage()?

@morrone, why are you using ldmsctl instead of ldmsd_controller? Not a challenge just a question.

**Comment by morrone** [comment]
> @morrone, why are you using ldmsctl instead of ldmsd_controller? Not a challenge just a question.

I am not actually using either, I am using configuration files. But we don't have much in the way of documentation for configuration files. ldmsctl/whatever are the closest thing that gave me any answers.

**Comment by baallan** [comment]
I can confirm that it is also missing from ldmsd_controller.man.
