### ISSUE TITLE
store_avro_kafka behavior with strgp_add's "container" field

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#1134]
strgp_add requires a "container" option, even though it doesn't make great sense with the store_avro_kafka when we configure it with something like "kafka_conf=/etc/ldmsd_kafka.conf". If the kafka_conf contains "bootstrap.servers", then "containers" should really not be required.

At the moment "container" appears to _override_ bootstrap.servers. I configured "container=unused", and had the correct bootstrap.servers set, and store_avro_kafka attempts to connect to "unused:9092" rather than the servers from bootstrap.servers.

**Comment by morrone** [comment]
If it is too complicated/dirty to make the container field optional, another solution might be to just make the container value be ignored by store_avro_kafka (or maybe make it available in substitutions, but don't interpret it as the broker configuration).

**Comment by tom95858** [comment]
@morrone, I think this is resolved?

**Comment by morrone** [comment]
Yes, I think so.
