### ISSUE TITLE
Minor suggestion for Plugin_avro_kafka_store.man

### ISSUE THREAD

**Issue by jhansonhpe** [ovis-hpc/ovis#1165]
Plugin_avro_kafka_store.man provides an examples for serdes_conf  and for kafka_conf. Both use the same port number of 9092 which is the default port for broker in a Kafka configuration. The default port for schema registry (Confluent) is 8081. Hence I suggest that

serdes.schema.url=https://localhost:9092

be replaced with

serdes.schema.url=localhost:8081

Which also removes the https to more align with the other example.

**Comment by tom95858** [comment]
Thanks Jeff!

**Comment by morrone** [comment]
We should keep the "http://" part though, because serdes options usually require that. This in contrast to kafka broker entries, where the http:// is not used.
