### ISSUE TITLE
spank plugin documentation/examples/tutorial request

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#121]
A user asks by email:
"I tried to get the SLURM spank plugin and LDMS plugin to work without success. Is there any additional information other than what is provided in the man pages? Ideally, we'd like a way to tag the metrics from LDMS with one or more job IDs."

**Comment by morrone** [comment]
I too would like some better documentation on the spank plugin. How would one specify the "ovis" auth type and the location of the auth key file?

It is also a bit vague about what consumes the data, only mentioning "slurm_sampler" and "papi_sampler". Does this plugin not supply the information needed for all samplers that use "sampler_base" and the supplied jobid field? If not, why not?
