### ISSUE TITLE
v4.x ipmi plugin support requested

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#122]
A user asks by email:
"The IPMI reader and sensor plugins both assume that the sensor data is to be read over a network. Is it possible for them to read from /dev/ipmi0? For example, by default ipmitool and ipmi-sensors will read from this device by default. Or is the intention that these plugins are not to be run on the hosts they are monitoring? E.g. monitor01 runs LDMS but invokes ipmitool for a set of compute nodes? If so, how would this work with a genders set-up?"

**Comment by baallan** [comment]
The ipmi plugin is experimental, with a corresponding lack of comprehensive documentation.
@valleydlr may be able to help you further.

**Comment by valleydlr** [comment]
The IPMI reader and sensor plugins were developed specifically for reading from remote hosts. It is possible to modify them to perform collection from one or the other based on use of a configuration flag though this is not currently in process.

**Comment by oceandlr** [comment]
I am closing this.
