### ISSUE TITLE
kokkos sampler/store need to be renamed

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#123]
In meetings with multiple groups recently, the naming of the kokkos sampler/store has caused considerable confusion. Can we as part of continuing work fairly soon rename it to a prog_push[_store, _sampler] (or app_push or something more descriptive and more generic)?

The confusions it raises are:
does ldms depend on kokkos?
does the app pushing depend on kokkos?
what is kokkos?

Also, it seems to violate the directory structure conventions (a sampler under src/store/, ongoing development under store instead of under src/contrib/kokkos.

**Comment by oceandlr** [comment]
I just asked about documentation for the capability, but putting the request in the issues list is a better way! If what there is is limited, should this be a topic for a User's Group Call? @tom95858

**Comment by tom95858** [comment]
As the author of all this I wasn't invited to any of the private meetings with the multiple groups to which you allude; so unfortunately, i have no idea what was said and therefore have no idea where the confusion arises.

It seems like a good UG topic if there are Kokkos app writers that want to implement their own plugin. Note that this plugin capability is _not_ an LDMS service, but a Kokkos capability. This capability is leveraged by these plugins to publish Kokkos application data to LDMS.

**Comment by oceandlr** [comment]
The "multiple groups" is overstating it. I (at least) have been discussing the Kokkos-targetted capability as a possible option/model for getting application data into the LDMS data stream, but without ever having used it myself! The confusion has been is this Kokkos-only or can it be leveraged for non-Kokkos application data.

I think the right thing is to schedule the topic for a UG meeting. Then I and others can find out the actual capabilities and represent it properly.

**Comment by tom95858** [comment]
I will put together a presentation of Kokkos and perhaps more importantly the ldmsd_streams capability and how it is used. The Kokkos sampler and store are not general purpose, they are specifically for Kokkos data.

The ldmsd_streams API, by contrast, is a generic service provided by LDMS that allows applications to publish data (kokkos, papi, ...) to subscribers (e.g. ldmsd samplers). The interpretation of the published data (JSon), is the function of the subscriber (sampler in this case). 

This is conceptually identical to the meminfo, vmstat, etc... samplers. They understand the format of the data (/proc/meminfo, /proc/vmstat, ...) published by the kernel.

**Comment by oceandlr** [comment]
@tom95858 @valleydlr ldmsd_streams is the topic of the Jan 6 UG, is that right?

**Comment by tom95858** [comment]
The streams facility and API was presented at the LUG meeting.

**Comment by baallan** [comment]
Presentation of the streams api, while useful, did nothing to address the original issue.

Particularly,
"Also, it seems to violate the directory structure conventions (a sampler under src/store/, [and] ongoing development under store instead of under src/contrib/kokkos."

Moving the kokkos-specific bits all to src/contrib/kokkos would (optically) alleviate dependency concerns.

**Comment by tom95858** [comment]
Ok, I see the confusion. There is some leftover code (kokkos_sampler.c) in there. Only the kokkos_store.c is being built. This is supported code, it doesn't belong in contrib. I will clean up those files and post a pull request.
