### ISSUE TITLE
Containerization?

### ISSUE THREAD

**Issue by vsoch** [ovis-hpc/ovis#1261]
Hiya! I have a possibly dumb question. I've built this into a Docker container (and it seems to work) and I'm wondering what interfaces are used to derive the metrics/data? E.g., I'm wondering if I run this in Kubernetes in a sidecar pod, if the metrics would reflect the entire node the pod is on (or just the pod in question). Thanks!

**Comment by vsoch** [comment]
Is there documentation somewhere that describes the interfaces used by each sampler?

**Comment by tom95858** [comment]
The man page typically specifies which file/source from which it derives its data. Most of the /proc samplers use open/read. The ibmad, slingshot, GPU, ... samplers use whatever interfaces are required to query that data. In most cases, this is not called out in the man pages.

**Comment by vsoch** [comment]
Gotcha - thanks @tom95858! One more question - do you have an example config file that will output a json structure (as opposed to the tabular / terminal output I see by default)?

**Comment by tom95858** [comment]
@vsoch  are you tacking about ldms_ls output?

**Comment by vsoch** [comment]
Yes - and I think I know the answer to that (no) so happy to close the issue. Thanks for the help @tom95858 !
