### ISSUE TITLE
Possible memory leaks in store_avro_kafka.c

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#1275]
It looks like we are leaking memory in store_avro_kafka, becuase we can see the ldmsd aggregator's memory growing slowly without apparent bound. On a larger cluster with many more metric sets, the growth is faster.

The numbers that valgrind are reporting for the size of the leak exceed all memory reported by "ps", so it does make me question whether I should trust it. However, it pointed at a prossible problem(s) in store_avro_kafka.c:serialize_row_as_avro().

I do see at least this, that looks worrying:

avro_generic_value_new() is called to create "class" without a matching call to avro_value_iface_decref().

**Comment by tom95858** [comment]
@morrone, I think you may have found it by inspection. I had never read that part of the documentation before your clue here. I'll put something together and get you a patch later today. Thanks.
