### ISSUE TITLE
LDMSD Bug When Using IPv6 address

### ISSUE THREAD

**Issue by Snell1224** [ovis-hpc/ovis#1311]
I have a github actions .yaml file that tests the Darshan-LDMS integrated coded (i.e. darshanConnector) and noticed that it was failing to send the stream data to the LDMS streams daemon. The ``ldms_ls`` was also returning ``Connection failed/rejected``. Did some debugging and it turns out this error appeared on commit https://github.com/ovis-hpc/ovis/commit/39468f0bf3d60311b0d269a2906745064ec61791. From what I understand this commit enabled support for ipv6 by checking which ipv4/6 is enabled on the system.

My current github actions test script ran on ``ubuntu-latest`` which has ipv6 enabled so, I'm assuming, LDMS detected this and initialized a daemon using the ipv6 address (i.e. for ``localhost``) over ipv4. 

I don't know if there is an option to tell LDMS to use ipv4 over ipv6 so I ended up disabling ipv6 altogether with
``sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1``. Once disabled, the LDMSD was able to collect the streams data and ``ldms_ls`` did not return any errors. Unless there's something I'm misunderstanding, I think there is a bug somewhere in this commit. 

RECREATE PROBLEM:
Using ``build-test-ubuntu-22.04.yaml``, add the following options to enable ipv6 and re-run the script:
```
container:
        image: ovishpc/ovis-ubuntu-build
        options: --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0
```

When ipv6 is enabled:

![Screenshot 2023-12-11 152226](https://github.com/ovis-hpc/ovis/assets/60634446/e1d6cc62-fd9a-4ded-bcc6-5a35dc2ae7f4)
![Screenshot 2023-12-12 121312](https://github.com/ovis-hpc/ovis/assets/60634446/ef07b0eb-b541-44f1-b95a-68854a28ac37)

When ipv6 is disabled:

![Screenshot 2023-12-11 152344](https://github.com/ovis-hpc/ovis/assets/60634446/a6af7334-ed54-486d-ace0-b75406093993)
![Screenshot 2023-12-12 121354](https://github.com/ovis-hpc/ovis/assets/60634446/e5008dd4-ef1e-4d95-b21e-6c6ac3bb1f60)

**Comment by tom95858** [comment]
@narategithub is this still an issue or can we close this?

**Comment by narategithub** [comment]
@Snell1224 Thank you for reporting this. There is indeed a bug in the IPv6 support in the case of no listening address given. In the mean time, you can work around the issue by specifying '::' as host name and it will listen to *any* address on both IPv4 and IPv6. For example:

```sh
# xprt option in CLI
$ ldmsd -x sock:411:::
```
or

```conf
# in config file
listen port=411 xprt=sock host=::
```

**Comment by narategithub** [comment]
@Snell1224 the pull request that addressed this issue has just been merged. Could you please see if the issue is resolved?

**Comment by Snell1224** [comment]
@narategithub Yes, the issue has been resolved. Thank you for the information and fixing this!
