### ISSUE TITLE
dcgm sampler configuration error

### ISSUE THREAD

**Issue by mshow34jt** [ovis-hpc/ovis#1321]
When attempting to add DCGM_FI_DEV_NAME  (field 50) or DCGM_FI_DEV_UUID (field 54), the sampler fails to start.
Fri Jan 12 15:55:03 2024: ERROR     : msg_no 16: error -1: Plugin 'dcgm_sampler' configuration error.
Fri Jan 12 15:55:03 2024: ERROR     : Configuration error at line 10 (sampler.conf)

It doesn't really say what is wrong either. (I had to discover which fields were causing the error by trial and error)

**Comment by tom95858** [comment]
@baallan, @morrone can one of you take a look at this? If not, let me know and OGC will take a look, but we don't have this hardware.

Maybe add an error message that indicates which attribute is causing the failure and include the library's error code?

**Comment by baallan** [comment]
I can look at improving the error messages as part of refactoring the dcgm PR recently rejected.

**Comment by morrone** [comment]
@mshow34jt Are you sure there were not any additional error messages before those two?

Could you please share the configuration line?

**Comment by morrone** [comment]
@mshow34jt And what version of ldms?

**Comment by mshow34jt** [comment]
LDMSD Version: 4.4.1
This works...
load name=dcgm_sampler
config name=dcgm_sampler producer=${HOSTNAME} interval=${SAMPLE_INTERVAL} instance=${HOSTNAME}/dcgm component_id=${COMPONENT_ID} fields=55,100,101,150,155 schema=dcgmfav5

This does not work:
load name=dcgm_sampler
config name=dcgm_sampler producer=${HOSTNAME} interval=${SAMPLE_INTERVAL} instance=${HOSTNAME}/dcgm component_id=${COMPONENT_ID} fields=50,55,100,101,150,155 schema=dcgmfav5


this is the copy of the error output if either 50 or 54 are in the list of items to collect
Fri Jan 19 00:57:07 2024: DEBUG     : dcgm_sampler config() called
Fri Jan 19 00:57:07 2024: DEBUG     : dcgm_sampler gpu_schema_create()
Fri Jan 19 00:57:07 2024: ERROR     : dcgm_sampler schema creation failed.
Fri Jan 19 00:57:07 2024: DEBUG     : msg_no 16 flags 3 rec_len 83 rsp_err -1
Fri Jan 19 00:57:07 2024: ERROR     : msg_no 16: error -1: Plugin 'dcgm_sampler' configuration error.
Fri Jan 19 00:57:07 2024: ERROR     : Configuration error at line 10 (/sw/admin/ovis/conf/sampler.conf)
Fri Jan 19 00:57:07 2024: DEBUG     : mmap use at exit: mm_stat: size=524288 grain=1024 chunks_free=1 grains_free=498 grains_largest=498 grains_smallest=498 bytes_free=509952 bytes_largest=509952 bytes_smallest=509952 bytes_used+holes=14336
Fri Jan 19 00:57:07 2024: LDMSD_ LDMS Daemon exiting...status -1, Error -1 processing configuration file '/sw/admin/ovis/conf/sampler.conf'
Fri Jan 19 00:57:07 2024: LDMSD_ cleanup end.

**Comment by morrone** [comment]
Yes, it was string handling that was bad. PR is up.
