### ISSUE TITLE
Documentation request 

### ISSUE THREAD

**Issue by qwofford** [ovis-hpc/ovis#133]
I'd like to know if the mpi_profiler increments the counter before or after a function call, and I think this would be valuable information for the shm sampler readme.

It appears that the counter is incremented _after_ the function call, as per:

https://github.com/ovis-hpc/ovis/blob/d25b8747496c947b529b6ab3ae211cfaa6ad4d24/ldms/src/sampler/shm/mpi_profiler/mpi_profiler.h#L190-L197

I'm working from the OVIS-4.2.3 tag

**Comment by iramin** [comment]
Yes, that is correct. The MPI function is called first, then the post-processing is performed.

https://github.com/ovis-hpc/ovis/blob/d25b8747496c947b529b6ab3ae211cfaa6ad4d24/ldms/src/sampler/shm/mpi_profiler/wrap/input.w#L11-L16

If pre-processing is needed, a different function should be called before the actual MPI function.
