### ISSUE TITLE
dcgm_sampler fails to build with -Wall -Werror

### ISSUE THREAD

**Issue by tom95858** [ovis-hpc/ovis#1337]
Hi @morrone,

I think there's a bug in the script gen-ldms-dcgm-list-fields. I think it is generating accessor code that is failing to add a **return** at the end of main. This is happening on Power hardware.

Here's a cut and past of the error...

make[5]: Entering directory '/home/totucke/hpc_home/work/ovis-pkg/ovis/build-vortex/ldms/src/sampler/dcgm_sampler'
  CC       ldms_dcgm_list_fields-ldms-dcgm-list-fields.o
ldms-dcgm-list-fields.c: In function ‘main’:
ldms-dcgm-list-fields.c:463:1: error: control reaches end of non-void function [-Werror=return-type]
 }

Here's what I did to "fix" it; I haven't tested it.

```C
diff --git a/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields b/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields
index c4473ddd..049952b6 100755
--- a/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields
+++ b/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields
@@ -86,5 +86,6 @@ int main()
        dcgm_init();
        dump_dcgm_tags();
        dcgm_fini();
+       return 0;
 }
 EOF
```

**Comment by tom95858** [comment]
```
diff --git a/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields b/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields
index c4473ddd..049952b6 100755
--- a/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields
+++ b/ldms/src/sampler/dcgm_sampler/gen-ldms-dcgm-list-fields
@@ -86,5 +86,6 @@ int main()
        dcgm_init();
        dump_dcgm_tags();
        dcgm_fini();
+       return 0;
 }
 EOF

```

**Comment by baallan** [comment]
That fix is fine.  I think the intent is to make that main go away in a planned patch after the feedback received to the related patch on the 4.4. branch.
