### ISSUE TITLE
Help w/documentation on access control

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#139]
Is there a feature in v4 that allows an aggregator (L2) to connect to another (L1) in "read-only" mode, and if so how do I specify that? Or is this post-v4?

The use case is:
L2 is in another administrative domain and should 
* be able to get data from the L1
* not be able to send control signals changing any configuration in L1 or L0.
* not be able to (successfully) make a DOS attack on L1's aggregation ability.

Per-data-set restrictions are not important in this use case.
If the feature exists, please point me at the right man page or source code.

I'm imagining this would be a feature (read-only) somehow defined when a listening port argument is passed to ldmsd at startup.

**Comment by valleydlr** [comment]
There is currently no permissions functionality associated with a listening port. Permissions are defined on a metric set if using the "munge" authentication method.


________________________________

**Comment by tom95858** [comment]
All configuration requests are access controlled. Only a connection from the same owner/group as the running daemon can change the configuration. Status requests, however, are allowed for other. As @valleydlr mentioned access to metric sets are also controlled.

Presently, only the munge auth method provides reliable uid/gid information. ovis and none are always 0/0 and therefore are all or nothing.

**Comment by baallan** [comment]
So will the ogc munge extension work in progress in some way enable the scenario where L2 and its local munge is not in on the secret of the munge on the L1 server?

**Comment by tom95858** [comment]
The multi-domain munge support will allow the aggregator to associate some endpoints with one domain and others with a second domain. But even absent that support, if a user other than the euid/egid of the running ldmsd daemon cannot modify the running configuration. The munge support simply allows the daemon to reliably know the remote euid/egid.
