### ISSUE TITLE
Updtr_status_summary Missing in 4.4.3

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#1399]
Hi all,

I wanted to use the updtr_status_summary referenced in Jim's provisioning ldmscon talk last year but I don't see the command in the current ldmsd_controller. Is that still a functionality? I'd like to see oversampled and skipped counters.

Thanks!

**Comment by nichamon** [comment]
@bschwal The command is `updtr_status`. `summary` is an attribute. I can't find a place in the provisioning slides from ldmscon2023 that refers to `updtr_status_summary`. 

To get the oversampled and skipped counters, run `updtr_status` in `ldmsd_controller`. Do `help updtr_status` for brief description of each attribute, including the description of `oversampled` and `skipped` counters. This works in any v4.4 series and v4.3.11.
