### ISSUE TITLE
error R_X86_64_PC32 while linking swig 

### ISSUE THREAD

**Issue by StefanA-AWS** [ovis-hpc/ovis#147]
Hi,

I have a version of LDMS compiled using "../configure --prefix=$OVIS_HOME; make; make install"

If I add --enable-swig to the setup, I get this error :
--
make[5]: Entering directory `/home/ec2-user/ovis/src/ovis-4.2/build/ldms/swig'
  CCLD     _ldms.la
/usr/bin/ld: .libs/_ldms_la-ldms.o: relocation R_X86_64_PC32 against undefined symbol `ldms_rbuf_desc_array_metric_value_get' can not be used when making a shared object; recompile with -fPIC
--
Here I allready added -fPIC but I still got the error. 

Any idea what I'M doing wrong ?

Thanks

Stefan

**Comment by narategithub** [comment]
@StefanA-AWS what is the version of swig you are using?

**Comment by StefanA-AWS** [comment]
[ec2-user@ip-10-0-0-44 ~]$ swig -version

SWIG Version 2.0.10

Compiled with g++ [x86_64-redhat-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
[ec2-user@ip-10-0-0-44 ~]$

**Comment by StefanA-AWS** [comment]
To test, I installed swig 4.0.1 and now I get a different error :

 make[4]: Entering directory `/home/ec2-user/ovis/src/ovis-4.2/build/lib/swig'
 Making all in zap
 make[5]: Entering directory `/home/ec2-user/ovis/src/ovis-4.2/build/lib/swig/zap'
 /usr/local/bin/swig -python -I../../../../lib/src -o zap.c ../../../../lib/swig/zap/zap.i
 make  all-am
 make[6]: Entering directory `/home/ec2-user/ovis/src/ovis-4.2/build/lib/swig/zap'
  CC       _zap_la-zap.lo
  CCLD     _zap.la

 libtool: link: only absolute run-paths are allowed 
make[6]: *** [_zap.la] Error 1
 make[6]: Leaving directory `/home/ec2-user/ovis/src/ovis-4.2/build/lib/swig/zap'

**Comment by StefanA-AWS** [comment]
OK, this can be closed. After @narategithub  hint, I installed newer version of swig and bison, run autoconf.sh under sudo, deleted all 'build' files and redid it. Now it is working for me.

**Comment by andyw-lala** [comment]
Surely the solution to this is improving the configure rules to flag inadequate packages ?

Perhaps open a specific issue targeting configure stage referencing this issue (and others, if appropriate)
