### ISSUE TITLE
LDMS Users group

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#15]
Topic: LDMS Users Group
Schedule below. For call in info and notes, please see the [ovis-hpc/ovis wiki](https://github.com/ovis-hpc/ovis/wiki/User-Group-Meeting-Notes)

=======================================================

Time: Jan 21, 2019 12:00 PM Mountain Time (US and Canada)

Every 2 weeks on Mon, until May 27, 2019, 10 occurrence(s)

Jan 21, 2019 12:00 PM

Feb 4, 2019 12:00 PM

Feb 18, 2019 12:00 PM

Mar 4, 2019 12:00 PM

Mar 18, 2019 12:00 PM

Apr 1, 2019 12:00 PM

Apr 15, 2019 12:00 PM

Apr 29, 2019 12:00 PM

May 13, 2019 12:00 PM

May 27, 2019 12:00 PM

https://zoom.us/j/599135580

One tap mobile

+16468769923,,599135580# US (New York)

+16699006833,,599135580# US (San Jose)

Dial by your location

+1 646 876 9923 US (New York)

+1 669 900 6833 US (San Jose)

Meeting ID: 599 135 580

**Comment by oceandlr** [comment]
quick start video from users group meeting has been posted

**Comment by ovis-hpc** [comment]
closing issue since the links are in the sidebar
