### ISSUE TITLE
edac sampler issue

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#163]
Scenario: 
Running only edac sampler on a broadwell node with RHEL 7.7. Installed OVIS 4.3.3. The edac sampler gets a single set of metrics and then seems to fail on the subsequent sample. LDMS DEBUG and INFO logs do not show any other pertinent information.   

ldmsd.log:

ERROR     : 'edac': failed to sample. Stopping the plug-in.

valgrind:

--160672-- Reading syms from /opt/ovis/sandia-nosos-ovis-ldms_4.3.3/root/usr/lib64/ovis-ldms/libedac.so.
0.0.0
--160672-- Reading syms from /opt/ovis/sandia-nosos-ovis-ldms_4.3.3/root/usr/lib64/libsampler_base.so.0.0.0
--160672-- REDIR: 0x5f226d0 (libc.so.6:__strcpy_sse2_unaligned) redirected to 0x4c2d0c0 (strcpy)
--160672-- REDIR: 0xffffffffff600000 (???:???) redirected to 0x580c66a7 (???)
--160672-- REDIR: 0xffffffffff600400 (???:???) redirected to 0x580c66b1 (???)
==160672== Thread 6:
==160672== Invalid read of size 4
==160672==    at 0x409D68: release_ovis_scheduler (ldmsd.c:572)
==160672==    by 0x409DF5: stop_sampler (ldmsd.c:680)
==160672==    by 0x409DF5: plugin_sampler_cb (ldmsd.c:697)
==160672==    by 0x66BAEB8: ovis_event_heap_process (ovis_event.c:393)
==160672==    by 0x66BAEB8: ovis_scheduler_loop (ovis_event.c:657)
==160672==    by 0x409011: event_proc (ldmsd.c:1424)
==160672==    by 0x6CD3EA4: start_thread (pthread_create.c:307)
==160672==    by 0x5F868CC: clone (clone.S:111)
==160672==  Address 0x7a245bc is 4 bytes before a block of size 16 alloc'd
==160672==    at 0x4C2BF79: calloc (vg_replace_malloc.c:762)
==160672==    by 0x40C15B: main (ldmsd.c:1830)

**Comment by baallan** [comment]
verified this problem still exists on cts1 class hardware; checking into why

**Comment by baallan** [comment]
addressed by #1195
