### ISSUE TITLE
LDMS V4 Video Request list

### ISSUE THREAD

**Issue by ovis-hpc** [ovis-hpc/ovis#17]
We will be populating the wiki with demo videos. Please add your Video demo requests to this issue. Current requests include:
* overview with how the data can be used
* cluster build and configuration
* new feature: failover
* new feature: metric set groups and vectors of sets
* papi sampler (coming soon)
* Cray Aries network metrics - samplers and use
* Storage and Analysis interactions -- Hello World of python-based analysis using the Scalable Object Store (SOS)

**Comment by ovis-hpc** [comment]
Please add to the video push vs pull and automatic failover (now in the Quickstart documentation)

**Comment by oceandlr** [comment]
quick start video from users group meeting has been posted

**Comment by DebRez** [comment]
Please add a video with how to set up sosdb-ui and sosdb-grafana and how to use it.
