### ISSUE TITLE
Building v4 Beta with ovis-pkg-latest-stable | new excludes

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#18]
For ovis-pkg-latest-stable 4.1.1 I had previously needed to add the below excludes to ovis-ldms.spec and comment out all kokkos related statements.

%exclude %{_libdir}/ovis-ldms/libdstat.*
%exclude %{_libdir}/libparse_stat.*

I now need to add this exclude for it to finish building. 

%exclude %{_libdir}/ovis-ldms/libstore.*
%exclude %{_libdir}/ovis-ldms/libstore_none.*

**Comment by bschwal** [comment]
Also needed to massage ovis-ldms.spec to allow for sos version 4.1.1 but that was minor.

**Comment by oceandlr** [comment]
@bschwal Can we close this issue or is it still relevant to OVIS-4.3.3 GA?
