### ISSUE TITLE
Building v4 Beta, SOS issues

### ISSUE THREAD

**Issue by joncooknmsu** [ovis-hpc/ovis#19]
I did a public grab of v4_Beta, used git submodule to get SOS, and ran into the following problems:
1. The ovis INSTALL file suggests that building ovis will build SOS if it is there, but it did not, for me. I had to build SOS first and then use "--with-sos=/sos/install/path" to get configure to finish.
2. Then in compiling I get the errors below, which to me look like the default SOS that I grabbed with the git submodule command is an incompatible (older?) version. The SOS version information is below the compile errors.
  CC       libmap_la-libmap.lo
../../../../lib/src/coll/libmap.c: In function ‘map_transform’:
../../../../lib/src/coll/libmap.c:235:7: warning: implicit declaration of function ‘sos_key_for_attr’ [-Wimplicit-function-declaration]
  if (!sos_key_for_attr(trans_key, map_s->src_attr, match_val))
       ^
../../../../lib/src/coll/libmap.c: In function ‘map_transform_min’:
../../../../lib/src/coll/libmap.c:285:41: error: ‘sos_index_find_min’ undeclared (first use in this function)
  return __attr_find(ret, map->tgt_attr, sos_index_find_min);
                                         ^
../../../../lib/src/coll/libmap.c:285:41: note: each undeclared identifier is reported only once for each function it appears in
../../../../lib/src/coll/libmap.c: In function ‘map_transform_max’:
../../../../lib/src/coll/libmap.c:290:41: error: ‘sos_index_find_max’ undeclared (first use in this function)
  return __attr_find(ret, map->tgt_attr, sos_index_find_max);
                                         ^
../../../../lib/src/coll/libmap.c: In function ‘map_inverse_min’:
../../../../lib/src/coll/libmap.c:295:41: error: ‘sos_index_find_min’ undeclared (first use in this function)
  return __attr_find(ret, map->src_attr, sos_index_find_min);
                                         ^
../../../../lib/src/coll/libmap.c: In function ‘map_inverse_max’:
../../../../lib/src/coll/libmap.c:300:41: error: ‘sos_index_find_max’ undeclared (first use in this function)
  return __attr_find(ret, map->src_attr, sos_index_find_max);
                                         ^
SOS Version info:
~/tools/ovis/sos$ git status
HEAD detached at ba9a4db
nothing to commit, working directory clean

(I couldn't find any other SOS branch I should be on; the above is from just doing "git submodule init" and then "git submodule update")

**Comment by joncooknmsu** [comment]
I get the same compile errors with the latest public github SOS. Nothing fancy in my ovis build: 
../configure --enable-appinfo --enable-sos --prefix=/home/jcook/tools --with-sos=/home/jcook/tools

**Comment by oceandlr** [comment]
SOS as a submodule is going to be pulled out of v4. Please build without it for now.
