### ISSUE TITLE
trouble building cray_system_sampler

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#199]
I haven't built OVIS-4 since Nov. 

Now trying to build libcray_aries_r_sampler.la
I am getting cannot find --lluster_sampler

Looks like @baallan did some changes in the lustre directory as part of f1b15aa. Could this be part of the problem? Has anyone built this the cray_aries_sampler recently?

@valleydlr

**Comment by baallan** [comment]
@oceandlr you meant @valleydlr

**Comment by baallan** [comment]
fixed in pr #201

**Comment by oceandlr** [comment]
Thanks! I just tried this! I will mark +1 on pr #201.
