### ISSUE TITLE
LANL Trinity seeing segfaults from Slurm jobinfo sampler

### ISSUE THREAD

**Issue by KevinStroup** [ovis-hpc/ovis#202]
LANL reported that large jobs (1000 nodes or more) are occasionally (less then 10% of the time) failing in the Slurm prolog (and maybe epilog?) with a seg fault. If they disable that sampler the problem appears to go away. They are discussing the pros & cons of reconfiguring Trinity not to  run that sampler.

**Comment by tom95858** [comment]
Can you be more specific about which sampler we are talking about? Is this the spank plugin configured in plugstack.conf or is this the version that involves writing entries to a file in /tmp from the job prolog?

**Comment by tom95858** [comment]
PS: Can someone with Q take a look at the stack trace and tell me where it's crashing?

**Comment by KevinStroup** [comment]
My understanding is that it is the spank plugin configured in plugstack.conf

**Comment by KevinStroup** [comment]
From: "Cotton, Travis Bradley" <trcotton@lanl.gov>
Date: Monday, March 23, 2020 at 1:57 PM
To: "Stroup, Kevin Dale" <kdstrou@sandia.gov>, "Fullop, Joseph Patrick IV (LANL)" <fullop@lanl.gov>
Subject: Re: [EXTERNAL] Re: [ovis-hpc/ovis] LANL Trinity seeing segfaults from Slurm jobinfo sampler (#202)

I have some core dumps we got on gadget if that helps.
I didn’t find them to be super helpful, but they are available.
 
Just to be clear, there are no logs or messages that say “ldms crashed”.
 
What the slurm logs do say, is that the spank prolog/epilog is crashing when trying to load a plugin library (something.so)
I came to the conclusion that it might be ldms because we see the issue when ldms is enabled, we don’t see it when it is disabled.
 
I can grab the output of gdb on the core dump if that would help.
 
Travis

**Comment by KevinStroup** [comment]
From: "Fullop, Joshi" <fullop@lanl.gov>
Date: Monday, March 23, 2020 at 1:59 PM
To: "Cotton, Travis Bradley" <trcotton@lanl.gov>, "Stroup, Kevin Dale" <kdstrou@sandia.gov>
Subject: Re: [EXTERNAL] Re: [ovis-hpc/ovis] LANL Trinity seeing segfaults from Slurm jobinfo sampler (#202)

There is a segfault in libRT.so error 14 (userspace access of invalid memory).

**Comment by tom95858** [comment]
Is there a stack trace available? I would like to confirm where it is crashing so that we can resolve the issue.

When you say 'ldms is enabled', do you mean when the slurm_notifier.so spank plugin is enabled in the plugstack.conf file?
