### ISSUE TITLE
Install script util/nola.sh assumes everything under $prefix is readable

### ISSUE THREAD

**Issue by joncooknmsu** [ovis-hpc/ovis#204]
Script util/nola.sh seems to be removing old lib files, and so should only do a find in $prefix/lib, but it does it for all of $prefix. If there are other directories in there not readable by user, it fails and the 'make install' fails. This is on the OVIS-4 branch, not sure about others.

**Comment by baallan** [comment]
pull request #206 addresses this. Jon should test (he doesn't appear as an option for assignee/reviewer, however.

**Comment by baallan** [comment]
A patch fixing this for v4 has been merged.
