### ISSUE TITLE
remove v4_static_version_missing branch from ovis-hpc/ovis repo

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#215]
I pushed a development branch to the wrong remote.
What's the blessed way on github to delete this branch?
@narategithub @tom95858

**Comment by tom95858** [comment]
Hi @baallan, can't you just navigate to the branch and delete it? I don't think there is anything special about that.

**Comment by baallan** [comment]
Would love to, but no branch management buttons (other than change view) are presented in my view of the code/branch. I could probably merge it and then get a delete button, but that's not how we're handling pull requests as I understand it.

**Comment by baallan** [comment]
ah ok. found the branches tab has a branch list and a delete button that works. closing this issue.
