### ISSUE TITLE
json/json_util.h conflicts with common library in redhat (v4, v5(?))

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#222]
The json-c redhat package already uses the include/json subdirectory.
lib/src/json needs to install its includes to $incdir/ovis_json and the include statements we use need to be updated to <ovis_json/*> from <json/*>

Rpm conflict message from redhat install:
	file /usr/include/json/json_util.h from install of ovis-ldms-devel-4.3.4-1.1.ch6_1.x86_64 conflicts with file from package json-c-devel-0.11-4.el7_0.x86_64

**Comment by tom95858** [comment]
How does this even happen? It should be ${prefix}/include. How is this ending up in /usr/include?

**Comment by baallan** [comment]
prefix is /usr when building toss packages.

**Comment by baallan** [comment]
@tom95858  The llnl toss folk put all production admin daemons in /usr. They told us not to put it in /opt, when asked, for production use. I did not pick /usr for my benefit.  This goes all the way back to the v2 toss releases.

**Comment by tom95858** [comment]
Erf...Well I don't like the name of that header file anyway, so I don't mind changing it, however, I think we should move _all_ of our -devel headers to include/ovis because this absolutely will happen again and it seems like we should be proactive about avoiding collisions.

**Comment by baallan** [comment]
I absolutely agree with moving to include/ovis and a corresponding ldms/include in our source tree that unifies all the headers under lib/src and ldms/src. But this seems like a v5 thing since it would break third party plugin code.

**Comment by oceandlr** [comment]
@ballan @tom95858 I was looking for json thread in which to stick this question. (there was another older one #74 --- is that still active?). Question is:
I am looking to use a json parser. should I be trying to use the one in ovis/lib and, if so, is there example input for the json_test in sbin? or should I try to use a system one, and, if so, is there a canonical one I should try?

**Comment by baallan** [comment]
@oceandlr If you want to use json in ldms plugins, please use the json we have in lib. It should be in progress of being renamed slightly so that it does not conflict with system headers.  If you're doing general work, redhat comes with a stock json parser that (as Tom noted elsewhere) has deficiencies. You should also be aware that most json implementations don't support unsigned 64 bit and the json spec itself excludes NaN and Inf so you may be wanting another language entirely if looking to serialize results from science codes.  json.org has a catalog of options including c and c++ choices. I have an extended cJSON library from my ldms webstore work.

**Comment by oceandlr** [comment]
Thanks, @baallan. Are there some instructions on the API, or an example? I will just be doing some simple things, like parsing  "a=b c=d" into json format or taking a well-known list of "x,y,z"  and  putting it into json format.

**Comment by baallan** [comment]
@oceandlr https://github.com/ovis-hpc/ovis/blob/OVIS-4/lib/src/json/json_test.c is the only documentation/example I've noticed beyond the headers.

**Comment by tom95858** [comment]
Hi @oceandlr, if you are trying to generate JSON formatted strings, most of the code uses fprintf, or similar. If you're trying to parse JSON formatted content, check out ldms_xprt.c, __process_dir_reply. This function uses the parser to decode the JSON formatted dictionaries that are exchanged on the wire as part of ldms_xprt_dir().

**Comment by oceandlr** [comment]
Hi @tom95858 I want to take some text and turn it into json. I want to use the json format to push it in that form to the ldms_streams interface. Later of course, I will want to extract fields in the json to write it to a store. I do have issue #239 about extracting from ldms_streams.

**Comment by tom95858** [comment]
Hi @oceandlr, there are API that are kind of printf++. Check out src/sampler/spank/slurm_notifier.c uses these API. If you want to convert empire timing logs to JSon, I could code up an example translator if you like.

**Comment by oceandlr** [comment]
Hi @tom95858 if it is trivial for you, then I'd be happy for an example! In the meantime I will look at the code you suggest. The example you mention may not be the raw format I'm currently playing with (I'm also trying to do this with some MILC timing info), but I'm sure any example will help!

**Comment by morrone** [comment]
Yes, ovis's json_util (both the header _and_ the library) need to move. I started down that path in PR#82. It was decided that the library would be renamed, but it looks like that didn't happen yet.

While we are at it "libjson_parser" and "json_parser/json.h" should be moved under a ovis/lmds specific directories or given more ovis/ldms specific names.

**Comment by morrone** [comment]
Oh, nevermind about *_parser, I see that code was dropped post 4.3.3.

**Comment by morrone** [comment]
@tom95858 , you mentioned moving the header to "include/ovis". In 4.3.X that installed directory does not appear to exist. And "ovis" a a project repo is rapidly becoming just "ldms". So where do we want to go with this custom json library? Is it intended to be supplied by ldms, or as a general "ovis" library that multiple projects will use?

If the latter, then maybe the longer term goal would be to create a separate ovis library repo and put the shared libraries in there. In the short term to support that, I might make a patch to move the json lib to "ovis" names and subdirectories.

But if it will stay part of ldms, then perhaps I would instead move it to "ldms" names and subdirectories.
