### ISSUE TITLE
Systemd Aggregator Integration Issue

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#27]
The LDMSD_AUTH_OPTION="-A conf=/opt/ovis/etc/ldms/ldmsauth.conf" is necessary for the ldmsd.aggregator service to work properly. It is defined as a variable in .env file however it is not included in the ldmsd.aggregator.service file. For reasons I'm not 100% on, when not including this option ldms does not look in the default location for the authentication config and will therefore return this error: 

ERROR     : 'sock' transport creation with auth 'ovis' failed, error: ENOENT(2). Please check transpot configuration, authentication configuration, ZAP_LIBPATH (env var), and LD_LIBRARY_PATH.

Please add the authentication option to the aggregator service code and maybe add LDMS_AUTH_FILE environment variable to the .env file to make sure it is absorbed into the systemctl call.

**Comment by bschwal** [comment]
Actually, on the intel x86_64 platform I'm testing on, even referring to the LDMSD_AUTH_OPTION variable does not work. -A conf=/opt/ovis/etc/ldms/ldmsauth.conf must be put directly in the .service file.

**Comment by eric-roman** [comment]
I had to add $LDMSD_AUTH_OPTION to the systemd service files.  In the ExecStart lines add $LDMSD_AUTH_OPTION.  It needs to be $LDMSD_AUTH_OPTION not ${LDMSD_AUTH_OPTION} to ensure that the whitespace quoting is done correctly.

**Comment by bschwal** [comment]
Ah I see. Thank you! Is there anyway to make that file location the default where ovis authentication looks? Or to add verbosity to the error statement?

**Comment by bschwal** [comment]
I ran with $LDMS_AUTH_OPTION and still found that it was failing. The only way I've found it to work is with the full -A conf=/opt/ovis/etc/ldms/ldmsauth.conf. Any suggestions?

**Comment by baallan** [comment]
can we close this?

**Comment by bschwal** [comment]
I haven't tested this on the newest OVIS version so I'm unsure if all is well.
