### ISSUE TITLE
extraneous branches in the repo?

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#270]
@tom95858 @nichamon 
There are some branches in ovis-hpc/ovis instead of in a personal repo:
OVIS-4
OVIS-4-ref
OVIS-4-ref-ldms_ls-fix
normalize-JSON-config

Do you mean for these to be there?

**Comment by tom95858** [comment]
Hi @oceandlr ,

Yes, these are 'unstable' development branches on OVIS-4 that will end up being merged when they are fully tested/vetted.

**Comment by oceandlr** [comment]
Ok - thanks.
