### ISSUE TITLE
autoconf test allows any yacc, but ldms json lib requires bison extensions

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#280]
It looks like ovis ldms just uses "AC_PROG_YACC", which will check for any of bison, byacc, or yacc.

But it appears that ldms relies on at least one bison-specific extension. in compilation of ldms's custom json library, it uses "$(YACC) --defines=", and I believe that "--defines" is a bison extension.

So we either need a better autoconf test, or we need the compilation reworked to work with the lowest common denominator yacc.

**Comment by tom95858** [comment]
Hi @morrone,

Have you actually encountered an issue or is this speculative. There is no such thing as 'yacc' on any GNU platform that I know of because that code is proprietary ATT-SYS-V. The yacc command is simply a link to bison.

Tom

**Comment by morrone** [comment]
I actually encountered the issue.

byacc appears to be the default "yacc" in TOSS3, which probably means that it is the default in RHEL7.

**Comment by tom95858** [comment]
Wow, well that is disappointing. But byacc (Berkeley Yacc) is not the default on RHEL7 because that's my development platform and I would have seen this already. I guess we can implement our own OVIS_PROG_YACC macro that doesn't accept byacc. What's your inclination?

**Comment by morrone** [comment]
Have you checked "rpm -qf /bin/yacc" and "rpm -qf /usr/bin/yacc"? Because if you have bison installed, then autoconf is probably selecting that rather than the default yacc command.

I would use suggest using the name "BISON", not "YACC" since bison is specifically what is required. And AC_CHECK_PROG may be sufficient; it might not need wrapping in a new macro.

**Comment by tom95858** [comment]
Hi @morrone, ok I see, so we use AC_PROG_YACC to set up the BISON/YACC, etc... vars, and then use AC_CHECK_PROG($(BISON)) to check for bison in particular?

**Comment by morrone** [comment]
PR #282 is what I was thinking.

**Comment by morrone** [comment]
PR was merged.
