### ISSUE TITLE
v4 app_sampler has no man page

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#289]
ldmsd_app_sampler.md (or whatever content describes the v4 app_sampler plugin) has not been ported to OVIS-4 from master.

**Comment by tom95858** [comment]
@narategithub can you please back-port the man page from master for this sampler?

**Comment by narategithub** [comment]
@tom95858 sure.

**Comment by narategithub** [comment]
@baallan it is already in OVIS-4 branch: https://github.com/ovis-hpc/ovis/blob/OVIS-4/ldms/man/Plugin_app_sampler.man

**Comment by baallan** [comment]
I thought all new samplers were keeping their associated man/script files in with their source subdirectory.

**Comment by narategithub** [comment]
@baallan This was probably posted/merged before I knew the new location decision.
