### ISSUE TITLE
ldmsd_updtr_state_str bug

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#29]
In https://github.com/ovis-hpc/ovis/blob/master/ldms/src/core/ldmsd.h the inline function provokes compiler warning on every file which includes ldmsd.h. Either the switch should use 'default: return "BAD STATE";' or the case LDMSD_UPDTR_STATE_STOPPING should be handled. Ideally, it should be both, as C provides no guarantee that a passed enum value is a valid enum member.

static inline const char *ldmsd_updtr_state_str(enum ldmsd_updtr_state state) {
        switch (state) {
        case LDMSD_UPDTR_STATE_STOPPED:
                return "STOPPED";
        case LDMSD_UPDTR_STATE_RUNNING:
                return "RUNNING";
        }
        return "BAD STATE";
}

**Comment by valleydlr** [comment]
This should be posted to gitlab (dev environment).
