### ISSUE TITLE
papi sampler silently fails when config file not found

### ISSUE THREAD

**Issue by eric-roman** [ovis-hpc/ovis#293]
In `papi_process_config_file` a failure of a call to `stat` does not produce an error message.  As a result, no error message is produced when a user specifies a papi configuration file that does not exist.

Please add an error message in the papi sampler for the case where stat fails.

**Comment by tom95858** [comment]
Hi @eric-roman , this is addressed in commit c459054a0c623758167a87adadba0e88df23ecf6 in the OVIS-4 branch
