### ISSUE TITLE
Building with ovis-pkg, cython version issue

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#31]
I am building ovis 4.2.1-rc1 with ovis-pkg. I found that using the latest stable python package provided by RHEL (0.19-5) the sos build fails with multiple cython errors: "Obtaining 'char const *' from temporary Python value." I used Cython-0.29 directly from cython.org and that built without error.

**Comment by baallan** [comment]
This has been reported upstream:
https://gitlab.opengridcomputing.com/tom/SOS/issues/6 last year.
The anaconda2 python distribution also works when building sos (modulo extraneous ; bug)
