### ISSUE TITLE
hello_stream build issues

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#310]
The new hello_stream sampler (on the OVIS-4) has some oddities in the build system.

First, there is a perl script named "parser.pl" that is installed under sysconfdir (/etc/sysconfig with some default installs). I do not think that sysconfdir is the correct place for a script like this. Additionally, anything that we install needs less generic naming than "parser.pl".

Next, the package installs config file into:

```$(sysconfdir)/ldms/hello_sampler_util```

Everything else installs into ${sysconfdir)/ldms.d, not $(sysconfdir)/ldms. That is probably a bug?

Also, we should probably try to avoid the use of custom install-data-local/uninstall-local hooks for simple file installs. I think something like this:

```
STREAM_FILES = \
       $(srcdir)/hello_stream1.conf \
       $(srcdir)/hello_stream_store.conf \
       ${srcdir}/README


HELLO_CONF_DIR = $(DESTDIR)$(sysconfdir)/ldms/hello_sampler_util/stream_configs
install-data-local: $(STREAM_FILES)
       $(MKDIR_P) $(HELLO_CONF_DIR)
       $(INSTALL_DATA) $(STREAM_FILES) $(HELLO_CONF_DIR)/


uninstall-local:
       rm -rf $(STREAM_DIR)
```

can be done something like this instead:

```

helloconfigsdir = $(sysconfdir)/ldms.d/hello_sampler_util/stream_configs
helloconfigs_DATA = hello_stream1.conf \
                                  hello_stream_store.conf \
                                  README
```

**Comment by oceandlr** [comment]
Hi @morrone 

Right now the streams utilities are in use case testing, and intended to be supported in V4. The goal was to get some of the support utilities in an encapsulated place, consistent with similar utilities. In this case, the utilities for the hello_stream should be in encapsulated in <InstallDir>/etc/ldms/hello_sampler_util which is at the same level as <InstallDir>/etc/ldms/aries_mmr_set_configs.  The utilities include this parser as well as example configs for the use of streams. 

Are you saying this is not happening?

**Comment by morrone** [comment]
@oceandlr,yeah, sorry, you are correct that it winds up in /etc/ldms/hello_sampler_util when using the default system prefix.
That is just the first thing that I've seen do that. Everything that we currently install is under /etc/sysconfig/ldms.d. So if that is the intended path, I'll package that one up too. /etc/ldms sounds like a better path for longer term ldms configuration than /etc/sysconfig/ldms.d anyway.

The other issues of perl scripts in /etc and avoiding the custom hooks still stand.

**Comment by morrone** [comment]
If you mean the perl script, for instance, when you say "utilities", /etc is probably just not the place for that.

**Comment by oceandlr** [comment]
@morrone  - this isn't the only utility aid there (you might not have the Aries ones if you aren't building for XC). I'll take a look to see what else might be similar and if there is a either a better place or an agreed upon philosophy re /etc.

agreed, will change name of parser.pl. It's not required for the use of the hello_streams, just there as a demo aid. That's why it's not with other binaries. I thought the encapsulation was sufficient.

**Comment by morrone** [comment]
> @morrone - this isn't the only utility aid there (you might not have the Aries ones if you aren't building for XC). I'll take a look to see what else might be similar and if there is a either a better place or an agreed upon philosophy re /etc.

Right, I haven't fully scanned the tree to see what needs fixing. I'm just focusing on the stuff that we use for now. But I have no problem with this one being fixed together with other places now that it has been identified.

> agreed, will change name of parser.pl. It's not required for the use of the hello_streams, just there as a demo aid. That's why it's not with other binaries. I thought the encapsulation was sufficient.

If it is expected to work as is, it should probably be given a good name and put in a "bin" location. If it is only expected to be documentation, then "share" might be a better place for it. /etc is for configuration, as per the Linux FHS.

Are you expecting that a file like /etc/ldms/hello_stream/stream_configs/hello_stream1.conf would somehow be directly loaded by the ldmsd at run time? What would tell the ldmsd to load that file? I ask, because this does seem like exactly the thing that I would expect to find somewhere under /etc/sysconfig/ldms.d, so I'm not sure why some things use that base path and others use /etc/ldms.

I almost wonder if _all_ of the /etc/ldms/hello_stream contents should be considered documentation and put under /usr/share. Because normally if a file just has a name like "*.conf*" in /etc, we would expect it to be loaded by its associated service when it starts up (in this case ldmsd). That is clearly not what we would want here. We need sysadmins to make a conscious choice to enable something like this, and to configure it correctly. So for things like that, we might prefer to have the name be "*.conf.example" so it isn't accidentally loaded.

I guess all of this gets replaced anyway once we have first class configuration files for ldmsd. But that could be quite some time before we see that in a release, so perhaps some cleanup now is still justified.

**Comment by oceandlr** [comment]
Re conf file --- no, its an example of the conf file. Since stream is push as opposed to the canonical operation which is a pull, in the conf is a "subscribe" vs an "updater" and I thought it was work having that example somewhere (in addition to the man page). ".example" extension is a good suggestion - thanks!

I'm ok with /share if that's more appropriate. @valleydlr @tom95858 I will take a look and see what else we might think about moving at the same time.

**Comment by oceandlr** [comment]
@tom95858 @valleydlr @baallan Any problems if I put in a change to V4 that a) gets rid of /etc/ldms and b) puts aries_mmr_set_configs and hello_sampler_util into XXX/share/doc/ovis-ldms-X.Y.Z/<some new dir name> or XXX/share/doc/ovis-ldms-X.Y.X/examples/<some new dir name>, with the latter preferable? 

Those seem to be the only 2 of the case that @morrone is concerned about.

**Comment by baallan** [comment]
@oceandlr please use a subdirectory of share/doc/ovis-ldms-X.Y.X/examples/ rather than dropping single files at the top level.
It already has subdirs static-test and slurm-test.

**Comment by oceandlr** [comment]
@baallan I wasn't going to do that. The two cases mentioned are directories.

**Comment by baallan** [comment]
excellent. thanks.

**Comment by oceandlr** [comment]
Move to share has been completed
