### ISSUE TITLE
Auth munge configuration issue

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#318]
We chatted briefly about auth munge with rdma on the LDMS call this morning. This is the follow-up ticket.

My error has changed from what I recall seeing last time, so perhaps some bug has been addressed in the scripts. I am using, commit 5040632 on OVIS-4 (plus a couple of unrelated changes).

The error that I currently see is:

```
ldmsd[67238]: Mon Jul 20 12:24:56 2020: ERROR     : 'rdma' transport creation with auth 'munge' failed, error: ENOENT(2). Please check transpot configuration, authentication configuration, ZAP_LIBPATH (env var), and LD_LIBRARY_PATH.
```

In /etc/sysconfig/ldms.d/ldmsd.local.conf, there are only two things that are uncommented:

```
LDMS_AUTH_TYPE=munge
LDMS_GENDERS="/etc/genders"
```

@baallan , @tom95858

**Comment by baallan** [comment]
The message is a C-level error.
Can you include the command line you're (via genders) using to start ldmsd?
It should be found in: /var/run/ldmsd/ldmsd.start.local
or some similarly located .start. file.

**Comment by baallan** [comment]
Also handy would be as much of /var/run/ldmsd/ldmsd.env.local as you can share and as much of /var/run/ldmsd/all-config.local as you can share.

**Comment by morrone** [comment]
Yes, it looks like this:

```
    /usr/sbin/ldmsd -c /var/run/ldmsd/all-config.local -a munge -A conf=/etc/sysconfig/ldms.d/ClusterSecrets/local.ldmsauth.conf -r /var/run/ldmsd/ldmsd-local.pid -x rdma:411 -P 4 -v ERROR

```

The "conf=" is definitely wrong. So I try setting:

```
LDMS_AUTH_FILE=LDMS_AUTH_FILE=/var/run/munge/munge.socket.2
```

That yields this:

```
    /usr/sbin/ldmsd -c /var/run/ldmsd/all-config.local -a munge -A conf=/var/run/munge/munge.socket.2 -r /var/run/ldmsd/ldmsd-local.pid -x rdma:411 -P 4 -v ERROR

```

This results in the same error.  This also looks wrong, because the ldms_auth_munge man page says that the option should be "-A socket=PATH".  So I will try running the command line by hand and see what happens:

```
# /usr/sbin/ldmsd -c /var/run/ldmsd/all-config.local -a munge -A socket=/var/run/munge/munge.socket.2 -r /var/run/ldmsd/ldmsd-local.pid -x rdma:411 -P 4 -v ERROR
[root@opal160:ldms.d]# Mon Jul 20 13:35:17 2020: ERROR     : 'rdma' transport creation with auth 'munge' failed, error: ENOENT(2). Please check transpot configuration, authentication configuration, ZAP_LIBPATH (env var), and LD_LIBRARY_PATH.
Mon Jul 20 13:35:17 2020: CRITICAL  : LDMSD_ LDMS Daemon exiting...status 6, error creating transport
Mon Jul 20 13:35:17 2020: CRITICAL  : LDMSD_ cleanup end.
```

I also tried leaving off the "-A" option all together. Same error.

**Comment by morrone** [comment]
/var/run/ldmsd/all-config.local is:

```
load name=meminfo
# config sampler with defaults
config name=meminfo producer=opal160 instance=opal160/meminfo component_id=161
start name=meminfo interval=1000000 offset=0
load name=llnl_lustre_client
# config sampler with defaults
config name=llnl_lustre_client producer=opal160 instance=opal160/llnl_lustre_client component_id=161
start name=llnl_lustre_client interval=1000000 offset=0
#
# end metric sets section
#
# aggregator config args computed with /usr/bin/ldmsctl_args3 -n opal160 -g /var/run/ldmsd/genderscratch/genders.local
#
# end aggregation section
#
```

I also tried commenting out all lines related to llnl_lustre_clients to make sure that wasn't somehow mucking things up (although if it was, ldlms would have some serious error message repair needed). Still get the error.

**Comment by morrone** [comment]
So with the all_config.local listed above, can we maybe start with the question of why this command does not work?

```
# /usr/sbin/ldmsd -c /var/run/ldmsd/all-config.local -a munge -A socket=/var/run/munge/munge.socket.2 -r /var/run/ldmsd/ldmsd-local.pid -x rdma:411 -P 4 -v DEBUG
# Mon Jul 20 13:53:17 2020: INFO      : Processing the config file '/var/run/ldmsd/all-config.local' is done.
Mon Jul 20 13:53:17 2020: ERROR     : 'rdma' transport creation with auth 'munge' failed, error: ENOENT(2). Please check transpot configuration, authentication configuration, ZAP_LIBPATH (env var), and LD_LIBRARY_PATH.
Mon Jul 20 13:53:17 2020: CRITICAL  : LDMSD_ LDMS Daemon exiting...status 6, error creating transport
Mon Jul 20 13:53:17 2020: CRITICAL  : LDMSD_ cleanup end.
```

Also, the same error messages are printed when the "-A" option is left out of the above command.

**Comment by morrone** [comment]
Sigh. I don't think the auth munge plugin was built. Guys, this should have been a much easier problem that this has been. Error messages are important.

**Comment by baallan** [comment]
yes. ldms/src/core/ldms_xprt.c is in dire need of logging for error cases. The tricky bit is which cases, as we expect transport to fail and retry in many cases. Obviously missing plugin is not something retry is going to fix.

**Comment by morrone** [comment]
@baallan, is there a way to set default auth permissions in ldmsd? Or is it just left to every individual plugin to implement that themselves (granted, the some of the individual plugins may use sampler_base to do it themselves)?

**Comment by baallan** [comment]
not entirely sure what you're asking. we broke out the auth settings config from sampler_base recently:  pr #268

**Comment by morrone** [comment]
I am asking if there is a way to, in one place, say that I want the default uid to be "0", the default gid to be "0", and the default perms to be "755" for all metrics. Can I do that?

It is great to _allow_ every metric to set its own permissions if that is needed, but there should be a place to set the defaults for all metrics in absence of explicit configuration in each individual metric.

**Comment by baallan** [comment]
at the ldms level, perms are on the set-instance level, as that is the unit of transport.
sampler_base parses options with default perm "777" and uid/gid taken from current user.

You could patch to extend the defaults to be taken from LDMS_SET_GID_DEFAULT, LDMS_SET_PERM, etc. The base_auth_parse is easy to extend provided its documented also.

**Comment by morrone** [comment]
And as far as I can tell, the default perms are not 777. Maybe I am misinterpretting what I am seeing, but if a sampler does not call ldms_set_config_auth(), I am not seeing it at all. I did see the metric under auth ovis, but not in auth munge.

If you are suggestind that LDMS_SET_GID_DEFAULT and LDMS_SET_PERM are C defines, that is not what I want at all. I am talking about runtime configuration. base_auth_parse() is not the correct place to do that either because, again, every sampler has to volunatrily do that. I want this to be a default that is correctly set, through a runtime configuration option, at the ldmsd level.

**Comment by baallan** [comment]
see sampler_base.c:429 for 777. I was thinking the all caps bit as environment variables, not defines.

**Comment by morrone** [comment]
Right, that is the manual, every sampler needs to do its on its own approach, perhaps with the help of code in sampler_base.

Like I said, I would like to see it build into ldmsd proper. In other words, when a plugin calls ldms_set_new(), the returned ldms_set_t will already contain the global metric permissions that the user has configured in the ldmsd.

Right now it does the following:

```
ldms_set_t ldms_set_new(const char *instance_name, ldms_schema_t schema)
{
        return ldms_set_new_with_auth(instance_name, schema, geteuid(), getegid(), 0777);
}
```

For some reason that does not appear to be working for my plugins at the moment. I need to investigate why my metrics only appear with auth ovis, and not with auth munge.

**Comment by morrone** [comment]
Now my metric data is appearing. A moment before it wasn't. I have no idea what happened.

**Comment by baallan** [comment]
did you pick up alpha.1?
Tom merged passel of fixes to ovis-4.

**Comment by morrone** [comment]
@baallan I expanded on your suggestion to use environment variables, and opened a new ticket, #331, to propose the uid/gid/perm defaults . I have other issues open with other auth munge questions, so I think I can close this one now.

The problem with the bad error message is broken out into issue #332.
