### ISSUE TITLE
index error in stop sampler

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#322]
I reliably get an array out of bounds on a no-tricks array used in ldmsd.c (valgrind trace below) with OVIS-4 when a sampler fails to sample and gets stopped. The sampler in this case is procnetdev and the daemon is doing nothing else.

Without valgrind, code runs but at exit is a stack dump (further below).
If the plugins all run well, the non-valgrind exit is clean. This suggests the stop sampler is corrupting other memory.
This can be reproduced (after pr 321 is accepted) with ldms-static-test.sh fail_sampler_procnetdev.

==97355== Invalid read of size 4
==97355==    at 0x40B02C: release_ovis_scheduler (ldmsd.c:577)
==97355==    by 0x40B407: stop_sampler (ldmsd.c:685)
==97355==    by 0x40B4AF: plugin_sampler_cb (ldmsd.c:702)
==97355==    by 0x4E51D9B: ovis_event_heap_process (ovis_event.c:393)
==97355==    by 0x4E526EF: ovis_scheduler_loop (ovis_event.c:657)
==97355==    by 0x40CF0F: event_proc (ldmsd.c:1429)
==97355==    by 0x4EB7C47: start_thread (pthread_create.c:309)
==97355==    by 0x4B5F5FF: thread_start (clone.S:91)
==97355==  Address 0x509264c is 4 bytes before a block of size 4 alloc'd
==97355==    at 0x4875D8C: calloc (vg_replace_malloc.c:711)
==97355==    by 0x40EB53: main (ldmsd.c:1947)

Non valgrind exit dump in log file:
Mon Jul 20 14:17:04 2020: INFO      : LDMSD_ LDMS Daemon exiting...status 0, 
*** Error in `ldmsd.61026': free(): invalid next size (fast): 0x0000000000471b40 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d58c)[0x4000002bd58c]
ldmsd.61026(cleanup+0x148)[0x40a7b8]
ldmsd.61026(cleanup_sa+0x54)[0x40acbc]
[0x40000005066c]
/lib64/libc.so.6(nanosleep+0x28)[0x4000002ea9d8]
/lib64/libc.so.6(usleep+0x48)[0x40000031704c]
ldmsd.61026(main+0x2778)[0x40fcf8]
/lib64/libc.so.6(__libc_start_main+0xf0)[0x4000002615d4]
ldmsd.61026[0x40998c]
======= Memory map: ========
00400000-00440000 r-xp 00000000 00:2f 119193673

**Comment by tom95858** [comment]
@baallan can you please confirm that commit e72b33db114f0645e0221f974be49f61fa0f8c1d fixes this issue.

**Comment by baallan** [comment]
exit and valgrind are happy with this change.
