### ISSUE TITLE
Request for sos and baler support for ldms v4

### ISSUE THREAD

**Issue by kalasagar211** [ovis-hpc/ovis#33]
I used  https://github.com/ovis-hpc/ovis/wiki/QuickStart-%28v4%29 link to install and working fine without munge 

But i want to use baler and sos. 

How to use them with ldms. Plase help me. 

is there any monitoring gui to integrate ldms? 

thanks
sagar

**Comment by valleydlr** [comment]
Hi Sagar,

Baler is no longer packaged with LDMS and SOS and gpcd are no longer submodules. Baler and SOS will be exposed on this site soon as separate projects along with documentation.

Thanks
