### ISSUE TITLE
Auth munge bug?

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#330]
I am not sure if this is a bug or not, because the auth munge permissions are not documented.

When I use the meminfo plugin with the following settings:

```
config name=meminfo producer=opal160 instance=opal160/meminfo component_id=161 uid=0 gid=0 perm=0
```

I find that the root user can still see the meminfo metric listing and retrieve the metric data (using ldms_ls). That seems unexpected, because I have clearly listed the perms as no access to anyone.

Is it intended that the root uid and/or gid overrides all permissions? That should be documented if it is.

**Comment by baallan** [comment]
Either root should have access to everything (which i think it has to for transport to work) or perms of 0/0/0 means the sampler is never called because noone can see the result anyway. Maybe flag 0/0/0 as a configuration error?
