### ISSUE TITLE
All_example plugin issue

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#35]
I am getting the following error when starting my aggregator when using the all_example plugin:

ERROR     : store_csv:  metric id 3: no name at list index 3.
ERROR     : store_csv: reconfigure to resolve schema definition conflict for schema=all_example 
and instance=node31/all_example.

Here are the relevant lines of configuration:
sampler.conf
load name=all_example
config name=all_example producer=node31 instance=node31/all_example component_id=5200001 job_set=node31/jobinfo

agg.conf
strgp_add name=policy_all_example plugin=store_csv container=csv schema=all_example
strgp_prdcr_add name=policy_all_example regex=.*
strgp_start name=policy_all_example

What is causing this error? Additionally, when I store with csv it stores fine, however storing with sos causes the aggregator to fail with no reported errors after failing.

**Comment by baallan** [comment]
if this is a full install of ldms, run
ldms-static-test.sh all_example
to verify the sampler is fine.

The normal cause of this conflict message (in the absence of memory corrupting bugs) is that some node is configured with a different schema definition. For example if some node has job_set defined and some other node does not, the schemas will not match.

**Comment by bschwal** [comment]
Running that command leads to 
dlopen: /opt/ovis/lib64/ovis-ldms/libzap_sock.so: cannot open shared object file: No such file or directory
It is in fact a missing library. 

All of the nodes have the same sampler configuration besides the fact that the instance, producer, and component name is configured per node along with job set instance. 

This only affects all_example. If I take all_example out it does not have this error.

**Comment by baallan** [comment]
Do you get the same dlopen error if you run 
ldms-static-test.sh meminfo
?

**Comment by bschwal** [comment]
Yes I do.

**Comment by baallan** [comment]
does 
find /opt/ovis -name libzap_sock.so
turn it up?

**Comment by baallan** [comment]
Jim will probably want this issue moved to ogc gitlab.

**Comment by bschwal** [comment]
find /opt/ovis -name libzap_sock.so
/opt/ovis/lib64/ovis-lib/libzap_sock.so

Compiling with 4.2.1-rc1.
env |grep ZAP
ZAP_LIBPATH=/opt/ovis/lib64/ovis-lib.

**Comment by baallan** [comment]
What is the value of ovis_lib_plugins in
/opt/ovis/lib64/ovis-lib-configvars.sh
?

**Comment by bschwal** [comment]
ovis_lib_plugins=/opt/ovis/lib64/ovis-lib

**Comment by baallan** [comment]
I just checked and the 4.2.1-rc1 did not include patches from master that fix zap_libpath in ldms-static-test.sh. The next 4.2 release/rc does/will.
In the mean time, you can get ldms-static-test.sh to work (if you want) by editing the ZAP_LIBPATH= variable in it to point to the right place (ovis-lib instead of ovis-ldms).

**Comment by bschwal** [comment]
No errors in the logs after testing that.

**Comment by baallan** [comment]
what does ldms_ls -l -v (other required args per your host) of the aggregator daemon show for the complete list of all_example data sets?
an attachment (if possible) may be better than pasting in the comment box.

**Comment by bschwal** [comment]
[all_example.txt](https://github.com/ovis-hpc/ovis/files/3056174/all_example.txt)

**Comment by baallan** [comment]
I reproduced this symptom. valgrind found a null pointer usage in store_sos for all_example.

**Comment by baallan** [comment]
[store_sos.vg.txt](https://github.com/ovis-hpc/ovis/files/3056890/store_sos.vg.txt)

**Comment by baallan** [comment]
Patches for this have been pushed to gitlab upstream for master and v4.2.

**Comment by baallan** [comment]
Fixes for this have been merged upstream. Please reopen the issue if the problem recurs in the next github update.
