### ISSUE TITLE
help required to get data into csv file

### ISSUE THREAD

**Issue by kalasagar211** [ovis-hpc/ovis#36]
Here i am trying to store meminfo metrics to csv file

How to write sampler and aggregator for this Please help me 

Thanks 
kalasagar

**Comment by kalasagar211** [comment]
sampler.conf
 ======================================================
 load name=meminfo
 config name=meminfo producer=${HOSTNAME} instance=${HOSTNAME}/meminfo component_id=${COMPONENT_ID} schema=meminfo  job_set=${HOSTNAME}/jobinfo uid=0 gid=0 perm=0770
 start name=meminfo interval=${SAMPLE_INTERVAL} offset=${SAMPLE_OFFSET}
==========================================================
aggregator.conf
============================================================
prdcr_add name=vmtest2 host=vmtest2 port=10447 xprt=sock type=active interval=30000000
prdcr_start name=vmtest2

updtr_add name=updtr1 interval=10000000 offset=300000
updtr_prdcr_add name=updtr1 regex=.*
updtr_start name=updtr1

 load name=store_csv
 config name=store_csv path=/home/suparikshan/ action=init altheader=1 rollover=86400 rolltype=1 buffer=1

 strgp_add name=meminfo_store_csv plugin=store_csv container=metric_data schema=meminfo
 strgp_start name=meminfo_store_csv
 
===================================================================

It's working fine with csv 

i need to test with sos and mysql databse. Plase guide me 

Thanks in advance 
sagar

**Comment by valleydlr** [comment]
Hi Sagar,

We will put up an example for building a sos plugin and configuring a sos store on the wiki. There is no storage plugin for mysql. Our suggested method for mysql is to bulk load csv files.

**Comment by kalasagar211** [comment]
Thank you valleydlr. i am waiting for wiki page. 

I need another help. 

i want to generate my own plugin and metric set with some parameters not all . how to do it 

and also any GUI tool u have to use ldms ?

**Comment by kalasagar211** [comment]
another question i have @valleydlr 
but LDMS 3 vesrion have mysql support right?? 
i didnt understand this too 
**Our suggested method for mysql is to bulk load csv files.**

so no mysql use csv u r suggesting right. 

Please clarify me 

If SOS works also its fine for me 

Thank you 
sagar

**Comment by valleydlr** [comment]
Yes I am suggesting that you load csv files into mysql if that is the database you want to use. SOS does work but still need to put up the example. Will try to post yet this week.
