### ISSUE TITLE
lsdate flexibility

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#361]
lsdate should handle dates ('1'+9 dec digits) embedded anywhere in string, not just at end. this would handle compressed, etc files.
probably needs a rewrite in  perl/awk/python and a flag to enable new behavior

**Comment by tom95858** [comment]
@baallan where are we on this?

**Comment by baallan** [comment]
@tom95858 I still need to take a couple of days to do it; never gets to the top of the queue.
If its lingering is bothersome, i could move it to an snl tracker.
