### ISSUE TITLE
RHEL 7.1 Build Error

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#38]
I'm building with 4.2.1-rc1 and I am getting the following error on a rhel 7.1 system.

/usr/bin/ld: .libs/_ldms_la-ldms.o: relocation R_X86_64_PC32 against undefined symbol `ldms_rbuf_desc_array_metric_value_get' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value

Any help is appreciated. Thanks!

**Comment by baallan** [comment]
Check that the system libtool is up to date and that there is no accidental cross-compiling going on.

**Comment by baallan** [comment]
This turned out to be a rhel build vs epel deploy issue.
