### ISSUE TITLE
Exceeded max store keys

### ISSUE THREAD

**Issue by bschwal** [ovis-hpc/ovis#39]
On OVIS 4.2.1-rc1:

I am trying to create 22 csv store files on my L2 aggregator. 3 csv files have 0 bytes stored in them even though the values appear under ldms_ls -l on the L2 aggregator and the files are non-zero in my L1 agg store. My log file has the error: 

store_csv.c: Error: Exceeded max store keys

I see there is a default in that file of 20 keys. What is the correct way to increase this number? Is that the cause of my zero bytes files?
Any help resolving this is appreciated.

**Comment by baallan** [comment]
this is fixed in next rc already.

**Comment by bschwal** [comment]
Thank you!
