### ISSUE TITLE
For help:No data is written to the SOS database

### ISSUE THREAD

**Issue by MAChenliang** [ovis-hpc/ovis#399]
I refer to [LDMS Version 3 Tutorial]  (https://ovis.ca.sandia.gov/images/4/4d/LDMSV3Tutorial_SAND20175153.pdf ) to start useing store_sos plugin.It shows "running",but no data is written to the directory.I have no idea how to solve it.

System version: centos 7.7
OVIS version: OVIS-4.3.3
SOS version: sos-OVIS-4.3.1

  ldmsd_controller --hostname localhost --port 10001
  sock:localhost:10001> load name=store_sos
  sock:localhost:10001> config name=store_sos path=/data/sos
  sock:localhost:10001> strgp_add name=meminfo_sos plugin=store_sos container=meminfo schema=meminfo
  sock:localhost:10001> strgp_start name=meminfo_sos
  sock:localhost:10001> status
  Name         Type         Interval     Offset       Libpath
  ------------ ------------ ------------ ------------ ------------
  sos          store             1000000            0 /opt/ovis/lib/ovis-ldms/libstore_sos.so
  meminfo      sampler           1000000            0 /opt/ovis/lib/ovis-ldms/libmeminfo.so
  Name             Host             Port         Transport    State
  ---------------- ---------------- ------------ ------------ ------------
  Name             Interval     Offset       Mode            State
  ---------------- ------------ ------------ --------------- ------------
  Name             Container        Schema           Plugin           State
  ---------------- ---------------- ---------------- ---------------- ------------
  meminfo_sos      meminfo          meminfo          store_sos        RUNNING
      producers: 
      metrics: 

ll /data/sos/
total 0

**Comment by tom95858** [comment]
It's not clear from the above that you ever created a producer to point at the sampler deamon(s), or ever created updaters to gather data from the samplers daemons. The store saves data that has been collected by an "updtr."

**Comment by MAChenliang** [comment]
Thx.SOS plugin is working successfully now.
I did not creat updaters before.
