### ISSUE TITLE
Missing autoconf checks in v4

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#40]
It looks like there are some missing autoconf checks in v4.  The configure script ran without error, but when trying to compile on a v4 development branch I get:

```
make[5]: Entering directory `/g/g0/morrone/src/ovis/ldms/src/ldmsd'
  CC       ldmsd_stream.lo
  CC       ldmsd_request_util.lo
  CCLD     libldmsd_stream.la
  CCLD     librequest.la
  CC       ldmsd_plugattr.lo
  CCLD     libplugattr.la
  CC       ldmsd-ldmsd.o
  CC       ldmsd-ldmsd_config.o
  CC       ldmsd-ldmsd_request.o
  CC       ldmsd-ldmsd_cfgobj.o
  CC       ldmsd-ldmsd_prdcr.o
  CC       ldmsd-ldmsd_updtr.o
  CC       ldmsd-ldmsd_strgp.o
  CC       ldmsd-ldmsd_smplr.o
  CC       ldmsd-ldmsd_failover.o
  CC       ldmsd-ldmsd_group.o
  CCLD     ldmsd
/bin/ld: cannot find -ljson_util
/bin/ld: cannot find -lev
```

**Comment by baallan** [comment]
can you post the config.log and config.status from your failed build?
and what platform (os, compiler) is this on?

**Comment by morrone** [comment]
It looks like this is due to new code on @tom95858's development branch that he shared with me.  I can almost certainly cherry pick the things I need onto OVIS-4.2.1-rc1 and avoid the other build problems that were introduced.

I am building on a TOSS server (basically RHEL7.6).

Under this version of RHEL, it looks to me like there is a json/json-util.h header supplied by the json-c-devel package, but only libjson and libjson-c libraries are included, nothing called libjson_util.

So, maybe this is just a note for @tom95858 before those things are merged into the main branch.

**Comment by ovis-hpc** [comment]
This topic is about a private internal branch which is in development and not the release code. Such conversations should be between the involved developers.
