### ISSUE TITLE
Need proper cython autoconf test(s)

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#404]
It looks like OVIS-4 has now lost the "--disable-python" option, and also requires cython. However there does not appear to be a proper autoconf test (or tests) for cython. We will need that before the next V4 release.

Additionally, the tests need to detect the proper cython. For instance, the EPEL python36-Cython package installs the cython binary as "cython3.6". LDMS will need to properly detect and use the cython that matches the detected python.

**Comment by tom95858** [comment]
Good catch @morrone we'll make that a priority.

**Comment by narategithub** [comment]
@morrone we have `--disable-ldms-python` to disable python-dependent module. Could you please point me to the point when we have `--disable-python`? I could not find it from `configure.ac` or `ldms/configure.ac` git log history.

@tom95858 please let me know if we should rename `--disable-ldms-python` to just `--disable-python`.

**Comment by morrone** [comment]
@narategithub , I don't know, maybe that was something stray in my spec file from very old stuff. I wouldn't worry about that. We should probably focus on getting proper cython checks.

**Comment by morrone** [comment]
By the way, is anything from cython needed at run time, or is it just at build time that it is used? Just wondering if a BuildRequires is sufficient in my spec file, or if a Requires is also in order.

**Comment by narategithub** [comment]
cython is needed only at build time.

About the python option name, I think `--disable-ldms-python` should be just `--disable-python`, but I'll wait for a confirmation from @tom95858 .

**Comment by morrone** [comment]
--disable-ldms-python does appear to work. --disable-python seems like a better name, but there might be an argument to be made that it shouldn't change in a minor release. Or if we do change it there should be a backwards compatible --disable-ldms-python that works, and sets --disable-python, while also printing a warning that --disable-ldms-python is deprecated.  The deprecated option could be removed entirely in, say, 5.X.

(The cython checks are still required for v4)

**Comment by baallan** [comment]
btw --disable-ldms-python stems from the time when ovis/ had submodules (e.g. sos) with their own python bindings enabled separately. now submodules have been eschewed, it could become enable-python i expect. (other than annoying packagers, no great loss).

**Comment by tom95858** [comment]
@narategithub , please rename disable-ldms-python to just --disable-python. I believe it should be enabled by default.

**Comment by baallan** [comment]
@tom95858 enabling python is fine by default so long as it works with a rhel 7 (non-epel) python3 and does not depend on an epel cython. If requiring an unusual-source cython, python should be disabled by default.

**Comment by tom95858** [comment]
@baallan, @morrone I understand the requirement to only have run-time dependencies on distribution RPM. However, this is a *build* dependency, not a run-time dependency. I can also understand the preference to have build dependencies on distribution RPM. However, the distribution RPM for Cython a) does not properly support Python3, and b) the Python community in general recommends that we use *pip*, not the distribution RPM.

The proposed requirement for non-epel packages only as a build dependency does not seem well reasoned to me. We should, however, have better documentation for what our build dependencies are and how to acquire them. I have previously suggested that we have readily available "build containers" for the supported distros. This think this would ameliorate most or all of these concerns for the supported distros.

Python2 is no longer supported. Numpy, SciPy, Pandas, etc...all have build dependencies on Cython and I see no reason why we cant as well. If for whatever reason you cannot or will not use the pip version of Cython, then you will have to disable Python support.

**Comment by morrone** [comment]
I would like to clarify that I was not in the camp that argued against having a dependency on packages in EPEL. EPEL dependencies are generally an easy ask for adding to TOSS.

I'll mull it over some more, but I am currently of the desire that ldms support the lowest common denominator version of cython from EPEL (for RHEL7, that looks like 0.28.5). It is not necessarily the end of the world to insert a pip install command in every build process, but when a well packaged and easily accessible solution is available from EPEL, that is likely to be the preference from LLNL.

You can make containers as you like, but I would strongly discourage you from assuming that your external packagers can or will use those containers. Some of us have build farms designed to build packages rpm for entire operating systems. Your container model won't work well with that. You container model is more of the "ldms is the center of the world and can be built in isolation to anything else" kind of thinking. For us, it is just one of many, many pieces of software that we build. My efforts over the past year have largely been aimed at bringing ldms in line with standard practices in the Linux world so that LDMS doesn't stand out as the thing that is always a pain to build, configure, and use. I think LDMS has made really good progress on that front, and I'm hoping we'll stay the new course!

In other words, requiring your supplied containers in order to build and package ldms would make things much harder for us, not easier.

I have no problem with moving from python2 to python3. One might argue that is the sort of change that requires a major version change, but I don't really care. We just need to advertise the change well so that people know what they are getting into with 4.3.4.

So I think you, Tom, and I only disagree on one thing here: pip. I know that the python community prefers pip for everything, but most python developers tend to live in a different sort of world than system level software developers. pip tends to be problematic for system level software, and I certainly count ldms as system level software.

Again, I'm not closing the door on this one pip use case entirely in the future, but I would like to avoid it in the present when an easy alternative (the EPEL rpms) is available.

**Comment by baallan** [comment]
@morrone I nominate you to open an item in the appropriate TOSS3 internal tracker to get py36/scipy/pandas and cython 0.28.5 included in TOSS3 from either the most recent rhel7 software collection or epel.

**Comment by morrone** [comment]
@baallan, I think you are mixing issues. scipy and pandas are not required by this part of the ldms build as far as I can see. Those are a topic for another issue. Lets stick with cython in this ticket.

Python 3.6 is already in RHEL7/TOSS3. Python 3.8 is already in RHEL8/pre-TOSS4. I already have a ticket open to include the EPEL package python36-cython in TOSS3 and python38-cython in pre-TOSS4.

**Comment by baallan** [comment]
@morrone right, re scipy & pandas. please pardon my enthusiasm. We need pandas only if packaging full sosdb tools, not the ldms sos plugin(s).

**Comment by baallan** [comment]
re pip: pypi.org (default origin of pip results) is registered in France, and therefore has no security standards relationship with US institutions. Moreover, it has been numerous times the host of malware and has no obviously stated measures in place to prevent it from being used as a cyber attack vector. 
We must have some vendor-certified, security patched source of anything we run as system services. My understanding is that neither pypi nor epel actually qualifies in this regard. That leaves (for redhat7) the software collections being an a source of cython tooling.

**Comment by tom95858** [comment]
Just so I understand @baallan, no one at the labs uses Numpy, Pandas, or SciPi, ... etc...? My understanding is that these are built with Cython as well.

@narategithub could you please check what the minimum version of Cython is required?

**Comment by baallan** [comment]
Users apply many different versions of python3/cython/etc. They do it without privilege. In some cases they build their own from source. In many they use a locally supported (nonrhel, nontoss) anaconda3 installation. None of this works for admin tools on our systems.

**Comment by nick-enoent** [comment]
@tom95858 Cython version 0.20 runs in all Python versions from 2.4 to 3.4 (excluding 3.0). From Cython 0.21 supported versions become 2.6, 2.7, 3.2 and later. Cython 3.0 removes support for Python 2.6 and requires either Python 2.7 or Python 3.4+.

**Comment by morrone** [comment]
Patches have landed to address the original issue described in this ticket. I am going to close this ticket. Feel free to open new tickets to continue discussion of related topics!
