### ISSUE TITLE
high rate kernel events feature

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#407]
A kernel high rate software events (perfmon for software counters instead of MSR/papi hw counters) sampler is very desirable.
This is complementary to a streaming software events sampler.

The papi 6 api has some features for software events.
The syspapi sampler seems to be only for MSR-ish events (which is fine btw).
Seems like perfmon has a ton of capability beyond msrs.
Can we have a bit of discussion about what the right approach is to getting this software event information into ldms and the right approach to making such data easily specified for collection?

**Comment by tom95858** [comment]
@baallan, the syspapi sampler might be a place to start. It uses the perfmon API, and libpapi to convert the event names into masks used by perfmon. It is reasonable to extend this sampler to allow it to gather other events as well.
