### ISSUE TITLE
lustre2_client sampler not collecting metric data other than component_id, job_id and app_id

### ISSUE THREAD

**Issue by wooloo1121** [ovis-hpc/ovis#434]
Hello,

We are using LDMS on our hpc cluster, and notice the lustre2_client sampler is not returning metric data other than component_id, job_id and app_id. Namely, with command "ldms_ls -h localhost -p port -l host/lustre2_client", we get only the following:
M u64        component_id                       1
D u64        job_id                                     0
D u64        app_id                                    0

In /opt/ovis/config/ldmsd.conf, we have the following setting:
load name=lustre2_client
config name=lustre2_client producer=cas001 component_id=1 instance=cas001/lustre2_client llites=* oscs=* mdcs=*
start name=lustre2_client interval=1000000

And I checked /var/log/ldmsd.log, there seems no related error message.

Is there anything we did wrong or missed that makes the metric data not been collected? And what do the job_id and app_id here mean? 

Thank you very much and look forward to your reply.

**Comment by tom95858** [comment]
Hi @wooloo1121, What version of lustre are you running?

**Comment by wooloo1121** [comment]
@tom95858 It's lustre 2.12.

**Comment by morrone** [comment]
@wooloo1121 , the job_id, app_id, and component ID  are all present in most of the metric sets whether or not the user has actually configured those fields to be used. job_id and app_id are for recording what job and "application" were running on the node at the time of the sample. For SLURM, job_id maps to a SLURM job ID, and app_id maps to a SLURM job step (to the best of my understanding. But if you haven't explicitly set up job id reporting, the fields will always be zero.

**Comment by wooloo1121** [comment]
Hi @morrone, thank you very much for answering. When you say "explicitly set up job id reporting", do you mean the setting in /opt/ovis/config/ldmsd.conf file?

**Comment by morrone** [comment]
@wooloo1121, yes, a jobid plugin needs to be configured, and then other steps need to be taken to have the job id information sent to that plugin. One mechanism is using a supplied slurm spank plugin to send job information through ldms streams to the ldmsd, which the jobid plugin watches and uses to update the job metric set. I haven't run through the details myself yet, but I am hoping to work on that here soon.

**Comment by baallan** [comment]
@wooloo1121 what version of LDMS are you using? The symptom you report is possibly consistent with ldms being an older version 3 or early version 4. Older versions of ldms lustre2_client plugin were not entirely compatible with lustre >= 2.10.

**Comment by wooloo1121** [comment]
Hi @baallan, thank you for the reply. It's 4.3.3, which is the version that starts to be compatible with lustre 2.12?

**Comment by baallan** [comment]
4.3.4 (Which is still in beta I think), the tip of the OVIS-4 branch on github has been tested with lustre 2.12.

Also, be aware that if your lustre file system is very large (in terms of server nodes for mds, oss) the lustre data set may become very large. I typically collect only the llite data with lustre2_client and the lnet_stats data.

**Comment by wooloo1121** [comment]
@baallan We installed 4.3.4 ldms client (keep the server side 4.3.3 for now), but lustre2_client still not working.

**Comment by tom95858** [comment]
Hi @wooloo1121, if by 'server side' you mean the sampler runnning on the compute, then that is the side that is running the lustre2_client sampler and therefore it will still be running the "old" code that doesn't have the support for the newer lustre stats file location. In other words, updating the "aggregator" alone won't resolve the issue.

**Comment by wooloo1121** [comment]
Hi @tom95858, sorry for not being clear. By "client", I mean the sampler running on the compute node. 

Is there anything we need to do with the lustre file system to possibly "make it work with ldms"? Or is there any configuration specific to the lustre sampler we possibly missed?

**Comment by wooloo1121** [comment]
Hi @baallan @tom95858 @morrone , thank you very much for your help and patience. We just tried with the tip of the OVIS-4 branch and modified the sampler configuration file to only collect llite data, then lustre2_client worked!

**Comment by baallan** [comment]
@wooloo1121 The latest  lustre sampler should also work for other items than llite. If it does not work for you when properly configured, we need to fix it. All three (llite, osc, mdc) worked in our local testing.

But, there are often many more osc/mdc targets to monitor than llite items, so the ldmsd sampler daemons and aggregators may need to be configured with much more memory for these lustre data sets. For example "ldmsd -m 2G ..." will usually provide more than enough for a sampler of all the available lustre data. 

If you have the time, please let us know if you can (or cannot) also collect the osc and mdc data.

**Comment by wooloo1121** [comment]
@baallan Yes with "-m 2G" I could collect all the llite, osc and mdc data :)

**Comment by baallan** [comment]
Thanks for confirming osc and mdc collection work on your platform.
