### ISSUE TITLE
ldms plugins should not be required to honor an "instance" configuration option

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#45]
Currently, it is required that all ldms plugins implement an "instance" configuration option.  Unfortunately, this option just does not make sense for all plugins, and this requirement should likely be amended.

First of all, some plugins generate multiple metric sets from one or more schemas.  How is this single instance name supposed to be applied to multiple metric sets which are required to have different instance names?

The current approach by some of those plugins to accept the instance plugin option, and then completely ignore it.  This is probably not a great approach, but it demonstrates that the instance option's design is not general enough to be a required configuration in all plugins.

**Comment by baallan** [comment]
opa2, dvs, and IB fabric samplers also want to create a set instance per device rather than per plugin.

**Comment by baallan** [comment]
An improvement on 'instance' would be to provide api for plugin writers that lets the user specify
instance=${pattern1} schema=${pattern2} 
where patterns are substituted following some conventions.

This would let the user override hardwired schema naming which sooner or later always leads to a conflict of schema types.
Our current instance naming habits could be expressible as:
schema=something instance=%H/%S
where replacements are:
%H short host name
%S schema name
etc

And an advanced case commonly seen now would be:
schema=procstat_%V{maxcpu} instance=%H/%S maxcpu=${NCORE}
where
%V{maxcpu} is replaced with the environment expanded string value of the maxcpu parameter, which on my systems would be 16 or 72 or 36

**Comment by baallan** [comment]
The addition of lists and record types to set schema has made it possible to handle multiple (time varying count) devices in a single schema and single instance; reducing the need for this feature.
