### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by MAChenliang** [ovis-hpc/ovis#452]
I met a problem when I try to install ovis-ldms-4.3.4-alpha.1.
I used the version 4.3.3 before.It worked fine.

System version: centos 7.7

`yum install libtool python python-devel libyaml libyaml-devel curl-devel openssl-devel swig tkinter numpy glibc`
`pip install cython`
`./autogen.sh`
`mkdir build`
`cd build`
`../configure --prefix=/opt/ovis --enable-sos --with-sos=/opt/SOS --enable-swig --enable-readline`
`make`

...
...
/usr/bin/ld: hello_publisher.o: undefined reference to symbol 'sem_timedwait@@GLIBC_2.2.5'
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[6]: *** [hello_publisher] Error 1
...
...

**Comment by baallan** [comment]
have you tried this with the most recent OVIS-4 head or beta-1 release?

**Comment by tom95858** [comment]
Hi @MAChenliang , can you please close this if it is no longer an issue?
