### ISSUE TITLE
papi packaging for system daemon use

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#454]
LDMS syspapi sampler needs a consistent in all toss versions libpapi.

**Comment by baallan** [comment]
@morrone 
Given that libpapi is also a research topic for many and that system daemons cannot depend on lmod or the like, I hit on the following for packaging on toss-derived stria. It would make a good approach for toss, if toss3 does not package papi-6.0.x to /usr/lib64.

my papi source is obtained from:

```
#!/bin/bash
papiver=papi-6.0.0
papitar=${papiver}.tar.gz
curl -L -O http://icl.utk.edu/projects/papi/downloads/$papitar
```

My ATSE spec file looks something like below. It might want a little tune-up of configure options to support the NVIDIA hardware that CTS1/CTS2 provide. The main idea is that $ovis_pkglibdir/papi-$papiversion can be assumed by ldmsd.

```
%define ldms_all System Environment/Libraries
%define build_timestamp %(date +"%Y%m%d_%H%M")
# % global __strip /bin/true
%global _enable_debug_package 0
%global _enable_debug_packages 0
%global debug_package %{nil}
%global __debug_install_post /bin/true
%global __os_install_post /usr/lib/rpm/brp-compress %{nil}
%if 0%{?rhel} && 0%{?rhel} <= 6
%{!?__python2: %global __python2 /usr/bin/python2}
%{!?python2_sitelib: %global python2_sitelib %(%{__python2} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")}
%{!?python2_sitearch: %global python2_sitearch %(%{__python2} -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))")}
%endif

%define papiversion 6.0.0

# Main package
Summary: OVIS Commands and Libraries
Name: ovis-papi
Version: %{papiversion}
Release: 1.0%{?dist}
License: GPLv2 or BSD
Group: %{ldms_all}
URL: http://icl.utk.edu/projects/papi/downloads/papi-6.0.0.tar.gz
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Source: http://icl.utk.edu/projects/papi/downloads/papi-6.0.0.tar.gz
Requires: rpm >= 4.8.0

%description
This package provides the papi interface for LDMS

%prep
%setup -q -n papi-%{papiversion}

%build
echo bTMPPATH %{_tmppath}
rm -rf $RPM_BUILD_ROOT
echo bBUILDROOT $RPM_BUILD_ROOT
export CFLAGS="%{optflags} -O1 -g"
cd src
%configure \
--bindir=/usr/lib64/ovis-ldms/papi-%{papiversion}/bin \
--libdir=/usr/lib64/ovis-ldms/papi-%{papiversion}/lib \
--includedir=/usr/lib64/ovis-ldms/papi-%{papiversion}/include \
--mandir=/usr/lib64/ovis-ldms/papi-%{papiversion}/share/man \
--datadir=/usr/lib64/ovis-ldms/papi-%{papiversion}/share \
--datarootdir=/usr/lib64/ovis-ldms/papi-%{papiversion}/share \
--prefix=/usr/lib64/ovis-ldms/papi-%{papiversion}
make %{?_smp_mflags}

%install
echo TMPPATH %{_tmppath}
echo BUILDROOT $RPM_BUILD_ROOT
cd src
make DESTDIR=${RPM_BUILD_ROOT} V=1 install
# remove unpackaged files from the buildroot
rm -f $RPM_BUILD_ROOT%{_libdir}/ovis-ldms/papi-%{papiversion}/*.la

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root)
%{_libdir}/ovis-ldms/papi-%{papiversion}/lib/*
%{_libdir}/ovis-ldms/papi-%{papiversion}/share/papi/papi_events.csv
%exclude %{_libdir}/ovis-ldms/papi-%{papiversion}/lib/pkgconfig
%exclude %{_libdir}/ovis-ldms/papi-%{papiversion}/lib/pkgconfig/*
#end core

# util
%package util
Summary: LDMS PAPI util package
Group: %{ldms_grp}
Requires: ovis-papi = %{papiversion}
%description util
This is a development package of Lightweight Distributed Metric System (LDMS).
Users who want to implement their own sampler or store must install this
package.

%files util
%defattr(-,root,root)
%{_libdir}/ovis-ldms/papi-%{papiversion}/bin/*
#end util

# devel
%package devel
Summary: LDMS PAPI devel package
Group: %{ldms_grp}
Requires: ovis-papi = %{papiversion}
%description devel
This is a development package of Lightweight Distributed Metric System (LDMS).
Users who want to implement their own sampler or store must install this
package.

%files devel
%defattr(-,root,root)
%{_libdir}/ovis-ldms/papi-%{papiversion}/include/*.h
%{_libdir}/ovis-ldms/papi-%{papiversion}/include/*/*.h
%{_libdir}/ovis-ldms/papi-%{papiversion}/lib/pkgconfig/*
#end devel

%package doc
Summary: Documentation files for %{name}
Group: %{ldms_all}
%description doc
Doxygen files for ovis package.
%files doc
%defattr(-,root,root)
%{_libdir}/ovis-ldms/papi-%{papiversion}/share/man/*/*

%changelog
* Mon Mar 9 2020 Ben Allan <baallan@sandia.gov> 4.3
Create 4.3 papi software collection element.
```

**Comment by morrone** [comment]
I really don't understand this approach. I am not a fan of having a whole usr/lib/include/man/etc directory tree for papi under a hard-coded ovis-lmds library path. Nor am I a fan of making it sound like papi is a part of ldms in the packaging when it is really a standa-alone package, regardless of where it is installed.

Also, if we repackage papi, lets start with the upstream spec file. We only need the base and -devel pacakges. I don't think we want util and doc packages. It definitely isn't normal to put the man pages in a separate doc subpackage.

Maybe we should take a step back and discuss the basics:

What is the minimum version of papi that ldms require?

I didn't spot any version checks in LDMS's configure system. Did I miss something? That might be something we need to fix in LDMS.

I just tried enabling all of the configure options that had "papi" in the name, and LDMS built fine with the TOSS-supplied PAPI 5.2.0.

What is going on there?

But lets say we _want_ a newer PAPI than is installed. What are the papi compatibitliy concerns? Why don't we just update the TOSS papi 5.2.0 to something newer? Are there concerns that the newer papi are not backwards compatible?

**Comment by baallan** [comment]
We need papi latest stable (6.0.0.1 as of May 2020). 

There is no binary compatibility between papi minor versions (in uint32 Maj.Min.Rev.Inc, Maj.Min must match exactly). The fact that something compiles doesn't mean it is useful or that plugin configuration files written for modern papi will be understood by a 5.2 library.

5.2 is much too old to deal with hardware architectures we care about; 5.5 was released in 2016.

* It would be ideal if /usr/lib64/libpapi in toss was 6.0.x.x in TOSS releases and not an ldms problem. Issue TOSS-4857 on cz has some of the additional concerns that lead to this proposal; I don't know how to crack the nut of 5.2 in use by other packages except this way.  
* It would be ideal if ovis had a papi version check in configure, but it doesn't as you point out.
* We do want to be able to access the extra papi utilities for identifying things about the current hardware. Making those optional or part of the base toss rpm is a matter of taste. I went with optional for ATSE based on local input; happy to have fat and fewer rpms in toss.

**Comment by morrone** [comment]
OK, it sounds like it is less of a code requirement than it is a requirement for a set of features that is offered in the newer papi.

So here are some of the things I think we would want to see in the papi 6 package to allow it to be included in TOSS:

* Base package name is "papi6" (or perhaps "papi6.0" or "papi6.0.0" depending on how likely we need different sub versions installed at the same time)
* Package structure matches existing papi rpm package structure, don't invent our own
* No references to LDMS introduced in the papi package

The big question is how to support simultaneous install with other papi versions. The quick and easy approach is to do something like this:

```%configure --prefix=/usr/local/%{name}```

The main thing we would need to work out is if "/usr/local" is the best base path. Maybe "/opt" would be better. Or something else that isn't coming to mind yet.

The harder approach would be to try appending the version string matches the one from %{name} to each and every file and directory that would conflict with other installed papi packages. That is basically the approach that python and similar packages take. Of course, those packages expect that. This might be harder to accomplish if the package has baked-in assumptions about paths or file names.

**Comment by baallan** [comment]
A better solution would be if toss packages depending on ancient papi just migrated to the new one.
Locally we have a preference for (if it's new location) /usr/local over /opt since /opt may not mount at the same time as usr.
prefix=/usr/local/lib/papi60/ would solve all file naming issues and support simple configure in ldms of --with-libpapi=/usr/local/lib/papi60.

**Comment by morrone** [comment]
Sure, but if that is what you want to pursue that then you'll need to make a normal papi package for 6, not the approach you proposed in this ticket.

**Comment by baallan** [comment]
if toss starts shipping /usr/papi/6.0 in the toss3 base, this ticket is unnecessary.

**Comment by morrone** [comment]
> if toss starts shipping /usr/papi/6.0 in the toss3 base, this ticket is unnecessary.

Is that package something you plan to work on?

**Comment by baallan** [comment]
I don't have a _plan_ to work on it. I could propose a spec file based on a prefix=/usr/papi/6.0 and the feedback to the atse spec file @morrone provided, but I do not have direct access to the toss spec files repo or build bot.

**Comment by morrone** [comment]
I think that the spec file that papi itself provides seems pretty reasonable (with some minor tweaks to make it actually work...).

**Comment by tom95858** [comment]
@baallan What is the symptom you are experiencing? I am running the PAPI sampler successfully on RHEL 7, 8, Suse, and Cray.

**Comment by baallan** [comment]
There's no 'symptom' per se. It's just that papi 5.2 is very old wrt hardware architectures and metrics it understands correctly. CTS1, CTS2, and nvidia are all newer. We pretty much always use papi 5.x where x=latest or papi 6.0, depending on how recently the particular profiling effort was started.

**Comment by morrone** [comment]
It should probably be noted that the RHEL papi 5.2.0 package is not just 5.2.0 code. It also has 24 patches, some of which are backporting additional hardware support. Have we verified that things we need are missing in the rhel package, or are we just assuming from the version number?

**Comment by baallan** [comment]
Omar has told us that 5.2 is insufficient for real work on modern platforms.

**Comment by morrone** [comment]
I'm not sure who that is, and that answer didn't seem to differentiate between upstream 5.2 and rhel's 5.2.

**Comment by tom95858** [comment]
Can we get Omar to confirm that if we simply install the preferred version of PAPI, that our samplers will use that version? I'm not talking about build time, I'm talking about run-time. Modulo an API change, I don't see why that would not be the case. Pulling PAPI into our source feels like a maintenance nightmare.

**Comment by morrone** [comment]
@tom95858, what exactly is your concern about run time library use? Papi does version its library, so if we point the ovis build to the correct version at build time it should use the correct one at run time (although this does remind me that I may need to add an ld.conf.d file for this papi library location).

But I do not know much about papi. Are there things outside of libpapi.so that you are worried about?

And just to be clear, I am assuming that papi 6 will be built as a normal external package, not the way described at the beginning of this ticket.

**Comment by baallan** [comment]
If we drop --disable-rpath from the toss builds, there's no need to worry about any ldms-specific ld.so.conf settings. Don't know if TOSS maintainers are ok with this yet.

@tom95858 no one proposed making papi part of our sources; I did propose making a specific packaging of papi embedded in the ldms layout so there would be no other TOSS package conflicts. With some chiming in from Chris, a TOSS internal discussion seems to indicate we can include a /usr/papi/6.0 in toss. There's no utility in putting an older version of papi in TOSS.

@morrone The papi 5.2 papi moderately patched by redhat is way behind the capabilities of papi 6.0 (see release notes at https://bitbucket.org/icl/papi/wiki/PAPI-Releases) that we want to include in upcoming versions of the papi sampler plugins. Omar Aaziz, the snl ldms resident papi expert and part of the ECP project,  always uses at least papi 5.6 or 5.7 because the redhat version is insufficient.

**Comment by tom95858** [comment]
Hi @morrone, I don't have a worry, but I didn't want to state unequivocally that it would "just work" without testing it myself. I'm simply asking Omar to do so because I believe it should.

**Comment by morrone** [comment]
> If we drop --disable-rpath from the toss builds, there's no need to worry about any ldms-specific ld.so.conf settings. Don't know if TOSS maintainers are ok with this yet.

I built papi 6.0.0.1 for toss 3 and 4. The packages install under /usr/papi600 as discussed in the TOSS jira.

But it looks to me like dropping --disable-rpath did not result in correct linking to papi. Configure worked (--with-libpapi=/usr/papi600 --with-libpfm=/usr/papi600 ), and the module all built, but I see:

```
$ ldd libpapi_sampler.so.0 |grep papi
        libpapi.so.6.0 => not found
```

and

```
$ objdump -x libpapi_sampler.so |grep RPATH
  RPATH                /usr/lib64
```

I see the same for libsyspapi_sampler.so and libhweventpapi.so.

And meanwhile, they seem to be using the wrong libpfm:

```
$ ldd libsyspapi_sampler.so |grep pfm
        libpfm.so.4 => /usr/lib64/libpfm.so.4 (0x00002aaaab707000)

```

**Comment by baallan** [comment]
yes. makefile.am
libsyspapi_sampler_la_LIBADD = $(COMMON_LIBADD) -lpapi -lpfm -lpthread
is ignoring the library path that should be captured in configure if the user specifies other than /usr as the location of the papi and pfm libraries.

**Comment by morrone** [comment]
I'm not sure that it is quite that simple. The "-Wl,-rpath" is being set in AM_LDFLAGS, but it is not working. First, I think we may be using the wrong rpath option. According to the libtool manual:

```
-rpath libdir
If output-file is a library, it will eventually be installed in libdir. If output-file is a program, add libdir to the run-time path of the program. On platforms that don’t support hardcoding library paths into executables and only search PATH for shared libraries, such as when output-file is a Windows (or other PE platform) DLL, the .la control file will be installed in libdir, but see -bindir above for the eventual destination of the .dll or other library file itself.

-R libdir
If output-file is a program, add libdir to its run-time path. If output-file is a library, add -Rlibdir to its dependency_libs, so that, whenever the library is linked into a program, libdir will be added to its run-time path.
```

So it sounds to me like for libraries we are making, we need to use "-R libdir". It tried that, and it did result in the rpath being added. Next we need to either figure out how to make that rpath the _first_ path that is checked (it was the last one when I just added it to LDFLAGS). If it is last, then the papi from the main ld search path will be used rather than the one in the rpath.

Alternatively, we might require a specific version of the papi library (the one found in the path specified with --with-libpapi). That would avoid using a younger or newer version of the library found elsewhere in the path. And if the exact version is found elsewhere in the path, then hopefully we don't care if it is used.

**Comment by baallan** [comment]
We may also need to change the libtool link flag flavor used depending on whether or not --disable-rpath is in use. When present, the assumption is that something elsewhere in deployment will make sure LD_LIBRARY_PATH is precisely what it needs to be.

**Comment by morrone** [comment]
I'm not using --disable-rpath. It is not clear to me what you mean though.

**Comment by morrone** [comment]
Alright I think I've got it figured out, more or less.

I am thinking of applying the same style of cleanup to the papi situation that I did to the slurm configuration options.

Do we need libpfm to be a separate --with option? It seems to come with papi now. Do we ever really expect it to be in a different library path that papi?

**Comment by baallan** [comment]
For toss, i expect they will always be paired in /usr/papi*. In general (e.g. ubuntu), libpfm is a product independent of the papi authors and we should probably have the option to override the 'co-located w/papi' available for cases where it isn't. 

re esthetic nits, consider including the dots in /usr/papi-6.0 ; The runtime compatibility check is going to match against exact X.Y of the X.Y.Z.R in the papi versioning.

**Comment by morrone** [comment]
I created PR #482 that fixes the configuration system issues and allows building against libpapi and libpfm in non-standard install paths.

**Comment by baallan** [comment]
It appears toss 3.7-4 resolves this issue with the placement of papi600 and papi600-devel packages.
