### ISSUE TITLE
Include "make dist-check" to PR build checks

### ISSUE THREAD

**Issue by Snell1224** [ovis-hpc/ovis#455]
@morrone Per the #449 PR fix, would it be possible to implement the "make dist-check" step to this repository's github container that builds and checks the OVIS code for each PR? 

I don't know if this step is already included in the container but if it is not, I think adding "make dist-check" would help immensely for future automation testing (i.e. Jenkins) since we won't need to worry about errors with the standard install tests/checks on the code.

Also, we'll be able to make the necessary changes in the PR before committing them instead of potentially needing to go back and fix them later on.

**Comment by morrone** [comment]
The first thing to understand is that none of the build commands live "in the container", as currently implemented. The docker hub container that I created (morrone/centos7-ldms-build:latest) is just a base centos7 environment with a fairly minimal set of additional packages needed to build ldms (but not necessarily all of the optional components).

Right now there is only one github workflow set up to use that container, but there could certainly be more. Additionally that one workflow could be expanded to have more jobs.

If you don't need more packages added to the container, you can simply edit workflows (or add new ones) right in the ovis git repo. See the .github/workflows directory in your checked out copy of the repo.

So the commands live in the workflow files, and can optionally be directed to run in various containers.

A commit to pr #449 that adds a job to do "make distcheck". See 2ed7c36df5.

**Comment by Snell1224** [comment]
Ah, okay that makes much more sense now. 

Just to clarify, if additional workflows were created and pointed to the centos7 container, will these workflows will be added as an additional "check" for each PR automatically? 

Also, does the centos7 container reside within the ovis git repo or a users personal repo? Just trying to understand how additional containers can be added and used as part of the build checks for the PRs.

Thank you for adding the "make distcheck" job and explaining how the commands work. I'll go ahead and close the issue in a bit.

**Comment by morrone** [comment]
No problem, I'm happy to share the info and have more people engaging!

Github workflows have an "on" section that describes the triggers that should launch the jobs listed in the workflow. In build-test-centos7.yaml, I have this section:

```
on:
  push:
    branches: [ OVIS-4 ]
  pull_request:
    branches: [ OVIS-4 ]
```

This means that the jobs will be run any time there is a push to the OVIS-4 branch, and any time there is a pull request initiated against the OVIS-4 branch.

The create-release.yaml workflow has this:

```
on:
  push:
    tags:
      - 'OVIS-4*'
```

It triggers any time a tag is created in the repo that begins with "OVIS-4".

So the workflow's triggers decide when the jobs in the workflow get launched. Going back to the build-test-centos7.yaml example, you'll see the jobs currently looks like this:

```
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: morrone/centos7-ldms-build:latest
    steps:
    - uses: actions/checkout@v2
    - run: sh autogen.sh
    - run: ./configure
    - run: make
```

The "runs-on" line chooses on which Virtual Machine, provided by GitHub, the job will run. The only Linux VMs offered by GitHub are Ubuntu.

Next the "container" tells it to use  container image "morrone/centos7-ldms-build:latest" from Docker Hub. All the "steps" will be run in the specified container that is itself running on the specified VM.

The docker containers are hosted on Docker Hub. They are not part of the github ovis repo. There is only one container so far: the one that I created under my personal Docker Hub account. There could be more in the future. The ovis central developers might make an ovis docker hub account at some point, if we figure out a method to work on that together.

If you need packages add to my container, just let me know. I can probably make other containers too if needed.

**Comment by Snell1224** [comment]
Great, this has been very helpful! I'll definitely be referring to this later on and will let you know if I need any additional packages added to the container.
Thanks!
