### ISSUE TITLE
autogen: subdir-objects

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#457]
Building on a changed system with the latest OVIS-4 branch.

new thing (to me) in autogen.sh (see below). What am I supposed to do??

Thanks
========================
ldms/src/sampler/hello_stream/Makefile.am:15: warning: source file '../sampler_base.c' is in a subdirectory,
ldms/src/sampler/hello_stream/Makefile.am:15: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
autoreconf: Leaving directory `.'

**Comment by morrone** [comment]
The other samplers appear to link against the sampler_base library one way or another rather than making sampler_base.c a source file. That would probably fix the warning.

Longer term it looks like the sampler_base library will be replaced with more built-in ldms APIs.

**Comment by oceandlr** [comment]
Are you advising against doing subdir-objects?

**Comment by morrone** [comment]
Yes, I don't think we should do subdir-objects without a really good reason.
