### ISSUE TITLE
Error starting ldms client from OVIS-4.3.4-alpha.1

### ISSUE THREAD

**Issue by wooloo1121** [ovis-hpc/ovis#460]
Hello,

In #434, we are recommended to use the latest 4.3.4 version to get compatible with lustre 2.12. 

We just installed the version of ldms client from OVIS-4.3.4-alpha.1 while keeping the server side 4.3.3 for now. But when we tried to start the client process with command:
ldmsd -x sock:10001 -l /var/log/ldmsd.log -s /var/run/ldmsd.sock -r /var/run/ldmsd.pid -c /opt/ovis/config/ldmsd.conf

there came the error:
ERROR     : 'sock' transport creation with auth 'none' failed, error: ENOENT(2). Please check transpot configuration, authentication configuration, ZAP_LIBPATH (env var), and LD_LIBRARY_PATH.

The error remained with ovis authentication added to the command:
ldmsd -x sock:10001 -l /var/log/ldmsd.log -s /var/run/ldmsd.sock -r /var/run/ldmsd.pid -c /opt/ovis/config/ldmsd.conf -a ovis -A conf=/opt/ovis/config/ldmsdauth.conf

or with naive authentication added:
ldmsd -x sock:10001 -l /var/log/ldmsd.log -s /var/run/ldmsd.sock -r /var/run/ldmsd.pid -c /opt/ovis/config/ldmsd.conf -a naive -A uid=0

When we tried to switch back to 4.3.3 client, the error disappeared.

What might the problem be? 

Thank you very much and look forward to your reply.

**Comment by tom95858** [comment]
Hi @wooloo1121, it looks like it's failing to find the transport or authentication plugin. These are loaded using dlopen(). The transport plugins are located using the ZAP_LIBPATH, and the authentication plugins are located using LD_LIBRARY_PATH environment variables. A guess is that one or both of these don't point to the correct location for your installation.

The authentication plugins have names like:

* ovis
** libldms_auth_ovis.so
* none
** libldms_auth_none.so
* ...

The transport plugins have names like:
* sock
** libzap_sock.so
* rdma
** libzap_sock.so

If you built from source, then the --prefix argument of your configure line specifies the install path where the transport plugins are in <prefix>/lib/ovis-ldms, and the authentication plugins are in <prefix>/lib/

**Comment by wooloo1121** [comment]
@tom95858 Thank you!
