### ISSUE TITLE
Error message if launch w/ munge but not built with munge?

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#464]
I built without --enable-munge, so no munge libraries built. I launched an ldmsd with -a munge and got no error message. I also queried it with ldms_ls -a munge and got no error message. Should there be?

**Comment by tom95858** [comment]
Hi @oceandlr, it probably found a previusly built munge authentication library in your install/LD_LIBRARY_PATH. Perhaps there were no sets on the **ldmsd** you were querying?

**Comment by oceandlr** [comment]
There were sets on the ldmsd. I did not see them with -a munge, but I did see them when I ran with -a none (thanks @baallan !)

I will check again to be sure that there isn't an old munge lib build. (I emptied out the build dir, but I will make sure I didn't have somewhere else, like a system installed version).

**Comment by tom95858** [comment]
@oceandlr can you point me at the host that exhibits this behavior. And can you show me exactly the commands that were executed.

**Comment by baallan** [comment]
I did a pull and rebuild and test (centos 7) this morning. And the log for requesting munge shows:
Tue Oct 20 08:41:56 2020: DEBUG     : Checking for meminfo in /home/baallan/ovis/repos/v42lp/LDMS_install/lib/ovis-ldms
Tue Oct 20 08:41:56 2020: DEBUG     : msg_no 0 flags 3 rec_len 28 rsp_err 0
Tue Oct 20 08:41:56 2020: DEBUG     : msg_no 1 flags 3 rec_len 28 rsp_err 0
Tue Oct 20 08:41:56 2020: DEBUG     : msg_no 2 flags 3 rec_len 28 rsp_err 0
Tue Oct 20 08:41:56 2020: INFO      : Processing the config file '/home/baallan/ovis/repos/v42lp/ldmstest/munge/run/conf.1' is done.
Tue Oct 20 08:41:56 2020: ERROR     : 'sock' transport creation with auth 'munge' failed, error: ENOENT(2). Please check transpot configuratio
n, authentication configuration, ZAP_LIBPATH (env var), and LD_LIBRARY_PATH.
Tue Oct 20 08:41:56 2020: DEBUG     : mmap use at exit: mm_stat: size=524288 grain=1024 chunks_free=1 grains_free=508 grains_largest=508 grain
s_smallest=508 bytes_free=520192 bytes_largest=520192 bytes_smallest=520192 bytes_used+holes=4096
Tue Oct 20 08:41:56 2020: CRITICAL  : LDMSD_ LDMS Daemon exiting...status 6, error creating transport
Tue Oct 20 08:41:56 2020: CRITICAL  : LDMSD_ cleanup end.

This should be reproducible by configuring the build without --enable-munge, installing, and then  running:

$prefix/bin/ldms-static-test.sh munge

While that fails, the corresponding command should work:
$prefix/bin/ldms-static-test.sh meminfo

**Comment by baallan** [comment]
@gentile if we merge PR #448, then the right error ("plugin %s not found in ZAP_LIBPATH=%s. Check that build and installation enables %s\n",plugname,path,plugname) could be logged at the right scope.

**Comment by oceandlr** [comment]
OK, @baallan so you saw the error? Yeah, I thought @tom95858 's comment was probably correct -- it found an only one somewhere, so there was no error message, but because it was conflicting the query didn't work. I won't get a chance to try it till tonight.

**Comment by baallan** [comment]
@gentile Yes, if there is an ovis installed to /opt or /usr that is in your LD_LIBRARY_PATH, then you will get the old version plugins because the ldms_auth  libraries are found via LD_LIBRARY_PATH instead of searching ZAP_LIBPATH due to how they are declared in the Makefile.ams (lib_LTLIBRARIES += libxxx.la instead of pkglib_LTLIBRARIES += libxxx.la) and dlopened.

**Comment by oceandlr** [comment]
Well I'm printing out the LD_LIBRARY_PATH and it looks like its just the libs under my current build.  However, the explanation is rational and since @baallan can reproduce it, I assume I still have something somewhere. I am fine closing this.

**Comment by oceandlr** [comment]
In the current release (see today's date): You do get a log message if using ugni. You do not get a log message if you use sock. Might be an issue in different paths taken.
