### ISSUE TITLE
lustre2_client sampler on lustre 2.10 ovis 4.3.4 beta

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#479]
With lustre 2.10 (files in /proc/fs/lustre/[llite,osc,mdc]:
If I configure the sampler with 'llite=* msc=* osc=*', the sampler works, but the metrics are named funny (see below) with extra type and numeric suffixes.
If I configure it with the device name as expected 'llite=cls02006 msc=cls02006-MDT0000 osc=cls02006-OST0000' it fails (silently collect all-0 sets).
If I configure it with llite=cls02006-01 , it succeeds.
The llite and other device names rooted at cls02006 as determined from
```
ls /proc/fs/lustre/llite/
cls02006-ffff9e9480276800
ls /proc/fs/lustre/mdc/
cls02006-MDT0000-mdc-ffff9e9480276800  cls02006-MDT0001-mdc-ffff9e9480276800
ls /proc/fs/lustre/osc/
cls02006-OST0000-osc-ffff9e9480276800  cls02006-OST0001-osc-ffff9e9480276800
# notice the lack of a -01 anywhere in these names.
```
The metric names it generates if using * to select devices to sample are of the forms seen here via ls:
D u64        client.status#osc.cls02006-OST0000-osc-01  1
D u64        client.status#mdc.cls02006-MDT0000-mdc-01  1
D u64        client.status#llite.cls02006-01            1
I expected metric names such as:
D u64        client.status#osc.cls02006-OST0000  1
D u64        client.status#mdc.cls02006-MDT0000 1
D u64        client.status#llite.cls02006           1

**Comment by baallan** [comment]
What I would really like to see is separate metric sets for each device or target, but for now making it name as in v3 with lustre 2.8 would be sufficient

**Comment by baallan** [comment]
@morrone Are you running lustre 2.10 clients anywhere and seeing similar naming? Or only 2.12 clients?
This is on our toss3.6-6/lustre 2.10 client systems.

**Comment by morrone** [comment]
We don't use the ovis provided lustre plugins. We use (where we use anything at all right now) the lustre client plugin from ldms-plugins-llnl that creates a separate metric set for each lustre filesystem mount (llite instance).

**Comment by baallan** [comment]
currently the sampler also ignores the schema= argument when it is supplied. Schema stays lustre2_client.

**Comment by baallan** [comment]
the llnl lustre plugins are now in the main tree, so this issue is no longer concerning.
