### ISSUE TITLE
read/write bytes

### ISSUE THREAD

**Issue by wooloo1121** [ovis-hpc/ovis#483]
Hi,

We have the lustre2_client plugin working now thanks to your help :), but are still a little confused about the meaning of the metrics. Are the read_bytes and write_bytes cumulated values since a certain time or something else? 

Besides, we are very interested in the total read/write byte amount produced by each job, are these values collected by ldms somewhere? from Lustre job stats for example

Thank you so much and look forward to your reply.

**Comment by baallan** [comment]
please see:
https://ovis.ca.sandia.gov/index.php/LDMS_Metric_Definitions
for lustre2_client. most of the counters are just increasing event/byte counters (that may eventually roll over at their upper bound-- integral metrics).

**Comment by baallan** [comment]
We have created an analysis prototype which computes total & lustre usage rate per job based on the lustre client statistics. 
This is not, however, part of ldms. It is part of the sos database and grafana development work byh SNL/OGC.

We have not created a sampler of lustre server-side job stats. If you would like to contribute one, that would be good to have.

**Comment by wooloo1121** [comment]
Hi @baallan, thank you for the reply. I also see metric like "client.read_bytes.rate" which seem to be zero for most of the time. Are they collected from somewhere or do you calculate them? and how are they calculated if so?

**Comment by baallan** [comment]
There is was in an earlier ldms version of the plugin, a feature that attempted to compute rates of some metrics at the sampler. It does not exist in the present version 4, as far as I can tell.

**Comment by baallan** [comment]
I highly recommend using the newer LLNL samplers for lustre client stats and server mdt/ost data. They are at:
https://github.com/LLNL/ldms-plugins-llnl
These plugins require less configuration and do not generate conflicting schemas on cluster systems where the mounted lustre volumes vary by host.

**Comment by wooloo1121** [comment]
@baallan Thank you for the suggestion. We tried installing the llnl sampler, it seems to work as the /var/log/ldmsd.log tells:
Wed Nov 04 12:55:10 2020: DEBUG     : lustre_client sample() called
Wed Nov 04 12:55:10 2020: DEBUG     : lustre_client llite_general_sample() scrfs-ffff8a9c191bb000
Wed Nov 04 12:55:10 2020: DEBUG     : lustre_client llite_general_sample() sjtu-ffff8ab33a353000

But we could not see data with the ldms_ls command or at the database. 

To install the sampler, we compiled the sampler and then copy the files under /usr/local/lib/ovis-ldms/ to /opt/ovis/lib/ovis-ldms/

At the configuration file, we have the following lines:
load name=llnl_lustre_client
config name=llnl_lustre_client
start name=llnl_lustre_client interval=1000000

Is there anything else we need to do? Thank you and look forward to your reply.

**Comment by baallan** [comment]
I don't think there's anything special about the llnl plugin with respect to ldms_ls or stores.
You can successfully ldms_ls the meminfo plugin data set on the same node configured with the lustre plugin?

**Comment by wooloo1121** [comment]
@baallan Yes the other plugins configured works with ldms_ls. 

It seems the llnl plugin is not "integrated" into ldms... Since it does not naturally come with ldms, is there anything else that needs to be done other than copying over the lib files? We don't find instructions on installing separate plugins.

**Comment by baallan** [comment]
Since you have log lines indicating the lustre plugin started and found devices, it looks like the compile and copy to prefix/lib/ovis-ldms worked as expected.  The build should be ok unless you have multiple ldms installations on the build host and the build for the lustre plugin was configured with an ldms installation other than the one you copied the library to.

**Comment by baallan** [comment]
If you can attach the entire daemon configuration file, the entire log file of the sampler daemon running with -v DEBUG, and the output file of "env > env.txt" and the output of "ldms_ls -lv $your_site_specific_args_to_ls" we might be able to spot something.

**Comment by wooloo1121** [comment]
@baallan We end up with installing ldms by default path and the llnl plugins begin to show up. To have the job stats plugins working, we install them on mds and oss nodes. Do they work well in your environment? since on oss node, it sometimes work with ldms_ls, sometimes we get the following:
first_line   : 0
last line    : 0
first column : 6
last column  : 9
str           : syntax error, unexpected DQUOTED_STRING_T, expecting ',' or '}'
Error 1 looking up the metric set directory.

and on mds node, the read and write bytes are always 0.

**Comment by baallan** [comment]
@wooloo1121 please open a new issue. In it, 
- give the exact lustre version running on the mds and oss servers where you see the issue.
- attach the entire ldmsd configuration file used to start the samplers.
- attach a file lls.log capturing the environment and ls data, e.g. script -c 'env && ldms_ls ...the_arguments' lls.log

**Comment by wooloo1121** [comment]
@baallan Thank you for the reply. It turns out a bug in the plugin, and they fixed it now.

**Comment by wooloo1121** [comment]
@baallan Sorry for posting here again, but I just want to confirm something. We tried with 4.3.3 at the aggregator side, but it can't collect the per job metric sets generated by the llnl samplers and no job specific data are showing in the sos store. Is it because of something in the daemon hosting the store plugins? so the sets are not sent to the store plugins.. Thank you so much and look forward to your reply.

**Comment by baallan** [comment]
Are you using the exact same version and build of ldmsd on all nodes? What version(s)? What transport (sock, fabric, rdma, ugni) are you using?

**Comment by wooloo1121** [comment]
@baallan, Sorry for the late reply and thank you so much for your reminding. We changed to the exact same version (the latest) at both sampler and aggregator sides, tried with csv store and added the job stats schema. Now it works :)
