### ISSUE TITLE
Can you provide a Baler usage example?

### ISSUE THREAD

**Issue by zongzeliunt** [ovis-hpc/ovis#5]
Hi, I'm having a cooperate project with LANL and this project requires using Baler to perform syslog analysis. I have succeed build OVIS and baler. However I don't know how to use it. The balerd -h page provide very little information and the man page of balerd are all garbled codes. Besides this the balerd -h page saids for more information see balerd(3) manpage, I can't find what balerd(3) is. So can you provide me some information about how to use baler to read a system log file and generate the pattern sequence file?
I tried to run command "balerd -l file.txt" to analyze file.txt, the output is a folder called "store" but all the files in that folder are unreadable. Do my method of running baler is correct? If not can you tell me what the correct way is?

**Comment by narategithub** [comment]
If you build with `--enable-doc --enable-doc-man`, the man page should be located at `$PREFIX/share/man/man1/balerd.1`. Sorry for the man page reference typo, it should be `balerd(1)` instead of `balerd(3)`.

If you build with `--enable-doc-html`, HTML help pages (by doxygen) is generated in `$PREFIX/share/doc/baler/html`. You can also see them online [here](https://git.opengridcomputing.com/baler/index.html).

For balerd usage, see [balerd(1)](https://git.opengridcomputing.com/baler/balerd.html).

Man pages for baler plugins can also be found on the doxygen [related pages](https://git.opengridcomputing.com/baler/pages.html).

balerd runs as a daemon and process the data live. So, if you want it to process files, please use this perl script to feed log messages to baler: `OVIS/baler/src/tools/syslog2baler.pl`.

I hope this help.

Cheers,
Narate

**Comment by zongzeliunt** [comment]
Hi Narate:
Thank you for your explanation. I have read the whole man pages and now I have some first step knowledge. However I can't find and guidance of how to use perl script to feed log messages to baler.  
I still have 3 questions:
1) How can I write the message format into the configure file to point which part of the message is time step and node id?
2) How to run balerd as a daemon?
3) How to run that perl script to input a log file and feed messages into baler?
BTW:  can you give me you email address, so I can discuss with you directly?
Thank you very much
Zongze

**Comment by zongzeliunt** [comment]
Anybody can help me on how to use syslog2balerd.pl? It's urgent! Thanks!

**Comment by narategithub** [comment]
1. `bin_rsyslog_tcp` only consume syslog format input, (e.g. `2015-03-30T09:40:09.997394-06:00 localhost Some messages`).

2. it run as a daemon by default, unless you specify -F, then it will run in the foreground.

3. `./syslog2baler.pl --help` should give you the information. But, in summary: `./syslog2baler.pl -host BALER_HOST -port BIN_RSYSLOG_TCP_PORT < log_file`. The port is the one you specify for `bin_rsyslog_tcp` in the config file. If you have more than one file, repeat the command for each file.

Let's discuss in the thread. It might be useful to others as well :)

p.s. to config rsyslog to forward messages to balerd, add the following line in `/etc/rsyslog.conf`

```
*.* @@<BALERD_IP_ADDRESS>:<BIN_RSYSLOG_TCP_PORT>
# e.g. 
# *.* @@127.0.0.1:10514
```

**Comment by zongzeliunt** [comment]
Thanks Narate, there still have problem.
I run baler in these steps:
1) Write "plugin name=bin_rsyslog_tcp port=55555" in configure.txt 
2) Run command "build/sbin/balerd -C configure.txt", command line show message "Fri Mar 3 13:22:32 2017 ERR: zap_listern() error: ZAP_ERR_RESOURCE" but not terminated. 
3) Run command ./syslog2baler.pl -host localhost -port 55555 < test.txt. Command line show message “connect: Connection refused at ./syslog2balerd.pl line 78” and balerd will terminate. 
According to the message, seems I failed to connect to the port which balerd is using, or maybe balerd didn't use the port 55555.
I don't know if my method of running balerd is correct, or that's not what you mean balerd is running as a daemon.  I'm just a rookie of using tools on linux. I wish you can give me as detailed as possible of guidance.  
BTW: how can I know if port 55555 is occupied by balerd?

**Comment by narategithub** [comment]
I apologize for a bad example again :(
The listening port should be `< 32768` as the default settings for ephemeral port (local port automatically created by the OS) range is `32768-61000`

I recommend port 10514 as it rhymes the rsyslog port `514`

To see who binds to a port, you can do `netstat -tanp` (as root).

Be mindful that the port you are forwarding messages to (10514) is BIN_RSYSLOG_TCP port in baler config file.

**Comment by zongzeliunt** [comment]
Thanks Narate. Your help is very useful. I changed port as 10514 and rerun balerd. Then I checked port occupation by "netstat -tanp" it shows balerd is occupying port 30003, not 10514. I know 30003 is the default port of balerd. I just feel surprised why it's not using port 10514. But anyway I know which port it's bind to.
I tried to feed test log messages into port 30003, it do not show "connection refused" again. I think balerd have already received my message. However I can't find where balerd output is. The only folder balerd generated is "store", and all the files inside are unreadable. 
I already write a host file path and keyword dictionary file path into balerd's configure file. I don't know if they have been accepted by balerd. 
I think balerd will generate a message pattern list for me, is that correct? Can you tell me how can I find it? Or should I use some special tool to read the files in folder "store"?

**Comment by narategithub** [comment]
1. I think 30003 is the port for balerd-to-balerd communication (slave-master mode for multiple baler daemons)

2. If you set BIN_RSYSLOG_TCP port to 10514 and netstat didn't report that balerd owns 10514 ... something is wrong. Please check the log file for more info.

3. As for the output, you need `bquery`. For example: `bquery -s store -t ptn` to see all of the patterns. For more information, please see https://git.opengridcomputing.com/baler/bquery.html

4. You might be interested in `bclient`, the interactive program to read data from the store. For more information, please see https://git.opengridcomputing.com/baler/bclient.html

**Comment by zongzeliunt** [comment]
Thank you Narate. I can assign port 10514 to balerd right now. I've opened one balerd process by default, I should kill it before I run balerd using new configuration. 
The bquery command can work for me. I can see each pattern_id and their happen count. However some of the patterns are just a dot or some symbols, not a sequence of English words or word IDs. I wonder are they encrypted? If I can output all the English words IDs and all the patterns which baler detected from test file that's best for me. 
I haven't try all the operations of bquery, Hope some operations can help me to find all the information I need. 
Baler is really a powerful tool, Now I finally know how it works. Thank you for your help these days. I really appreciate all you have done for me.
Zongze

**Comment by valleydlr** [comment]
Hi Zongze,


I am a researcher at Sandia and work with a number of people at LANL. Perhaps we can set up a brief phone meeting so I can better understand your use case and perhaps connect you with someone at LANL that might be able to directly assist you. If you have some availability tomorrow (Thursday) morning after 9:00 AM let me know and I would be more than happy to give you a call.


Thanks,

Jim Brandt

________________________________

**Comment by zongzeliunt** [comment]
Hi Jim:
Sorry I didn't see your comments last night. I am free this afternoon and you can call me at 940-999-4806. These days I am trying to use baler to analyze mutrino log and find out what format of pattern and keyword id could be generated by baler. I have developed a syslog event block detector and wish to implement my tool on baler's result. This is a main goal of my lab and LANL's cooperate project. Thank you for assisting me. 
Zongze

**Comment by zongzeliunt** [comment]
Hi Jim:
Sorry I didn't see your comments last night. I am free this afternoon and you can call me at 940-999-4806. These days I am trying to use baler to analyze mutrino log and find out what format of pattern and keyword id could be generated by baler. I have developed a syslog behavior learning tool and wish to implement my tool on baler's result. This is a main goal of my lab and LANL's cooperate project. Thank you for assisting me.
Zongze

**Comment by zongzeliunt** [comment]
Hello: 
These days I was kept using baler. It's very cool. I have used it to do a lot of syslog analyze. 
I just have one question: does baler have any feature to restore the database without terminate the process and remove "store" folder? Sometimes I kept input the same file into baler and want it to output a pattern list file. The result I output will be repeat a lot of times. I have to gather the root permit, terminate the balerd process and remove the store folder. It's very inconvenient.
Thank you

**Comment by valleydlr** [comment]
Hi,


Could you describe an example sequence and the symptom/problem you are seeing?


Thanks,

Jim

________________________________

**Comment by zongzeliunt** [comment]
I wish to clean the whole "store" folder without terminate balerd process.
I have a lot of original log files want to preprocessed by baler. However as the original files been preprocessed, there will have pattern-line message information in "store" folder. I wish I can use one command to totally clean all the information in "store" folder. Is there any command can help me?
Thank you.

**Comment by hugegreenbug** [comment]
I have a similar issue to @zongzeliunt . I followed the directions listed here and it appears to be working, but 

`bquery -s store -t ptn`

shows just lines with dots and punctuation. Is that what it should be showing? How can I visualize the patterns/clusters? Thanks.

**Comment by hugegreenbug** [comment]
I figured out that I needed to put the dictionary path in the config file. Now that I have, I see patterns that aren't just dots and punctuation.

I'm still wondering about the visualization support. Thanks.

**Comment by pgtgrly** [comment]
Hi, I'm currently using Baler to process some syslog data. I've run syslog2baler.pl on logs but when I run bquery on the store, the only output is two lines of dots. I think something is going wrong here.

Possible issues could be
1. balerd is listening at port 10514 as well as 30003
2. The configuration file is inadequate ( it only contains one line : plugin name=BIN_RSYSLOG_TCP port=10514" )
3. I'm unclear on the format of the dictionary file. Is it just a list of words?  What about the format for the host and token file. I find the documentation in balerd(1) to be inadequate. Some clarity on this issue would be very appreciated.

Thanks
