### ISSUE TITLE
Error starting the ldms aggregator with the tip of ovis-4 branch

### ISSUE THREAD

**Issue by wooloo1121** [ovis-hpc/ovis#510]
Hello,

We tried to start the ldms aggregator with the tip of ovis-4 branch, but had the following error:
ldmsd: ../../../../lib/src/coll/rbt.c:639: rbt_del: Assertion `t->card' failed.

We didn't have it when using 4.3.3. Should the configuration of the aggregator side change in any way?
Thank you and look forward to your reply.

Our entire configuration file is as follows

**Comment by wooloo1121** [comment]
prdcr_add name=cas001 host=cas001 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas002 host=cas002 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas003 host=cas003 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas004 host=cas004 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas005 host=cas005 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas006 host=cas006 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas007 host=cas007 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas008 host=cas008 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas009 host=cas009 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas010 host=cas010 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas011 host=cas011 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas012 host=cas012 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas013 host=cas013 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas014 host=cas014 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas015 host=cas015 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas016 host=cas016 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas017 host=cas017 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas018 host=cas018 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas019 host=cas019 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas020 host=cas020 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas021 host=cas021 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas022 host=cas022 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas023 host=cas023 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas024 host=cas024 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas025 host=cas025 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas026 host=cas026 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas027 host=cas027 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas028 host=cas028 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas029 host=cas029 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=cas030 host=cas030 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=hwmds1 host=hwmds1 port=10001 xprt=sock type=active interval=20000000
prdcr_add name=hwoss1 host=hwoss1 port=10001 xprt=sock type=active interval=20000000

prdcr_start name=cas001
prdcr_start name=cas002
prdcr_start name=cas003
prdcr_start name=cas004
prdcr_start name=cas005
prdcr_start name=cas006
prdcr_start name=cas007
prdcr_start name=cas008
prdcr_start name=cas009
prdcr_start name=cas010
prdcr_start name=cas011
prdcr_start name=cas012
prdcr_start name=cas013
prdcr_start name=cas014
prdcr_start name=cas015
prdcr_start name=cas016
prdcr_start name=cas017
prdcr_start name=cas018
prdcr_start name=cas019
prdcr_start name=cas020
prdcr_start name=cas021
prdcr_start name=cas022
prdcr_start name=cas023
prdcr_start name=cas024
prdcr_start name=cas025
prdcr_start name=cas026
prdcr_start name=cas027
prdcr_start name=cas028
prdcr_start name=cas029
prdcr_start name=cas030
prdcr_start name=hwmds1
prdcr_start name=hwoss1

updtr_add name=compute interval=6000000 offset=200000
updtr_prdcr_add name=compute regex=.*
updtr_start name=compute

load name=store_sos
config name=store_sos path=/data/sos

strgp_add name=meminfo_sos plugin=store_sos container=meminfo schema=meminfo
strgp_add name=vmstat_sos plugin=store_sos container=vmstat schema=vmstat
strgp_add name=lustre2_client_sos plugin=store_sos container=lustre2_client schema=lustre2_client
strgp_add name=procnetdev_sos plugin=store_sos container=procnetdev schema=procnetdev
strgp_add name=procstat_sos plugin=store_sos container=procstat schema=procstat
strgp_add name=llnl_lustre_client_sos plugin=store_sos container=llnl_lustre_client schema=llnl_lustre_client
strgp_add name=llnl_lustre_mdt_sos plugin=store_sos container=llnl_lustre_mdt schema=llnl_lustre_mdt
strgp_add name=llnl_lustre_ost_sos plugin=store_sos container=llnl_lustre_ost schema=llnl_lustre_ost

strgp_start name=meminfo_sos
strgp_start name=vmstat_sos
strgp_start name=lustre2_client_sos
strgp_start name=procnetdev_sos
strgp_start name=procstat_sos
strgp_start name=llnl_lustre_client_sos
strgp_start name=llnl_lustre_mdt_sos
strgp_start name=llnl_lustre_ost_sos

**Comment by tom95858** [comment]
Hi @wooloo1121, do you have a log from the failing aggregator?

**Comment by wooloo1121** [comment]
Hi @tom95858, the log for the above configuration file is very long (due to the many samplers on compute nodes and mds/oss servers), we turn to use the following configuration:

prdcr_add name=cas001 host=cas001 port=10001 xprt=sock type=active interval=20000000
prdcr_start name=cas001

updtr_add name=compute interval=60000000 offset=200000
updtr_prdcr_add name=compute regex=.*
updtr_start name=compute

load name=store_sos
config name=store_sos path=/data/sos

strgp_add name=meminfo_sos plugin=store_sos container=meminfo schema=meminfo
strgp_start name=meminfo_sos

And get the same error at the end of the relevant log as follows:

Sun Nov 15 09:04:08 2020: DEBUG     : ldmsd_prdcr_new(name cas001, xprt sock, host cas001, port 10001, type 0, intv 20000000
Sun Nov 15 09:04:08 2020: DEBUG     : msg_no 0 flags 3 rec_len 28 rsp_err 0
Sun Nov 15 09:04:08 2020: DEBUG     : msg_no 2 flags 3 rec_len 28 rsp_err 0
Sun Nov 15 09:04:08 2020: DEBUG     : msg_no 3 flags 3 rec_len 43 rsp_err 0
Sun Nov 15 09:04:08 2020: DEBUG     : Checking for store_sos in /usr/local/lib/ovis-ldms
Sun Nov 15 09:04:08 2020: DEBUG     : msg_no 5 flags 3 rec_len 28 rsp_err 0
Sun Nov 15 09:04:08 2020: DEBUG     : msg_no 6 flags 3 rec_len 28 rsp_err 0
Sun Nov 15 09:04:08 2020: DEBUG     : msg_no 7 flags 3 rec_len 28 rsp_err 0
Sun Nov 15 09:04:08 2020: INFO      : Processing the config file 'test.conf' is done.
Sun Nov 15 09:04:08 2020: INFO      : Listening on sock:10001 using `sock` transport and `none` authentication
Sun Nov 15 09:04:08 2020: DEBUG     : updtr 'compute' getting auto-schedule
Sun Nov 15 09:04:08 2020: INFO      : Enabling in-band config
Sun Nov 15 09:04:08 2020: INFO      : Producer cas001 is connected (sock cas001:10001)
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001/vmstat'
Sun Nov 15 09:04:08 2020: DEBUG     : producer 'cas001' add set 'cas001/vmstat' to hint tree
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001/procstat'
Sun Nov 15 09:04:08 2020: DEBUG     : producer 'cas001' add set 'cas001/procstat' to hint tree
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001/procnetdev'
Sun Nov 15 09:04:08 2020: DEBUG     : producer 'cas001' add set 'cas001/procnetdev' to hint tree
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001/meminfo'
Sun Nov 15 09:04:08 2020: DEBUG     : producer 'cas001' add set 'cas001/meminfo' to hint tree
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001/lustre2_client'
Sun Nov 15 09:04:08 2020: DEBUG     : producer 'cas001' add set 'cas001/lustre2_client' to hint tree
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001/jobinfo'
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000'
Sun Nov 15 09:04:08 2020: INFO      : Adding the metric set 'cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/jobinfo'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/lustre2_client'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/meminfo'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/procnetdev'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/procstat'
Sun Nov 15 09:05:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/vmstat'
Sun Nov 15 09:05:00 2020: INFO      : Set cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000 is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000 is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001/jobinfo is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001/lustre2_client is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001/meminfo is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001/procnetdev is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001/procstat is ready
Sun Nov 15 09:05:00 2020: INFO      : Set cas001/vmstat is ready
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/jobinfo'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001/jobinfo
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/lustre2_client'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001/lustre2_client
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/meminfo'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001/meminfo
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/procnetdev'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001/procnetdev
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/procstat'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001/procstat
Sun Nov 15 09:06:00 2020: DEBUG     : updtr_task sched '60000000': set 'cas001/vmstat'
Sun Nov 15 09:06:00 2020: DEBUG     : Schedule an update for set cas001/vmstat
Sun Nov 15 09:06:00 2020: DEBUG     : Update complete for Set cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000 with status 0
Sun Nov 15 09:06:00 2020: DEBUG     : Pushing set 0x7f18f4000d10 cas001.pi.sjtu.edu.cn/scrfs-ffff8a9c191bb000
Sun Nov 15 09:06:00 2020: DEBUG     : Update complete for Set cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000 with status 0
Sun Nov 15 09:06:00 2020: DEBUG     : Pushing set 0x7f18f4002cb0 cas001.pi.sjtu.edu.cn/sjtu-ffff8ab33a353000
Sun Nov 15 09:06:00 2020: DEBUG     : Update complete for Set cas001/jobinfo with status 0
Sun Nov 15 09:06:00 2020: INFO      : Set cas001/jobinfo is inconsistent.
Sun Nov 15 09:06:00 2020: DEBUG     : Pushing set 0x7f18f40028d0 cas001/jobinfo
Sun Nov 15 09:06:00 2020: DEBUG     : Update complete for Set cas001/lustre2_client with status 0
Sun Nov 15 09:06:00 2020: DEBUG     : Pushing set 0x7f18f40045b0 cas001/lustre2_client
Sun Nov 15 09:06:00 2020: DEBUG     : Update complete for Set cas001/meminfo with status 0
ldmsd: ../../../../lib/src/coll/rbt.c:639: rbt_del: Assertion `t->card' failed.

If we comment out the first five lines in the configuration, namely:
 prdcr_add name=cas001 host=cas001 port=10001 xprt=sock type=active interval=20000000
prdcr_start name=cas001

updtr_add name=compute interval=60000000 offset=200000
updtr_prdcr_add name=compute regex=.*
updtr_start name=compute

Then the error disappears.
