### ISSUE TITLE
help required to create our own metricset

### ISSUE THREAD

**Issue by jhansipasupuleti** [ovis-hpc/ovis#53]
How to write our own metricset with schema named  **dynamicinfo** which fetches the following paramaters : 

- cpu load
- free memory
-  free disk
- cpu utilization
-  uptime 

As LDMS have metric sets -  meminfo, vmstat  ?

Referred Document [https://github.com/ovis-hpc/ovis/wiki/Writing-a-sampler](url) But i did not get clear idea of how to write own metricset 
Can you please help me with the issue ?

**Comment by ovis-hpc** [comment]
There is a more comprehensive description for writing a sampler as well as the LDMSCON2019 tutorial posted. Do these provide enough information now? @jhansipasupuleti
