### ISSUE TITLE
Missing documentation for reconfiguring makefikes  for new plugins

### ISSUE THREAD

**Issue by saurabhjha1** [ovis-hpc/ovis#54]
https://github.com/ovis-hpc/ovis/wiki/Writing-a-sampler shows how to write a new plugin but it does not mention how to change the makefiles for compiling the new plugin.

By the way, great job on providing the video on how to setup and run LDMS. It was very easy to deploy LDMS on our test infra.

**Comment by bschwal** [comment]
Saurabh, I'm not the expert on this so hopefully others will chime in. We are trying to enable collaborators to add their own samplers and make integration easier. An example of this can be found under /ovis/ldms/src/sampler/contrib. You should be able to add --enable-NAMEOFSAMPLER to your configure statement after setting up the Makefiles and source code akin to that in the contrib directory.

Also good to hear on the feedback on the video! Please let us know if other topics (perhaps this one) would be beneficial for such a format.

**Comment by saurabhjha1** [comment]
Thanks for the info. I recommend adding the info on "--enable-NAMEOFSAMPLER" to "https://github.com/ovis-hpc/ovis/wiki/Writing-a-sampler " wiki for ease.
