### ISSUE TITLE
contribute a new store plugin (TimescaleDB)

### ISSUE THREAD

**Issue by wooloo1121** [ovis-hpc/ovis#541]
Hi,

We developed a store plugin to save data into TimescaleDB, the code is currently placed under ovis/ldms/src/contrib/store in our forked repository https://github.com/SJTU-HPC/ovis/tree/timescaledb_store_plugin . We are considering to contribute it to you, can we just create a pull request? And is it placed in the right directory?

Thank you and look forward to your reply.

**Comment by ovis-hpc** [comment]
That looks very interesting.

From a quick look at your repo:


Including an complete example test/demo configuration file (not embeded in a man page) would be helpful. Apologies if it's there and I somehow overlooked it.


The contribution needs a clear LICENSE file indicating how your institution/company licenses this code contribution before we can merge it into our code repo. Ideally we also need some documentation (not via github) of your copyright status if this was developed in a gov't laboratory or university.


I strongly recommend you adjust your plugin configuration parameters to keep the database password out of ldmsd configuration files/strings. Key material should be tightly controlled and minimally replicated.

We achieve this in other plugins by defining a parameter which names a file with the key in it and having the plugin obtain the key from there or by using a key service such as munge. The rabbitkw store shows one way to do it, but by no means the only way.


thanks much,

Ben


________________________________

**Comment by wooloo1121** [comment]
@ovis-hpc Thank you for the reply. We adjusted the password configuration to reading the password from file whose path should be specified in the configuration file, and added a demo one (example.conf). A license file is added. But for the "documentation" you asked, we're not sure. Do you have a template that we can use as a reference? And does it need to be signed by the university or ok just by individuals?

**Comment by baallan** [comment]
@wooloo1121 Most universities have intellectual property policies that need to be followed, where signature authority rests with some administrative official/department. I have no idea how it works in your specific institution, but usually research staff/students do not have it. @valleydlr @oceandlr may have more specific experience; I can't tell from github messages what your institution is. 

We need to be sure all is done correctly to avoid legal problems later.

**Comment by wooloo1121** [comment]
Hi @baallan, we are HPC center at Shanghai Jiao Tong University (Shanghai, China). I contacted relevant departments of our university and they don't have any documentation for this. We think it's fine to go without it, but if you really need one we could make a document and get it signed by our center leader. Please let me know which way you  prefer. Thanks.

**Comment by tom95858** [comment]
Hi @wooloo1121, if this sampler is a derivative work, then all you need to do is retain the existing copyright and add your institution's name to the top of that copyright. The existing copyright holders remain, and your institution "HPC center at Shanghai ..." would be added to the list of copyright holders.

So what is a "derivative work?" In the simplest terms, this means that you created the storage plugin by copying an existing plugin and modifying it to support TimescaleDB.

To be specific, something like this:

```
/* -*- c-basic-offset: 8 -*-
 * ... existing copyright holders, e.g...
 * Copyright (c) 2012-2018 Open Grid Computing, Inc. All rights reserved.
 * ...then add yours ...
 * Copyright (c) 2020 HPC Center at Shanghai Jiao Tong University
 *
 * This software is available to you under a choice of one of two
 * licenses.  You may choose to be licensed under the terms of the GNU
 * General Public License (GPL) Version 2, available from the file
 * COPYING in the main directory of this source tree, or the BSD-type
 * license below:
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *      Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *      Redistributions in binary form must reproduce the above
 *      copyright notice, this list of conditions and the following
 *      disclaimer in the documentation and/or other materials provided
 *      with the distribution.
 *
 *      Neither the name of Sandia nor the names of any contributors may
 *      be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 *      Neither the name of Open Grid Computing nor the names of any
 *      contributors may be used to endorse or promote products derived
 *      from this software without specific prior written permission.
 *
 *      Modified source versions must be plainly marked as such, and
 *      must not be misrepresented as being the original software.
 *
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
```

**Comment by wooloo1121** [comment]
Hi @tom95858, thank you for the reply. We added ourselves to the copyright lines as you suggested, and created a pull request https://github.com/ovis-hpc/ovis/pull/562 . Please let us know if there is any more we should do. Thanks.

**Comment by morrone** [comment]
It looks like #562 landed as a single squashed commit @tom95858 created, so this issue now appears to be complete.
