### ISSUE TITLE
Is it possible to add hosts to aggregator on the fly?

### ISSUE THREAD

**Issue by saurabhjha1** [ovis-hpc/ovis#55]
I am using docker-swarm for testing my plugins. Is there a way to add hosts in the aggregator config database on the fly? Docker swarm allows to scale the number of computes dynamically, but there is no way today to add hosts to aggregator dynamically or may be I am just unaware of this functionality.

**Comment by bschwal** [comment]
Saurabh, using ldmsd_controller to add hosts is the best way to do it dynamically, similar to what was done in the tutorial video. I use a cronjob to run a python script which uses subprocess to open the ldmsd_controller and make my desired changes for similar needs.

**Comment by saurabhjha1** [comment]
That make sense. Thanks!
