### ISSUE TITLE
lustre2_oss sampler support lustre 2.12?

### ISSUE THREAD

**Issue by wooloo1121** [ovis-hpc/ovis#566]
Hi,

Does the lustre2_oss sampler support lustre 2.12? since it reports zeros for fields like req_waittime and I don't see path /sys/kernel/debug in its source file. 

By the way, which field in lustre stats files does metric like req_waittime and req_qdepth take from (last, min, avg or max)?

Thank you so much and look forward to your reply.

**Comment by tom95858** [comment]
@morrone, would you please comment on this and close as appropriate.

**Comment by morrone** [comment]
@tom95858, that is not one of the samplers that I wrote, but I will take a look.

Yes, lustre2_oss does not appear to support lustre 2.12. I think wooloo1121 already figured this out and is using my plugins from ldms-plugins-llnl (now upstreamed and in ovis 4.3.7!).  wooloo1121 also has a plugin for oss IO stats that is pending over in ldms-plugins-llnl, and can now instead be redirected to upstream.

I think the lustre2_* plugins are probably on their way to being deprecated.

**Comment by wooloo1121** [comment]
Hi @morrone @tom95858, yes I used @morrone's plugins and developed an oss IO stats plugin to meet our needs. Thank you for the replies and I'll close this.
