### ISSUE TITLE
conversion to organizational account: thread

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#569]
on 2020.12.27 - ovis-hpc was changed to an organizational account. report any immediate issues here

**Comment by oceandlr** [comment]
@morrone  please let us know if you can edit the wiki

**Comment by oceandlr** [comment]
closing as an issue. moving to new discussions

**Comment by morrone** [comment]
@oceandlr, unfortunately no, I cannot edit the wiki. Where is that new discussion taking place?

**Comment by oceandlr** [comment]
oops -- discussion is there now.
