### ISSUE TITLE
reduce publishing utilities?

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#574]
1) Can ldms/src/samplers/hello_stream/hello_publisher.c be deprecated?
2) Possibly also ldms/src/samplers/hello_stream/hello_cat_publisher.c which I wrote to be a better version of the above to also support publishing to a file with a single connection overall.

Looks like ldms/src/ldmsd/test/ldmsd_stream_publish.c has at least the same intent as hello_cat_publisher.c

If ldmsd_stream_publish.c is being used for testing, then let just make it the one official tool for publishing and get it a man page. If the reviewer agrees, I will look into doing this.

UPDATE: I'm getting ldmsd_stream_publish not publishing all the lines in the file and ending with:
Tue Dec 29 18:21:58 2020: ERROR     : The message no 286331153:46912551045856 was not found.
Tue Dec 29 18:21:58 2020: ERROR     : The message no 286331153:46912551045856 was not found.
Tue Dec 29 18:21:58 2020: ERROR     : The message no 286331153:46912551045856 was not found.
Tue Dec 29 18:21:58 2020: ERROR     : The message no 286331153:46912551045856 was not found.

**Comment by morrone** [comment]
This seems reasonable to me in general (to remove hello_*). One piece that might be missing is a server side tool to dump streams to the log file (or some other location) for testing. Or does that exist as well?

As to the error, what does your file look like? Is it valid json? Either way, I think that sounds like it is worthy of opening a new issue. Better error messages would be appreciated even if it is working as expected.

**Comment by oceandlr** [comment]
1) The hello_sampler plugin dumps messages to the log file. 
2) It is valid json. It might be timing out on the messages, but hello_cat_publisher publishes them all just fine. I didn't dig too deeply though -- since we are using the streams more in production now, it's a good time to discuss the intended tool set.

**Comment by tom95858** [comment]
There are other samplers as well that I would like to deprecate, e.g. rapl.c, hweventpapi.c, etc... I had imagined moving these samplers to a sub-directory called 'deprecated' and force them to be individually enabled before deleting them altogether.

**Comment by oceandlr** [comment]
Let's keep the **sampler** (hello_sampler), since its very useful for testing the streams. 
I'm talking about the additional **utilities** that go with it (hello_publisher, hello_cat_publisher, and ldmsd_streams_publish).

We can ditch hello_publisher right now. I think we could ditch hello_cat_publisher, if I could understand why I'm getting error messages for ldmsd_streams_publish but not for hello_cat_publisher. I can ask @tom95858 about this live and it will be easier to explain.

**Comment by oceandlr** [comment]
Just talked with @valleydlr  and @tom95858. We will:

-  keep hello_publisher.c -- since its a nice trivial tester
- drop hello_cat_publisher.c once we have verified that ldmsd_streams_publish does work from top of tree
- probably move ldmsd_streams_publish and ldmsd_streams_subscribe out of ldmsd/test so people know they can use them more generally as tools.
-

**Comment by oceandlr** [comment]
Update: ldmsd_streams_publish for json is only for 1 item in the file. hello_cat_publisher does line by line, but has a max char per line. I think for now, I will leave this as is. We can revisit it later.
