### ISSUE TITLE
OpenMPI samples won't write to CSV until after aggd stopped

### ISSUE THREAD

**Issue by qwofford** [ovis-hpc/ovis#59]
I'm mostly using /proc samplers for my sampler daemons. All of these proc samplers stream data to CSV, when the aggregator is configured to write to CSV.

The OpenMPI sampler appears to be different. When the sampler starts, a CSV header is written for the shm_sampler in the appropriate ldms output directory. However, rows are not added to this CSV file until after I kill the aggregator daemon. At this point, all of the counter results from the OpenMPI sampler are written to the shm_sampler file at once.

**Comment by baallan** [comment]
The csv sampler does not change output timing based on  which sampler the data comes from.
Output is normally buffered by the kernel IO system and network file system (if present), and may  appear in blocks or (if small) only at exit.

There are store_csv options to force early flushing (see the man page Plugin_store_csv) for testing, but they are not recommended for writing on NVME/flash and not guaranteed to help for writing on network devices.

The buffering is also a source of latency for productions stores writing to CSV which is then tailed/piped to database ingestion tools.
