### ISSUE TITLE
ldms_ls missing error message

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#598]
When using shared secret, the following incantation returns the wrong message:

```
ldms_ls  -a ovis  conf=/etc/sysconfig/ldms.d/ClusterSecrets/ldmsauth.conf -v -x sock -p 411  -l
Schema         Instance                 Flags  Msize  Dsize  UID    GID    Perm       Update            Duration          Info    
-------------- ------------------------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
ldms_ls: No metric sets matched the given criteria
```

The problem with the incantation of course is the -A missing before the conf=/... .
Instead of appearing to be connecting to an empty daemon, it should be issuing some sort of message about "authentication method 'ovis' missing parameter given by '-A conf=passwordfile"

**Comment by tom95858** [comment]
ldms_ls or any *nix command can't know whether
```
conf=/etc/...
```
is the name of the metric set you are looking for or the argument for an option you've neglected (-A). This is simply the way that *nix argument parsing works. The _ls_ command has the same behavior, e.g.

```
tom@ovs-5416 ~
$ ls  8 -l

ls: cannot access 8: No such file or directory
```
... missing -w option

**Comment by baallan** [comment]
@tom95858 That's a ridiculous statement for this situation. 
ldms_ls certainly knows it's processing the "-a " argument and that -a may need an adjunct -A argument.

**Comment by tom95858** [comment]
@baallan, -A is an optional argument. If -A were required then you would receive the expected error message. Absent that, ldms_ls would have to presume that -A must follow -a, but again that's not how *nix option parsing works.

**Comment by baallan** [comment]
@tom95858 The issue here isn't at the parsing stage, it's in auth error handling paths.

**Comment by tom95858** [comment]
@baallan, auth didn't fail in this case; it succeeded, and therefore did not go down the "auth error handling paths." Auth succeeded, the connection was established, a lookup was requested for the set named conf=/... and the remote peer could find a set by that name.

**Comment by baallan** [comment]
@tom95858 upon further inspection, you are correct-- the ls found a copy of the same secret value in a forgotten standard location. So the issue then becomes: 

When issuing message 'ldms_ls: No metric sets matched the given criteria', the "matching criteria" should be echoed at the end of the message. This would make the command line syntax issue immediately obvious in many cases, including the one here.

**Comment by tom95858** [comment]
@baallan, recognize that what you will get is something like this:
```
tom@ovs-5416 ~
$ ldms_ls -h orion-01 -p 10001 -a munge conf=/oops orion-02/.*
ldms_ls: No metric sets matched any of the given criteria:
	^orion-02/.*$
	^conf=/oops$

[sshd:] (git-branch: --)
tom@ovs-5416 ~
$ ldms_ls -h orion-01 -p 10001 -a munge conf=/oops orion-02/.* orion-01/.*
orion-01/vmstat
orion-01/slurm
orion-01/procstat
orion-01/meminfo
```
Note that in the last case, there would be no error even though conf=/oops is clearly not intended. Otherwise, I have no issue with adding the match criteria to the message.

Note that the change to the message format may break some test scripts.

**Comment by baallan** [comment]
If there is a back compatibility concern, then we could enable the extra message details only when adding some form of debug option.  Then for any "ls doesn't work as expected" request, we could respond with "have you tried adding -D to get clues?".

**Comment by tom95858** [comment]
@baallan, I'm not sure we're on the same page. The -D option would require adding tests to verify the **new** option to avoid changing the **old** test cases. I'm simply pointing out that this change may require changing existing test cases.

**Comment by baallan** [comment]
@tom95858 I would much prefer to keep all existing test cases working and just add -Dxxx (which could well have other uses like changing the log level on the _ls side).
