### ISSUE TITLE
some suggestion about the dependences 

### ISSUE THREAD

**Issue by Mrxun-JN** [ovis-hpc/ovis#601]
I m trying to install this in my Linux Server, at first , i used the default configuration , that is /usr/bin/bison & gcc 4.4.7 , i had met some errors
1) make[4]: Entering directory `/GFPS8p/zouxun/software/ovis-ldms-4.3.6/lib/src/ovis_json'
bison -y --defines=ovis_json_parser.h -o ovis_json_parser.c ovis_json_parser.y
ovis_json_parser.y:58.18-21: syntax error, unexpected identifier
make[4]: *** [ovis_json_parser.h] 错误 1 (error 1)

Solutions: **conda install bison**, and bison comes  to bison 3.7.4

then ,error 2
2)make[6]: Entering directory `/GFPS8p/zouxun/software/ovis-ldms-4.3.6/lib/src/ovis_json'
  CC       ovis_json_test-ovis_json_test.o
  CC       ovis_json.lo
flex -o ovis_json_lexer.c ovis_json_lexer.l
  CC       ovis_json_lexer.lo
In file included from ovis_json_lexer.l:5:
./ovis_json.h:120: 错误：typedef‘yyscan_t’ 重定义 (error:  typedef ‘yyscan_t’ redefined)
ovis_json_lexer.c:140: 附注：‘yyscan_t’的上一个声明在此 (warning: the previous statement ‘yyscan_t’ is here )
make[6]: *** [ovis_json_lexer.lo] 错误 1 (error 1)

Solutions: i load my gcc 5.4.0 environment

next, error 3
3) when I used gcc 5.4.0 across error 2 ,next error is

make[3]: Entering directory `/GFPS8p/zouxun/software/ovis-ldms-4.3.6/ldms/man'
./make_exits_man.sh ./../src/ldmsd/ldmsd.c ./../src/ldmsd/ldmsd_config.c > ldmsd_exits.man
/bin/sh: ./make_exits_man.sh: 没有那个文件或目录 (error : no such file or directory)
make[3]: *** [ldmsd_exits.man] 错误 127 (error code : 127)

Solutions:I moved gcc 5.4.0, and recove it to 4.4.7

Untill now, I have absolutely installed LDMS for my computer
I hope this error can be fixed !

Thanks !

**Comment by tom95858** [comment]
@Mrxun-JN, could you please try setting your locale to LANG=en_US.UTF-8 and rebuilding?

**Comment by Mrxun-JN** [comment]
> @Mrxun-JN, could you please try setting your locale to LANG=en_US.UTF-8 and rebuilding?

okey，i will add some notes.
