### ISSUE TITLE
Configuration warning on all the flags

### ISSUE THREAD

**Issue by trecakov** [ovis-hpc/ovis#616]
I am trying to build ldms on centos 7 and I am having a warning when trying to configure it. 

.....
config.status: executing libtool commands
configure: WARNING: unrecognized options: --enable-jobinfo, --enable-jobinfo-slurm, --enable-papi-sampler, --enable-slurm-sampler, --enable-hweventpapi, --with-libpapi

All the dependencies should be installed, as well as papi and sos.

Please advise.
Thanks

**Comment by tom95858** [comment]
I think these are harmless warnings. There has been some configuration changes and the README.md/examples may be out of data.

**Comment by trecakov** [comment]
Thanks
