### ISSUE TITLE
permissions not quite honored

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#632]
I'm running a test where if the set has defaulted perms (-v shows rr- / 440) and the daemon is accepting auth=none connections, I get back results from ldms_ls. (this is as expected). All is running as root in a test cluster).
If I enable auth=munge, then (when running both ldms_ls and ldmsd as root) I get no results back from ldms_ls. This is unexpected.
If I extend the test config to include non-default perm=666 on the sampler, then ldms_ls does work as expected (shows results).

This is using the OVIS-4 tip with the recent seteuid patch.
Is this a bug or an operator confusion about the permissions model?

**Comment by tom95858** [comment]
It should have nothing to do with seteuid since that doesn't control whether or not a set is visible. That said, I'm going to revert the seteuid patch, I don't think it is necessary and is causing confusion.

**Comment by baallan** [comment]
No need to revert the seteuid patch on account of this problem. I suspect the two are independent, since I'm running everything in the test as root. I would expect the seteuid patch to be inactive based on its if tests.

**Comment by morrone** [comment]
I am also running tests with munge and root for both ldms_ls and ldmsd, with 0440 perms, but I am not seeing the problem that you are reporting. I am also on the tip of OVIS-4.

Maybe you could provide more details about your setup?

**Comment by baallan** [comment]
@morrone execution details from munge/perm problem:

```
# ps output of the 2 daemons (_ls works on daemon 1 (port 61079) but not on 2 (port 61080)
root      46523  0.0  0.0 117368  2772 ?        Ssl  15:16   0:00 ldmsd.61079 -x sock 61079 localhost -c /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/run/conf.1 -l /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/logs/1.txt -v DEBUG -r /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/run/ldmsd.pid.1
root      46552  0.0  0.0 119460  2796 ?        Ssl  15:16   0:00 ldmsd.61080 -x sock 61080 localhost -c /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/run/conf.2 -l /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/logs/2.txt -v DEBUG -a munge -r /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/run/ldmsd.pid.2

ldms_ls on host 1:
ldms_ls  -h localhost -x sock -p 61079 -v
Schema         Instance                 Flags  Msize  Dsize  UID    GID    Perm       Update            Duration          Info    
-------------- ------------------------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
opa2           localhost1/hfi1_0/1         CL     856    136      0      0 -r--r----- 1613686570.001242          0.000174 "updt_hint_us"="1000000:0" 
-------------- ------------------------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
Total Sets: 1, Meta Data (kB): 0.86, Data (kB) 0.14, Memory (kB): 0.99
ldms_ls on host 2:
ldms_ls  -h localhost -x sock -p 61080 -v -a munge
Schema         Instance                 Flags  Msize  Dsize  UID    GID    Perm       Update            Duration          Info    
-------------- ------------------------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
# lack of data here is the problem 


# ps output to verify euid/egid of daemons
  PID  EUID  RUID  SUID  EGID  RGID  SGID CMD
 46523     0     0     0     0     0     0 ldmsd.61079 -x sock 61079 localhost -c /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/run/conf.1 -l /ascldap/users/baallan/ovis-i
   PID  EUID  RUID  SUID  EGID  RGID  SGID CMD
 46552     0     0     0     0     0     0 ldmsd.61080 -x sock 61080 localhost -c /ascldap/users/baallan/ovis-ibnet/ldmstest/opa2/run/conf.2 -l /ascldap/users/baallan/ovis-i

ldms_ls on host 3:
ldms_ls  -h localhost -x sock -p 61081 -v -a munge
Schema         Instance                 Flags  Msize  Dsize  UID    GID    Perm       Update            Duration          Info    
-------------- ------------------------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
```

The sampler daemon config file is below. If I flip the comment on the 2 config lines, then ldms_ls works for both daemons.
```
load name=${plugname}
config name=${plugname} producer=localhost${i} schema=${testname} instance=localhost${i}/${testname} component_id=${i}
#config name=${plugname} producer=localhost${i} schema=${testname} instance=localhost${i}/${testname} component_id=${i} perm=666
start name=${plugname} interval=1000000 offset=0
```

All the above is generated using a lightly modified version of the opa2 input scripts for ldms-static-test.sh. the mods introduce the use of "-a munge" In the ps output of ldmsd lines, you'll notice that the : have been replaced with " " in the -x argument by our getopt code.

**Comment by morrone** [comment]
I'm not entirely sure that I follow this example. You talk about "host 1" and "host 2", but are these really running on different hosts or on the same host? I think maybe you are just using the wrong term there, and really this is all running on the same host? Just different ldmsd daemon instances running on different ports?

And you talk about "host 3", which uses a third port, but I'm not sure that you told us anything about what daemon was running on port 61081, so I don't know that we can make anything out of that.

Are you absolutely certain that cont.1 and conf.2 are the same? And are you certain all of the variables for daemon 2's config are correctly filled in? A misconfigured plugin would also explain what you are seeing.

Did you see anything different in the log files between the two daemons?

**Comment by baallan** [comment]
I can send you the tar of the complete output tree; I shouldn't post it here. 
'host' means daemon instance; they are all on the same host.
I didn't paste the startup line of the 3rd (agg) daemon into the message, because it is behaving the same as daemon 2 wrt _ls.
I ran diff on the two conf files; same except for comment headers. They are generated from the same 'prolog.sampler'.
The only significant difference in the two logs is where each says "listening on ....'' we get the expected none or munge for auth plugin echoed.

**Comment by morrone** [comment]
I can't reproduce the problem with a simple meminfo test that I created.

My recommendation would be to whittle down the complexity of the example until you have a simpler reproducer, or perhaps until the problem goes away and that might point to a problem with the last thing that was whittled away.

**Comment by tom95858** [comment]
. . . 
> ldms_ls on host 1:
> ldms_ls  -h localhost -x sock -p 61079 -v
> Schema         Instance                 Flags  Msize  Dsize  UID    GID    Perm       Update            Duration          Info    
> -------------- ------------------------ ------ ------ ------ ------ ------ ---------- ----------------- ----------------- --------
> opa2           localhost1/hfi1_0/1         CL     856    136      0      0 -r--r----- 1613686570.001242          0.000174 "updt_hint_us"="1000000:0" 

This says that the set cannot be viewed if they are not root or in the root group. Running as "none" everyone is root:root. Running as munge, your are baallan:baallan.

I believe that the code working as expected.
