### ISSUE TITLE
Validating incoming ldmsd requests

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#637]
Maybe I'm missing something, but at first read it does not appear that we are correctly validating incoming requests in the ldmsd.

For instance, when we are iterating through the attributes in the request, we call "ldmsd_next_attr()" a number of time. This function seems to blindly trust the attr_len in each of the attr structures. How do we know that attr_len is not incorrect, and directing the code to jump beyond the end of the entire request buffer?

Similarly, inside of an ldmsd_req_attr_t, when handlers access the attribute value as a string, they seem to just assume that the string will end in a null character within the the limits that attr_len and the enclosing request buffer should proscribe. Is there anywhere that I am missing that tests that assumption?

**Comment by tom95858** [comment]
I think you are correct. We should be validating that the attr_len in the attribute does not run past the end of req->len. We should also ensure that the strings (which they all are) are null terminated, i.e. attr->u8_value[attr->len] == '\0' or something like that.

BTW, I spent a few days creating a v2 configuration protocol. This protocol marshals the messages into and out of structures that are passed to each handler already parsed. This puts all of the parsing in one place and removes that code from each handler. I'll post that as a WIP for review of the general approach.

**Comment by morrone** [comment]
At least in concept that would be so much better!

**Comment by tom95858** [comment]
Resolved by commit eae6298341f204aed1768cc97adb0e21c139facf

**Comment by morrone** [comment]
@tom95858, while there has been some progress in this area, I do not think this is resolved yet. In particular the issue that I raised in the initial comment hasn't been addressed. ldmsd_next_attr() still does no validation. This will take a little more reworking to fix because that function probably doesn't have enough information when it is called to validate the sizes.

**Comment by tom95858** [comment]
@nick-enoent, could you please add the relevant check to ldmsd_attr_next(). Somehow I missed this when I reviewed the code. I know we discussed it when we were talking about doing this validation.

@morrone, I believe that we can add an additional check in the ldmsd_attr_first, ldmsd_attr_next functions that ensure that attr + attr->len does not extend beyond the end of the message. This will avoid adding these checks all over the place.

**Comment by morrone** [comment]
Perhaps ldmsd_attr_first() could walk the whole set of attributes, avoiding the need for the ldmsd_attr_next() to validate.

We also need to make sure the the attr is null terminated within the len, not just that the len value is correct.

**Comment by tom95858** [comment]
We could also validate the request upon receipt before ldmsd_attr_first is even called.

**Comment by morrone** [comment]
Yes!

**Comment by nick-enoent** [comment]
@tom95858 Sure thing, I'll take a look at it today.

**Comment by tom95858** [comment]
@morrone is this resolved?
