### ISSUE TITLE
ldms_ls in 4.x beta releases broken

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#66]
When using ldms_ls from 4.2 on a 4.3 daemon instance, no error is issued.
It should ldms_ls in both versions should detect and complain at the user that the server is not compatible.

Rather, a bunch of binary is dumped followed by a partial json-ish string, for example:

irectory" : [ {"name":"twain/vmstat","schema":"vmstat","flags":"CL ","meta_size":5600,"data_size":1032,"uid":0,"gid":0,"perm":"-rwxrwxrwx","card":123,"array_card":1,"meta_gn":2,"data_gn":7923,"timestamp":{"sec":1571436133,"usec":1978},"duration":{"sec":0,"usec":237},"info":[{"key":"updt_hint_us","value":"1000000:0"}]},{"name":"twain/procstat","schema":"procstat","flags":"CL ","meta_size":1432,"data_size":920,"uid":0,"gid":0,"perm":"-rwxrwxrwx","card":32,"array_card":1,"meta_gn":2,"data_gn":6999,"timestamp":{"sec":1571436133,"usec":1602},"duration":{"sec":0,"usec":63},"info":[{"key":"updt_hint_us","value":"1000000:0"}]},{"name":"twain/procnetdev","schema":"procnetdev","flags":"CL ","meta_size":1648,"data_size":328,"uid":0,"gid":0,"perm":"-rwxrwxrwx","card":35,"array_card":1,"meta_gn":2,"data_gn":2115,"timestamp":{"sec":1571436133,"usec":1614},"duration":{"sec":0,"usec":115},"info":[{"key":"updt_hint_us","value":"1000000:0"}]},{"name":"twain/meminfo","schema":"meminfo","flags":"CL ","meta_size":2024,"data_size":432,"uid":0,"gid":0,"perm":"-rwxrwxrwx","card":48,"array_card":1,"meta_gn":2,"data_gn":2973,"timestamp":{"sec":1571436133,"usec":1889},"duration":{"sec":0,"usec":366},"info":[{"key":"updt_hint_us","value":"1000000:0"}]}]}

**Comment by ovis-hpc** [comment]
The minor version bump to enable the check is pushed in 4.3.3 as discussed at LDMSCON

**Comment by baallan** [comment]
So that bump has still not hit github? I see nothing beyond 4.2.x in the branches. Just want to make sure I'm not missing something, not trying to rush a 4.3.3 release.

**Comment by oceandlr** [comment]
Yes. The 4.3.3. push to GitHub is imminent.

**Comment by ovis-hpc** [comment]
Now pushed
