### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [ovis-hpc/ovis#670]
[jw@cn06 build]$ make VERBOSE=1 -j$(nproc)
make  all-recursive
make[1]: Entering directory '/data/jw/ovis/build'
Making all in lib
make[2]: Entering directory '/data/jw/ovis/build/lib'
Making all in src
make[3]: Entering directory '/data/jw/ovis/build/lib/src'
Making all in third
make[4]: Entering directory '/data/jw/ovis/build/lib/src/third'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/third'
Making all in ovis_util
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_util'
  CC       util.lo
../../../../lib/src/ovis_util/util.c: In function 'ovis_strerror':
../../../../lib/src/ovis_util/util.c:1000:19: error: 'sys_nerr' undeclared (first use in this function)
 1000 |  if (e >=0 && e < sys_nerr)
      |                   ^~~~~~~~
../../../../lib/src/ovis_util/util.c:1000:19: note: each undeclared identifier is reported only once for each function it appears in
../../../../lib/src/ovis_util/util.c:1001:10: error: 'sys_errlist' undeclared (first use in this function)
 1001 |   return sys_errlist[e];
      |          ^~~~~~~~~~~
make[4]: *** [Makefile:672: util.lo] Error 1
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_util'
make[3]: *** [Makefile:576: all-recursive] Error 1
make[3]: Leaving directory '/data/jw/ovis/build/lib/src'
make[2]: *** [Makefile:505: all-recursive] Error 1
make[2]: Leaving directory '/data/jw/ovis/build/lib'
make[1]: *** [Makefile:624: all-recursive] Error 1
make[1]: Leaving directory '/data/jw/ovis/build'
make: *** [Makefile:532: all] Error 2
[jw@cn06 build]$

**Comment by baallan** [comment]
@LutzWeischerFujitsu  please also provide the version of gcc you are using.

**Comment by baallan** [comment]
It appears this is likely related to:
https://bugzilla.redhat.com/show_bug.cgi?id=1856765

**Comment by baallan** [comment]
I have created a patch #671 which resolves this (and the warning from ld in older versions about using sys_errlist).

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 jw]$ gcc --version
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[jw@cn06 jw]$ 

Thanks. Installing mgetty didn't solve it. Please notify when the master is updated.

**Comment by baallan** [comment]
This has been fixed at the tip of OVIS-4 by #672

**Comment by LutzWeischerFujitsu** [comment]
(base) [jw@cn06 build]$ make VERBOSE=1 -j1
make  all-recursive
make[1]: Entering directory '/data/jw/ovis/build'
Making all in lib
make[2]: Entering directory '/data/jw/ovis/build/lib'
Making all in src
make[3]: Entering directory '/data/jw/ovis/build/lib/src'
Making all in third
make[4]: Entering directory '/data/jw/ovis/build/lib/src/third'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/third'
Making all in ovis_util
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_util'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_util'
Making all in coll
make[4]: Entering directory '/data/jw/ovis/build/lib/src/coll'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/coll'
Making all in mmalloc
make[4]: Entering directory '/data/jw/ovis/build/lib/src/mmalloc'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/mmalloc'
Making all in ovis_auth
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_auth'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_auth'
Making all in ovis_event
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_event'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_event'
Making all in ovis_ev
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_ev'
make[5]: Entering directory '/data/jw/ovis/build/lib/src/ovis_ev'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_ev'
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_ev'
Making all in zap
make[4]: Entering directory '/data/jw/ovis/build/lib/src/zap'
Making all in .
make[5]: Entering directory '/data/jw/ovis/build/lib/src/zap'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/data/jw/ovis/build/lib/src/zap'
Making all in sock
make[5]: Entering directory '/data/jw/ovis/build/lib/src/zap/sock'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/data/jw/ovis/build/lib/src/zap/sock'
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/zap'
Making all in ovis_ctrl
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_ctrl'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_ctrl'
Making all in ovis_json
make[4]: Entering directory '/data/jw/ovis/build/lib/src/ovis_json'
make  all-recursive
make[5]: Entering directory '/data/jw/ovis/build/lib/src/ovis_json'
make[6]: Entering directory '/data/jw/ovis/build/lib/src/ovis_json'
make[6]: Nothing to be done for 'all-am'.
make[6]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_json'
make[5]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_json'
make[4]: Leaving directory '/data/jw/ovis/build/lib/src/ovis_json'
make[4]: Entering directory '/data/jw/ovis/build/lib/src'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/data/jw/ovis/build/lib/src'
make[3]: Leaving directory '/data/jw/ovis/build/lib/src'
make[3]: Entering directory '/data/jw/ovis/build/lib'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/data/jw/ovis/build/lib'
make[2]: Leaving directory '/data/jw/ovis/build/lib'
Making all in ldms
make[2]: Entering directory '/data/jw/ovis/build/ldms'
Making all in src
make[3]: Entering directory '/data/jw/ovis/build/ldms/src'
Making all in third-plugins
make[4]: Entering directory '/data/jw/ovis/build/ldms/src/third-plugins'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/ldms/src/third-plugins'
Making all in core
make[4]: Entering directory '/data/jw/ovis/build/ldms/src/core'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/data/jw/ovis/build/ldms/src/core'
Making all in ldmsd
make[4]: Entering directory '/data/jw/ovis/build/ldms/src/ldmsd'
Making all in .
make[5]: Entering directory '/data/jw/ovis/build/ldms/src/ldmsd'
  CCLD     ldmsd
/usr/bin/ld: ldmsd-ldmsd_auth.o:/data/jw/ovis/build/ldms/src/ldmsd/../../../../ldms/src/ldmsd/ldmsd_auth.c:113: multiple definition of `cfgobj_trees'; ldmsd-ldmsd_cfgobj.o:/data/jw/ovis/build/ldms/src/ldmsd/../../../../ldms/src/ldmsd/ldmsd_cfgobj.c:95: first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:781: ldmsd] Error 1
make[5]: Leaving directory '/data/jw/ovis/build/ldms/src/ldmsd'
make[4]: *** [Makefile:1044: all-recursive] Error 1
make[4]: Leaving directory '/data/jw/ovis/build/ldms/src/ldmsd'
make[3]: *** [Makefile:600: all-recursive] Error 1
make[3]: Leaving directory '/data/jw/ovis/build/ldms/src'
make[2]: *** [Makefile:577: all-recursive] Error 1
make[2]: Leaving directory '/data/jw/ovis/build/ldms'
make[1]: *** [Makefile:650: all-recursive] Error 1
make[1]: Leaving directory '/data/jw/ovis/build'
make: *** [Makefile:537: all] Error 2
(base) [jw@cn06 build]$

**Comment by baallan** [comment]
@tom95858  in ldmsd_auth.c we need
extern struct rbt *cfgobj_trees[]; instead of a redefinition.
A better solution would be to properly header cfgobj_trees and then remove the 5 redefinitions.

**Comment by baallan** [comment]
@LutzWeischerFujitsu please locally modify ovis/ldms/src/ldmsd/ldmsd_auth.c:113 so it reads
extern struct rbt *cfgobj_trees[];
and continue the build so you can tell us what else your compiler version is trapping that ours is not.

**Comment by LutzWeischerFujitsu** [comment]
Than all works. :-)
