### ISSUE TITLE
Changes coming to GitHub!

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#68]
Changes discussed at LDMSCON2019 are being rolled out!
* 11/4: Mainline development on v4 is master, with 4.x releases tagged as usual. The first v4 push to master has occurred and the first new tag is 4.3.3-beta
* Contrib directory set up is slightly different than that proposed at LDMSCON. contrib directory will be at the same level as sampler and store and not subdirectories of sampler and store. The push and the revision of the documentation will come after 4.3.3

**Comment by morrone** [comment]
master is now behind v4 development...it looks like OVIS-4.3-latest was made for v4 development instead.  Which approach are we going with?

**Comment by narategithub** [comment]
Oops. I'm sorry I forgot to update master and OVIS-4.3-beta. Now, OVIS-4.3-latest, OVIS-4.3-beta and master are the same.

**Comment by andyw-lala** [comment]
Thanks - much appreciated !
