### ISSUE TITLE
ldms packaging plan

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#69]
The [wiki describes](https://github.com/ovis-hpc/ovis/wiki/DirChanges-v3-to-v4) how in ovis v3, LDMS, baler, and sos were all under one project, but as of ovis v4, LDMS, Baler, and SOS are independent projects.

What impact (if any) is this planned to have on the approach to packaging?  Will LDMS move to having package names that start with "ldms", or is the project sticking with ldms packages being named "ovis"?

Whatever the plan, I think it would be very good to start uploading canonical tarballs of each release to github.  The tarball would be the result of running "make dist" on the project.

**Comment by baallan** [comment]
We don't expect major changes to packaging v4 other than sos and baler would be in their own rpms and ldms (and lib) will continue in the ovis-* rpm names. The packaging scripts themselves will be moving to ovis-hpc/distribution from baallan/distribution as soon as I have finished up the non-genders cray rpm specs for distribution/cle*.

There is no canonical tar ball because the result of make dist depends on configure which depends heavily on platform.

**Comment by morrone** [comment]
There really shouldn't _be_ "packaging scripts".  I should just be able to write a sane .spec file that will build the ldms canonical tarball.

I'll drop the "v4" part of this ticket.  Lets just discuss where we want to go with the build system of ldms.

I think it would be a good idea to move ldms into its own repository like sos and baler.

ldms should have its own, clean, single build system (no recursive calls into sub-project autogen/configure, etc.).

Can we move in that direction in a reasonable time frame?

**Comment by baallan** [comment]
Eliminating the separation of ovis/lib/configure.ac from ovis/ldms/configure.ac would be a fine start.
There seems to be some historically based aversion to this simplification, but I've never managed to find out where it originates. 
To the best of my knowledge, there is no other project that depends on ovis/lib. For example, baler and sos have their own support 'classes' which in some cases are clones (or divergent clones) of ovis/lib classes.

**Comment by morrone** [comment]
OK, great to know!  I was afraid that there needed to be an ovis-lib project that the other projects could build against.  But if ovis/lib can just be relocated under ovis/ldms that makes things even easier.

**Comment by baallan** [comment]
I think without much loss of sanity we could easily move ovis/lib/src/* to ovis/ldms/src/*, but maybe there's an alternate product roadmap for ovis/lib that I've missed. This would cut the amount of exported configuration trivia for 3rd party use in half.

**Comment by morrone** [comment]
Dropping this ticket.

**Comment by baallan** [comment]
Thanks for all your contributions that made dropping this ticket practical, btw!
