### ISSUE TITLE
Failover Not Working

### ISSUE THREAD

**Issue by Snell1224** [ovis-hpc/ovis#696]
Following the [Two Aggregators Configured as Failover Pairs](https://github.com/ovis-hpc/ovis-wiki/wiki/QuickStart-%28v4%29#Two_Aggregators_Configured_as_Failover_Pairs)  instructions and environment (without the authentication), I created an example failover to help understand how the aggregators are configured.

I was able to aggregate both host1 (nid00046) and host2 (nid00047) from each agg11.conf and agg12.conf files, respectively and the failover worked when killing agg11 and running ldms_ls for agg12 (both host1 and host2 appeared). 

However, when killing agg12 and running ldms_ls on agg11, I only received the data from host1 (nid00046) and the /tmp/demo_ldmsd_log file showed a “Failover pairing error: 1”.

I also added an -r pid file to the end of the ldmsd for agg11.conf but that didn’t seem to help or make a difference.

Below are the instructions ran:
```> ldmsd -x sock:10445 -c agg11.conf -l /tmp/demo_ldmsd_log -v ERROR -n agg11
> ldmsd -x sock:10446 -c agg12.conf -l /tmp/demo_ldmsd_log -v ERROR -n agg12
> ps auwx | grep ldmsd | grep -v grep
spwalto   1973  0.0  0.0 532704  5048 ?        Ssl  15:00   0:00 ldmsd -x sock 10445 -c agg11.conf -l /tmp/demo_ldmsd_log -v ERROR -n agg11
spwalto   5448  0.0  0.0 532708  5068 ?        Ssl  15:00   0:00 ldmsd -x sock 10446 -c agg12.conf -l /tmp/demo_ldmsd_log -v ERROR -n agg12
> kill 1973
> ldms_ls -h localhost -x sock -p 10446
nid00047/vmstat
nid00047/meminfo
nid00046/vmstat
nid00046/meminfo
**successfully getting the stats from host1 (nid00046)**
> ldmsd -x sock:10445 -c agg11.conf -l /tmp/demo_ldmsd_log -v ERROR -n agg11
> kill 5448
> ldms_ls -h localhost -x sock -p 10445
nid00046/vmstat
nid00046/meminfo
**failed to get the stats from host2 (nid00047)**
> cat /tmp/demo_ldmsd_log
Tue Apr 20 14:45:55 2021: ERROR     : Existing pid file named '/var/run/ldmsd.pid': overwritten if writable
Tue Apr 20 14:45:55 2021: ERROR     : Could not open the pid file named '/var/run/ldmsd.pid': Permission denied
Tue Apr 20 14:47:08 2021: ERROR     : Existing pid file named 'pid.pid': overwritten if writable
Tue Apr 20 14:47:08 2021: ERROR     : Existing banner file named 'pid.pid.version': overwritten if writable
Tue Apr 20 14:47:08 2021: ERROR     : Failover pairing error: 1
Tue Apr 20 14:47:09 2021: ERROR     : Failover pairing error: 1
….

**Comment by tom95858** [comment]
@narategithub can you take a look at this?

**Comment by narategithub** [comment]
@Snell1224 Can I see agg11.conf and agg12.conf? rc 1 is `EPERM`. I'm suspecting that the daemon name in the config file and the name given at the CLI might not match.

**Comment by Snell1224** [comment]
> @Snell1224 Can I see agg11.conf and agg12.conf? rc 1 is `EPERM`. I'm suspecting that the daemon name in the config file and the name given at the CLI might not match.

agg11.conf:
```prdcr_add name=nid00046 host=nid00046 type=active xprt=sock port=10444 interval=20000000
prdcr_start name=nid00046
updtr_add name=policy_h1 interval=1000000 offset=100000
updtr_prdcr_add name=policy_h1 regex=.*
updtr_start name=policy_h1
failover_config host=localhost port=10446 xprt=sock type=active interval=1000000 peer_name=agg12 timeout_factor=2
failover_start
```

agg12.conf:
```prdcr_add name=nid00047 host=nid00047 type=active xprt=sock port=10444 interval=20000000
 prdcr_start name=nid00047
 updtr_add name=policy_all interval=1000000 offset=100000
 updtr_prdcr_add name=policy_all regex=.*
 updtr_start name=policy_all
 failover_config host=localhost port=10446 xprt=sock type=active interval=1000000 peer_name=agg12 timeout_factor=2
 failover_start
```

**Comment by narategithub** [comment]
In `agg12.conf`, `failover_config` `peer_name` should be `agg11`.

**Comment by Snell1224** [comment]
Oh! Did not notice that. 
Changed the peer_name and the failover worked! Thank you!
