### ISSUE TITLE
ovis-lib directory not created in OVIS-4

### ISSUE THREAD

**Issue by vsurjadidjaja** [ovis-hpc/ovis#714]
The /Build/OVIS-4/lib/ovis-lib directory is not created when using OVIS-4 (specifically when following the install instructions on the wiki's QuickStart page).

**Comment by baallan** [comment]
It's not expected to be. The pkglibdir definition (where most of the plugins live) is $libdir/$PACKAGE where package is ovis-ldms, from the top directory's configure.ac. 
The prior existence of lib/ovis-lib was an artifact of the old build system that had multiple configure.ac files; these were unified into the top level configure.ac.
Any documentation or scripts mentioning lib/ovis-lib should be corrected.
