### ISSUE TITLE
Build process for subdir change?

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#720]
Did the build process for subdirectories change? I had errors building the Cray System Sampler which all looked like handling of subdirs?

**Comment by bschwal** [comment]
I am also getting a similar issue but after building. I'm trying to load app_sampler and it is looking for the library in lib64 which does not exist. Is that a sampler specific thing?

**Comment by tom95858** [comment]
I think this became borked when they upgraded Voltrino. Have no build issue on any other platform.

**Comment by tom95858** [comment]
What's the status here? Can we close this?

**Comment by bschwal** [comment]
I think @oceandlr is still having voltrino build issues, I think it is a system specific issue though. I haven't tried to build elsewhere yet.

**Comment by oceandlr** [comment]
I will try again. At one point ovis-4.3.8-fixes and OVIS-4 had diverged. What am I supposed to be using now?

**Comment by tom95858** [comment]
@oceandlr can you please confirm that we have an issue or close this? Thanks.
