### ISSUE TITLE
Missing canonical tarball

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#77]
ovis/ldms is missing a canonical tarball.  This is a bug.

I understand that the rationale given for this is: " There is no canonical tar ball because the result of make dist depends on configure which depends heavily on platform." However, I think it is a mistake to think that because there are different platforms with different configurations, there cannot be a single canonical tarball.

I think I understand where this idea might come from.  In order to be able to run "make dist", you need to both bootstrap the autotools system _and_ run the configure script.  It is necessary to run configure because that is how the Makefiles are generated.  The "make dist" command doesn't exist until the Makefiles exist. So one might reasonably suspect that "make dist" creates a tarball customized by a bunch of the decisions and command line options given to ./configure before "make dist" was called.  But this is not the case.

The tarball created by "make dist" contains _all_ of the source code, and a copy of the configure script.  There are no Makefiles in the dist tarball (only the *.in and *.am precursors), and this is because no configuration decisions have been made yet!

So almost all options given at the configuration time before the tarball was created are irrelevant.  It is only the configuration options given to the configure script in the _tarball_ that matter for differentiating the target build.

Granted, the initial configure-before-make-dist seems a little chicken-and-egg, and that is because it really is.  But there is almost no way around that issue, so autotools users just make peace with that.

So if the automatic tests and configuration options from the pre-make-dist run of configure don't matter, one might wonder why we should suffer through them at all.  After all, if we just want to run "make dist" to make the canonical tarball, none of the configure options will matter anyway, so being thwarted by a missing dependency is just annoying.  So many projects decide to add a configure option to bypass most checks and just allow enough of configure to run to generate the Makefiles.  Often this option is called "--enable-dist".  This is what the Linux kernel does, for instance.

So hopefully it is clear that a canonical tarball is entirely possible for ovis/ldms.  Getting a canonical tarball support will better align ldms with standard build practices, and will be an important step in improving the build and packaging experience.

**Comment by morrone** [comment]
PR #83 will get us much closer to a repaired make-dist canonical tarball.

**Comment by baallan** [comment]
"The tarball created by "make dist" contains all of the source code,"
This has not been the case for every previous version of autotools the project experienced.
If it is accurate for am 1.13 and all later, we should certainly be moving in the direction @morrone advocates. We need adequate multiplatform testing stood up to prove it.

**Comment by morrone** [comment]
I can't really speak to your experience in the past. The use of "make dist" to generate a canonical tarball is something we have employed, and seen employed, across many projects and years.

There are certainly occasional quirks and bugs that need to work around (it is pretty complex in its own right). I stumbled on one in my PRs that are currently pending for LMDS.  It turns out that things like "_SOURCES" inside of automake conditionals work as expected: the program/library is built condionally, but the source files are _always_ included in the dist.  There is a known bug where they overlooked doing the same for _MANS lines, so an explicit EXTRA_DIST is needed for any man pages that are inside of conditionals.

> We need adequate multiplatform testing stood up to prove it.

I don't think that is really necesary.  I am looking to change the the dist tarball, not the actual compilation path.  The platform where the official packaging person works just needs to have a relatively modern set of autotools (with in several years is probably sufficient, because RHEL/CentOS doesn't exactly have the latest tools usually, and those are plenty modern for this task).

That person just needs to do what I am doing:

1) use "git archive" to create a raw source tarball of some tag/branch
2) do "sh autogen.sh && ./configure && make dist" on same tag/branch
3) Unpack the tarballs from (1) and (2) next to each other in a directory
4) Run a recursive comparison of the contents of the two directories, e.g. "diff -r dir1 dir2"

But if they are reasonably the same, there is little reason to worry that the dist tarball would fail to build where the git checkout would succeed.

This comparison is not a common exercise.  We just need to be doing that now while we get the dist tarball in good shape.  Once that is done, the recursive diff comparison exercise is not something that we would expect to do very often in the future.  Partly this because once the canonical tarball exists, it will start getting usage and be less likely for rot to develop.  Also, code reviewers will learn to recognize issues that effect the dist over time as bugs are reported, so that also helps reduce extra work.

In the end, I think it will make the code easier to work with, and require less effort to  build, test, and package.

That said, it certainly wouldn't hurt to build the dist tarball on multiple platforms.  More testing isn't bad as long as it isn't going to result in long delays.

**Comment by baallan** [comment]
historical note: There have been enough ridiculous breakages/inconsistencies over the years in automake's 'make dist' (including the current man pages hack-around that you just rediscovered) that we took the conservative double-configure approach. It just adds time to robots that build packages robustly, rather than making the .am files a pile of messy workarounds. 

I mentioned adequate multiplatform testing because we are strongly not allowed to break the autogen and build process on bluewaters, which has a legacy cray environment.

**Comment by morrone** [comment]
This is resolved, at least for the OVIS-4 branch, by the landing or PR #316.
