### ISSUE TITLE
Potential error(e.g., deadlock ) due to the unreleased lock (CWE-667)

### ISSUE THREAD

**Issue by jenny-cheung** [ovis-hpc/ovis#772]
Dear developers, thank you for your checking! It seems that the lock `&lset->lock` may not be released correctly if the method  `int __process_dir_set_info` returns in the below two branches. Should it be a real bug? I think the fix is to insert `pthread_mutex_unlock(&lset->lock);` before returning.

https://github.com/ovis-hpc/ovis/blob/84513760731014c170104ff11608867b62096b58/ldms/src/core/ldms_xprt.c#L1686
https://github.com/ovis-hpc/ovis/blob/84513760731014c170104ff11608867b62096b58/ldms/src/core/ldms_xprt.c#L1692

```
static int __process_dir_set_info(struct ldms_set *lset, enum ldms_dir_type type,
				ldms_dir_set_t dset, json_entity_t info_list)
{
	...;

	if (lset)
		pthread_mutex_lock(&lset->lock);
	for (j = 0, info_entity = json_item_first(info_list); info_entity;
	         ...;
		if (!dset->info[j].key)
			return ENOMEM;
		...;
		if (!dset->info[j].value)
			return ENOMEM;

		...;
	}
	if (lset) {
		pthread_mutex_unlock(&lset->lock);
		...;
	}
	return 0;
}
```

Best,

**Comment by baallan** [comment]
@tom95858 it appears the reporter's observation is correct and the fix we might apply is to have the early returns converted to a 'goto err' with the err label just before the final if (lset) and the final return converted to a 'return rc'.
Do you concur?
Also it looks like neither here nor the caller logs a nomem message, which should be fixed at the same time.

**Comment by jenny-cheung** [comment]
@baallan Thank you for your detailed reply and confirmation!
