### ISSUE TITLE
Potential error(e.g., deadlock ) due to the unreleased lock &set->lock (CWE-667)

### ISSUE THREAD

**Issue by jenny-cheung** [ovis-hpc/ovis#773]
Dear developers, thank you for your checking! It seems that the lock `&set->lock` may not be released correctly if the method `__send_lookup_reply` when the` !msg` is satisfied and the control flow goes to  `err_0` that does not release the lock &set->lock. Should it be a real bug? I think the fix is to insert `pthread_mutex_unlock(&set->lock);` in the branch of` !msg`.

https://github.com/ovis-hpc/ovis/blob/84513760731014c170104ff11608867b62096b58/ldms/src/core/ldms_xprt.c#L1274

The process is detailed as below.
```
static int __send_lookup_reply(struct ldms_xprt *x, struct ldms_set *set,
			       uint64_t xid, int more)
{
	...;
	pthread_mutex_lock(&x->lock); // acquire the lock x->lock first
	
	...;

	pthread_mutex_lock(&set->lock);  // acquire the lock set->lock
	...;
	if (!msg) {  // the condition may be satisfied
		rc = ENOMEM;
		goto err_0; // goto err_o mistakenly with unrelased the lock set->lock
	}

	...;
	pthread_mutex_unlock(&set->lock);
	...;
	if (zerr != ZAP_ERR_OK) {
		...;
		goto err_0; // correctly since the lock set->lock has been released
	}
	pthread_mutex_unlock(&x->lock);
	...;
	return 0;
 err_0:
	pthread_mutex_unlock(&x->lock); 
	return rc;
}
```

Best,

**Comment by baallan** [comment]
@tom95858 reporter's observation looks correct, and the proposed fix appears correct. Tracing where the error code goes, in at least some cases it appears enomem gets incorrectly mapped to a zap error string, so fixing the error reporting at the same time (if in a separate commit) would be helpful.

**Comment by jenny-cheung** [comment]
@baallan Thank you for your detailed reply and confirmation!

**Comment by baallan** [comment]
@jenny-cheung if you have time, please cherry pick the proposed changes from #775, #776 and rerun your lock analyses, then let us know if the problems are still there or have been replaced with another problem.

**Comment by jenny-cheung** [comment]
@baallan They are fixed now. Thanks~
