### ISSUE TITLE
Slurm notifier must call slurm_init

### ISSUE THREAD

**Issue by eric-roman** [ovis-hpc/ovis#782]
From the Slurm README:

```
 -- Due to internal restructuring ahead of the 20.11 release, applications
    calling libslurm MUST call slurm_init(NULL) before any API calls.
    Otherwise the API call is likely to fail due to libslurm's internal
    configuration not being available.
```

**Comment by morrone** [comment]
The merged commit says, "Addresses #782", so I am closing this issue.

FYI, github recognizes the keywords "fixes", "closes", and "resolves", but not "addresses" to the best of my knowledge.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
