### ISSUE TITLE
Missing documentation on wiki

### ISSUE THREAD

**Issue by oceandlr** [ovis-hpc/ovis#795]
@Snell1224 On the wiki there appear to be stub pages with no information (e.g., features and functionalities). What's the plan for these? Should they be removed until there is content?

**Comment by tom95858** [comment]
Yes, but my recollection was that someone was going to flesh these out as part of a comprehensive documentation of our testing.

**Comment by oceandlr** [comment]
This was in features and not in testing. you guys decide

**Comment by Snell1224** [comment]
@oceandlr I have removed the sub pages until the Test Plan has been approved in the R&A portal.

**Comment by tom95858** [comment]
@Snell1224  could you please either provide the appropriate documentation or close this issue?
