### ISSUE TITLE
Missing autoconf test for openssl/evp.h header

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#80]
Ovis v4 is missing an autoconf test for openssl/evp.h header:

```
make[5]: Entering directory '/home/morrone/src/ovis/lib/src/ovis_auth'
  CC       auth.lo
auth.c:57:10: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
          ^~~~~~~~~~~~~~~
```

**Comment by baallan** [comment]
Please submit a patch to fix configure.

**Comment by morrone** [comment]
Yes, I'll try to get back to that.  I just wanted to remember the issue after I installed the ssl devel package on my system. At first pass it was a little confusing because there are some things in place for ssl detection, but maybe they are in the wrong autoconf or something (like at the top level when it needs to be tested at the ldms level).  That will get easier to debug at things are cleaned up.

**Comment by morrone** [comment]
Just looked at this, and it may instead be that lib/src/ovis_auth is built unconditionally, where as openssl support is currently conditional.

**Comment by morrone** [comment]
lib/src/ovis_auth is conditionally built when ENABLE_OVIS_AUTH is set. But ENABLE_OVIS_AUTH just tells us what was wanted on the command line, it doesn't tell us if we have the needed dependencies.
