### ISSUE TITLE
Rename ibmad sampler to ibmad_sampler

### ISSUE THREAD

**Issue by tom95858** [ovis-hpc/ovis#822]
@morrone, the ibmad sampler name is confusing the automake tools because it's target (libibmad.so) has the same name as an OFA verbs library by the same name and on which it depends. In order to resolve this conflict and make the sampler naming more consistent it seems like we should rename this sampler ibmad_sampler.

When I say 'confusing', specifically, the initial build after 'make clean' works, but subsequent builds will fail with

    Making all in ibmad
    make[5]: Entering directory `/home/tom/work/ovis-pkg/ovis/build-opt-ovis/ldms/src/sampler/ibmad' 
    CC       libibmad_la-ibmad.lo
    CCLD     libibmad.la
    gcc: error: /home/tom/work/ovis-pkg/ovis/build-opt-ovis/ldms/src/sampler/ibmad/.libs/libibmad.so: No such file or directory
    gcc: error: ./.libs/libibmad.so: No such file or directory
    make[5]: *** [libibmad.la] Error 1

I think the issue occurs when the dependency checking decides that ibmad needs to be rebuilt, but believes that the
dependency is satisfies because /usr/lib64/libibmad.so is present, but ./libs/libibmad.so is not.

**Comment by tom95858** [comment]
@morrone,

> As a transition strategy, We could maybe make new copies of the plugins to plugins with the new names, and mark the previous ones deprecated.

You mean mark it as 'deprecated' in the man-page I presume. This would be trivial to implement in the RPM post-install hook, i.e. just create a link from the old-name to the new-name. Users who build from source would not see this in the make install output; and I think I prefer that.

**Comment by morrone** [comment]
> @morrone,
> This would be trivial to implement in the RPM post-install hook, i.e. just create a link from the old-name to the new-name. Users who build from source would not see this in the make install output; and I think I prefer that.

I think that this needs to happen in the ldms build system rather than in the rpm packaging system. This is a change that would break a person's configuration. That sort of thing generally needs to be handled by the developer rather than the packager.

But that isn't terribly hard to do either. I'll push a commit shortly.
