### ISSUE TITLE
auto interval doesn't work for dynamic set plugins

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#836]
Sets which are created dynamically by plugins have no way currently to get their ldmsd_set_update_hint_set called correctly.
this causes them to be not aggregated if auto interval control is active.

This affects the lustre plugins and other multiset plugins that create their sets after 'start $plugin interval=xxx' has occurred.
cause:
Currently, start sampler calls __sampler_set_info_add which loops over the set pointers of the plugin instance to call ldmsd_set_update_hint_set with the arguments from the 'start' command.

One solution would be to extend the struct ldmsd_sampler to include interval and offset (significantly teasing the plugin authors); another would be for the plugin_sampler_cb and oneshot_sample_cb to set the hint values for all sets on the plugin just before the sample call.

I can see arguments for either solution (and for others which would entail new structures in ldmsd.c).

**Comment by baallan** [comment]
example: lustre_client plugin has this problem on my cray.

**Comment by tom95858** [comment]
@baallan, i believe that this has been "fixed" by @nichamon. If this is not the case, please re-open. The issue was that these samplers were not calling ldmsd_set_register().

**Comment by baallan** [comment]
@tom95858 @nichamon I'm reopening this. adding set_register calls seems to have most samplers in order, but not the ibmad_sampler. If I run with the patch in #854 updt_hint_us still isn't set.

**Comment by baallan** [comment]
After @morrone most recent updates, this issue still exists for dynamic set creation processes exemplified by  ibmad_sampler.

**Comment by morrone** [comment]
> After @morrone most recent updates, this issue still exists for dynamic set creation processes exemplified by ibmad_sampler.

Like I said, I didn't expect that my change would effect this. But I _am_ seeing the hints on ibmad sampler metric sets. And it did look to me like the ldmsd_set_register() code tries to set this. So I guess we need to figure out what is different between your setup and mine.

Can you please share your configuration options?

**Comment by baallan** [comment]
If you're seeing hints, let me dig back through the plugin binaries and see if something unexpected happened in the test deployment update.

**Comment by morrone** [comment]
I think I see the problem. It works when one uses the plugin name "ibmad", but not when one uses the new "ibmad_sampler" plugin name. There is an assumption in the code that these names are the name, but that is not programmatically or systematically enforced. And we wanted to allow both in this particular case to allow transition.

A simple half-measure fix would be to change the name that the plugin reports in the ldmsd_set_register() call. That leaves the old name broken for hints, but the new one name will have working hints.

There are certainly ways to fix this programmatically instead that would work for both. The first solution that I have in mind would probably be too large and invasive to implement in a minor release. With a little planning, the new plugin API can (and should) avoid this problem altogether.

So maybe the half-fix is fine for now?

I will look a little more and see if a there is a reasonable way to support both names without the fix getting too large.

**Comment by baallan** [comment]
@morrone sampler config is:
```
config name=ibmad_sampler producer=$anon instance=$anon/ibmad_sampler component_id=$anon job_set=${host}/jobid perm=0644
start name=ibmad_sampler interval=60000000 offset=0
```
the sha from
git log ibmad_sampler.c
```
commit 4dc4a59f4f61bec516dca6425b34ae035f1f12f7
```
do you have another sha?

**Comment by baallan** [comment]
I would be fine with simply moving to ibmad_sampler and forgetting about ibmad. I don't know of any institution that actually deployed ibmad (except maybe llnl, which you can upgrade).

**Comment by baallan** [comment]
> I think I see the problem

I tried loading the sampler as 'ibmad' instead of ibmad_sampler and confirmed that it then gets the hints field populated.
