### ISSUE TITLE
Configuration file environment variable substitution in "listen" command regression on OVIS-4

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#863]
It looks like there has been a regression in the handling of "env" options in ldms config files on the OVIS-4 branch.

I have these line in a config file:

```
env HOSTNAME=$(/usr/bin/hostname -s)
listen host=${HOSTNAME}-hsi0 port=411 xprt=rdma auth=munge_domain0
```

When ldmsd tries to start up, we see the error:

```
Jan 07 11:19:56 butte9 ldmsd[172376]: Fri Jan 07 11:19:56 2022: ERROR     : xprt listen error, getaddrinfo(-hsi0, 411) error: -2
```

The HOSTNAME substitution appears to now evaluate to an empty string.

**Comment by morrone** [comment]
It appears that the following commit introduced this regression:

```
* 60d4a43c 2021-12-14 Support LDMSD cmd-line options in configuration files (#826)
```

**Comment by tom95858** [comment]
@nichamon can you please take a look at this.

**Comment by morrone** [comment]
It looks like it is not the "env" lines that are broken, instead it looks like substitutions on the "listen" command lines in the file are not happening. Substitutions are still happening for at least "config" and "start" commands.

**Comment by morrone** [comment]
PR #864 does appear to address this bug.
