### ISSUE TITLE
version on v4.3.8 still coming out as 4.3.7.213 

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#879]
with current git 2.30.1 in toss, the version computation seems to be broken.

config/git-version-gen as scripted in configure.ac  is returning a 4.3.7 dirty string instead.
When I try to run pieces of git-version-gen by hand i eventually get to an error message:
```
fatal: No annotated tags can describe 'a54ebb4dea84cbe4b6e1614ee9265ece01b85320'.
However, there were unannotated tags: try --tags.
```

I don't know if the issue is our release tag not quite as needed or if something has changed in the current git version supported on TOSS3.

**Comment by baallan** [comment]
@morrone @tom95858 the unexpected behavior of configure/version is leading to incorrectly named tar files and rpms.

**Comment by baallan** [comment]
@tom95858 @morrone 
After manually tagging a local clone with 'git tag OVIS-4.3.8 -m something' make dist now does the right thing; it appears v4.3.8 just needs the right release tagging on github. this hold for both 1.8 and 2.30 git versions.

**Comment by morrone** [comment]
Yes, it is broken with any version of git. I emailed Tom about that, and he said he would take care of it.

Not only does the tag need to be in the form "OVIS-<version>" (our agreed upon format), it also needs to be an _annotated_ tag. So "git tag -a OVIS-4.3.8". The commit message can be the release message.

**Comment by morrone** [comment]
We hit a build issue with the correct tag created. I submitted PR #880 to address the issue.

**Comment by baallan** [comment]
The retagged tree now builds tar & rpm as expected for me.
