### ISSUE TITLE
ibmad_sampler needs include or exclude option

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#896]
On our socketdirect hardware the ibmad sampler continuously provokes ibwarn messages (not controlled by ldmsd) as part of the samplers auto-discovery for ib ports.
If we want to stick with auto-discovery of interfaces that go up/down due to cable/switch issues, we need to be able to stop autodiscovery on interfaces that admin knows will never come up. This could be by listing interfaces of interest or of exclusion.

**Comment by baallan** [comment]
an example
```
647876038.866932: DEBUG     : ibmad_sampler sample() called
1647876038.878861: DEBUG     : ibmad_sampler ibmad_metric_create() st55/mlx5_1.1, base_lid=0
ibwarn: [121702] mad_rpc_open_port: client_register for mgmt 1 failed
1647876038.878967: ERROR     : ibmad_sampler: ERROR: Cannot open CA:mlx5_1 port:1, ERRNO: 93
1647876038.880460: DEBUG     : ibmad_sampler metric_tree_refresh() skipping non-active ca mlx5_2 port 1
1647876038.891980: DEBUG     : ibmad_sampler ibmad_metric_create() st55/mlx5_3.1, base_lid=xxx
ibwarn: [121702] _do_madrpc: recv failed: Connection timed out
ibwarn: [121702] mad_rpc: _do_madrpc failed; dport (Lid xxx)
1647876039.893177: DEBUG     : ibmad_sampler: pma_query_via() failed: ca_name=mlx5_3 port=1  0
```

**Comment by baallan** [comment]
@morrone should I be doing something to patch the problems? Admins like zero-config where possible, but they like samplers that don't fill their logs with cruft even more. Of course ideally they want both at the same time.

**Comment by morrone** [comment]
I am a little busy at the moment. I will probably get to it eventually, but I don't have a current time frame in mind. If you would like to work on it, I am not at all opposed to that.

**Comment by baallan** [comment]
#907 fixes this.
