### ISSUE TITLE
Consolidate configure.ac, lib/configure.ac and ldms/configure.ac into the top level configure.ac

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/ovis#93]
In PR #78, @baallan suggested

> I would prefer a PR that consolidates configure.ac, lib/configure.ac and ldms/configure.ac (and the attendant m4/ subdirs) all into the top level configure.ac

I am fully in favor of this plan.  My only question is what the timing would be for that change.

My current cleanup efforts have been in support of achieving the following goals in a near-term v4 tag (ideally before the end of 2019):

- Fix the dist tarball to include all source
- Cleanup the "make install" products (remove test_* binaries, etc.)

These changes will allow the release manger (whoever tags a release) to generate a canonical tarball for ovis/ldms that can be added to github.  Github allows attaching release products to releases at https://github.com/ovis-hpc/ovis/releases, just in case you aren't familiar with that.

With those changes, making a .spec file for TOSS (or any other rpm-based distro) will be much, much easier.  It won't require any unique-to-ovis scripts and procedures. Building rpms will just require the canonical tarball and a spec file.  These are the two things that the rpmbuild command needs to generate rpms.

In support of getting this done in the near term and into some v4 release, I have been trying to keep the changes as low impact as possible. I was thinking that the consolidation of all of the recursive autotools into one clean autotools tree would be seen as too much change for v4, and might be relegated to v5 or later.

But if folks agree that this larger change is acceptable for the v4 branch in the near future (before the end of the year), then I am certainly willing to work on that.

Let me know what you all think!

@tom95858, @oceandlr, @valleydlr

**Comment by baallan** [comment]
I would like to get our house (names of libraries, locations of libraries, number of configure scripts) in order before we leave beta so that anyone creating plugins against a post-beta (GA) v4 release will not have to rename libraries in their linker flags. There shouldn't be .so file name changes (other than possibly adding new .so files) for the life of v4.  

Unless @morrone is particularly enthused to do the details, I will create a PR for consolidating configure and removing the redundant build-info-export files that merging lib/ and ldms/ create now.

**Comment by morrone** [comment]
Are 4.1.x, 4.2.x all considered "beta"?  In other words, there have been no stable releases of v4 yet, only betas?

Well in that case, yes I am totally in favor of this reorganization now.

@baallan, feel free to work on a PR for the consolidation. If you find you can't get to that work soon, then just let me know and I am happy to help out and work on it.

**Comment by valleydlr** [comment]
@morrone @baallan 4.1.x was beta and 4.2.x was GA and has been stable for > 6 months. Since 4.3.x has been in testing for some time and is stable, I would like to minimize impact (and move to GA for SC19) by only merging in bug fixes and perhaps things like PR #88, and #72 that don't touch any core functionality. We can save the disruption of reorganizing and renaming (and such) for 4.4.x and beyond.

**Comment by morrone** [comment]
@valleydlr, is it possible to get a 4.4 out in a number of weeks?

**Comment by valleydlr** [comment]
@morrone What is the time sensitivity for the changes that your are proposing?

**Comment by morrone** [comment]
@valleydlr, we would really like to move from v3 to v4, and these changes would vastly improve our ability to build, package, and use v4.  Not having a working canonical tarball in v4 is an impediment to standard build and packaging procedures.  By getting the canonical tarball in place, and by cleaning up the install products of the tree, we bring ldms in line with the build practices of a great many other projects.  This means that packaging becomes quite a bit easier for people with experience in that area.  Ultimately, it can reduce the time needed by the current core team to work on packaging, because when the tree follows autotools and install conventions, distro packagers can handle the package creation themselves. For instance, when these cleanups are made it will then be much, much easier for LLNL staff to handle the TOSS .spec file, and get ldms v4 into TOSS. When ldms follows convention in this area, the resulting packaging complexity is reduced. We don't need to have a single person with ldms expertise assigned to packaging ovis. It is easy for someone else to step in and handle a packaging update when the expert is away on vacation.

I would like to see easy(ish) wins like this making it into ldms without a great deal of delay. I'm not too concerned about the version number that has these things cleaned up, I just hope we don't have to wait six months for them.

**Comment by valleydlr** [comment]
@morrone Thanks for the clarification. I am in complete agreement with this direction and share your goal of getting there as soon as possible. Lets look at the complexity of the changes required and try to come up with a target schedule for getting there.

**Comment by baallan** [comment]
@morrone Top level only configure patch has been landed in OVIS-4.
I do not anticipate having time immediately to port this to master.
