### ISSUE TITLE
Old TOSS branches - removal?

### ISSUE THREAD

**Issue by ovis-hpc** [ovis-hpc/ovis#98]
@baallan can old TOSS v2X branches be removed?

**Comment by baallan** [comment]
2.x branches prior to 2.4.8 can be removed.
2.4.8 is still referenced in TOSS repos.

**Comment by ovis-hpc** [comment]
@baallan I think you have the power to remove these branches. If you can't, let me know and I will do so (@oceandlr)

**Comment by baallan** [comment]
i'm not clear on removing a branch without removing the tag. please go ahead.
should keep the tags.
ben
Sent from a mobile device making my vt100 look positively genius

On Nov 17, 2019, at 3:41 PM, ovis-hpc <notifications@github.com> wrote:

﻿

@baallan<https://github.com/baallan> I think you have the power to remove these branches. If you can't, let me know and I will do so (@oceandlr<https://github.com/oceandlr>)

**Comment by ovis-hpc** [comment]
@baallan you can remove the branches in the GUI. Not sure what you want to do. I will leave them and close this and you can decide at your leisure.
