### ISSUE TITLE
update hint handling?

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/ovis#987]
Observation of L1 update hint:
```
loadavg        login1/loadavg      CR     608    160      0      0      0 -rw-r--r-- 1658159520.002038          0.000039 "updt_hint_us"="1000000:230000" 
loadavg        node1/loadavg                 CR     600    160      0      0      0 -rw-r--r-- 1658159460.001547          0.000071 "updt_hint_us"="1000000:230000" 
```

even though on L0 daemons

```
start name=loadavg interval=60000000 offset=0
```
and on L1:
```
updtr_add name=all_admin5 interval=1000000 offset=230000
updtr_prdcr_add name=all_admin5 regex=.*
updtr_start auto_interval=true name=all_admin5
```

It is true that many other sets present are collected at 1 hz rather than 1/minute.

**Comment by baallan** [comment]
@nichamon We have a situation (observable on shirley, etc with ldms_ls) that the L2 is trying to update at 1Hz even though the set is produced at 1/minute. We don't understand why the set interval and update hints & updates never sync at 1/minute.
This produces many oversample messages at the L2.
Logging on the production L1s is at ERROR, so we don't see the oversample infos there.

**Comment by baallan** [comment]
It occurs to me to wonder if this is related to #957  or #971

**Comment by tom95858** [comment]
Hi @baallan, @nichamon:

The cause is that there is a single updater in each of the L1 aggregators (all_ecadminX) for all metric sets. That updater is updating every 1.0s:230.0ms and is _not_ in auto mode. Therefore the set hint is ignored from the sampler and overwritten with the update interval at the L1.

Here's some output at ecadmin5 (L1) to demonstrate this...

```
root@shirley-admin# ldmsd_controller --host ecadmin5 --xprt sock --port 413 --auth ovis -A name=/opt/ovis/etc/ldms/ldmsauth.conf
Welcome to the LDMSD control processor                                   
sock:ecadmin5:413> updtr_status                                          
Name             Interval:Offset  Auto   Mode            State           
---------------- ---------------- ------ --------------- ------------    
all_ecadmin5     1.0s:230.0ms     false  Pull            RUNNING         
    ec1              ec1-ib0                   411 sock         CONNECTED
    ec10             ec10-ib0                  411 sock         CONNECTED
    ec11             ec11-ib0                  411 sock         CONNECTED
...
```
The simplest thing to do to fix this configuration error is to put the updater in Auto mode.

**Comment by baallan** [comment]
@tom95858 so how should
```
updtr_add name=all_admin5 interval=1000000 offset=230000
updtr_prdcr_add name=all_admin5 regex=.*
updtr_start auto_interval=true name=all_admin5
```
be corrected?

**Comment by tom95858** [comment]
Well, I don't know @baallan, but what is written there is not what is running. The updater name doesn't even match.

**Comment by tom95858** [comment]
I'm suggesting that you might not be running the config you think you are. My claim is not based on the syntax of any configuration file; I simply ran the command shown above and noted that the updater is not, in fact, running in auto mode as you claimed. Hint processing that is working fine and as expected. You could have tested  your config yourself using ldmsd_controller against any of the L1 aggs or your own test aggregator as I did below:

```
root@biffle1# ldmsd_controller --host localhost --port 10411 --auth munge
Welcome to the LDMSD control processor
sock:localhost:10411> updtr_add name=all_admin5 interval=1000000 offset=230000
sock:localhost:10411> updtr_prdcr_add name=all_admin5 regex=.*
sock:localhost:10411> updtr_start auto_interval=true name=all_admin5
sock:localhost:10411> updtr_status
Name             Interval:Offset  Auto   Mode            State
---------------- ---------------- ------ --------------- ------------
all_admin5       1.0s:230.0ms    true   Pull            RUNNING
    admin5_413     admin5                  413 sock         CONNECTED
    admin5_414     admin5                  414 sock         CONNECTED
    admin5_415     admin5                  415 sock         CONNECTED
    ...
```
Note that the updater is in auto mode as requested.

**Comment by valleydlr** [comment]
Hi Ben,

Please send me all files, generators and generated configuration files, that have anything to do with the running configurations on Eclipse admin nodes and compute nodes.

Thanks,
Jim
________________________________
From: Benjamin Allan ***@***.***>
Sent: Monday, July 18, 2022 1:17 PM
To: ovis-hpc/ovis ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [ovis-hpc/ovis] update hint handling? (Issue #987)


@tom95858<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftom95858&data=05%7C01%7Cbrandt%40sandia.gov%7C364675df4a2744245a6408da68fa9166%7C7ccb5a20a303498cb0c129007381b574%7C1%7C0%7C637937722644226196%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RLf5wWMfEnPLcawAJ%2BUaCu7IGYi57Kx6gQjPewE1G7M%3D&reserved=0> I anonymized the config names as i have management guidance to do.
Modulo names, that's the syntax that configures all the L1s, so if you're saying the option syntax is correct then there is a bug in either the option processing or something related. If you're saying its incorrect, please supply the correction.
thanks.

**Comment by baallan** [comment]
I should mention eclipse is running ldms@78649 (march 10) in git, which is a few bug patches on top of 4.3.8 but before most of the recent feature work started merging.
I will work on a reproducer script and close this for now.
The c code for updtr suggests that auto_interval=true can be given to either updtr_add or updtr_start; we are testing adding it to updtr_start at cluster scale in the updtr config lines given above.

**Comment by baallan** [comment]
@tom95858 @valleydlr 
running 'ldms-static-test.sh auto-interval' produces correct results with c985fa6 (near top of current tree) and with the version on our cluster. It tests samplers running at 1,5,9 second intervals where each rate is on a different sampler daemon.
I also extended the test to run a second sampler at 9,1,5 second intervals on the 1,5,9 interval daemons and it seems to work right for all sets. So the change I have Mark testing should solve the L2 oversample problem.

The test uses updtr_add ... auto_interval=true for all cases, as documented in the man page.

The source code for ldmsd_request.c:updtr_start_handler indicates at line 3697-3701 that auto_interval is also supported there,
but recoding the test script to use updtr_start auto_interval=true yields no auto_interval behavior in spite of the 
```
 updtr->is_auto_task = 1;
```
at ldmsd_updtr.c:1124.

So it seems the implementation of auto_interval may need some cleanup or debugging depending on whether the intent is to support interval/offset/auto_interval uniformly on updtr_add and updtr_start or only on updtr_add.
